# Title: Ritsuko Arc – Day 2 –Afternoon– 1:00 PM
# Location: Haruka Academy, Locker Room
# Background CG: As described   

label ritsuko__sex_scene_2:
    "I heard from her teacher that Ristuko usually has a short solo practice during lunch."
    "After eating an early lunch, I came down here to confront her."
    "I’ve been waiting for an opportunity like this, ever since Ritsuko threatened to expose me before."
    "Normally, there’s nobody using the girls’ locker room at this hour. It’s a bit eerie with nobody around."
    "As I turn a corner, I find Ritsuko here, already dressed up for practice."
    "She turns and stares at me as I come into view."
    ritsuko "Eh? Shinn? What are you doing here!? This is a girls’ locker room, you pervert! Get out!"
    shinn "I want to talk to you."
    ritsuko "No! Get out!"
    shinn "Listen here. I know what you did with the Principal this morning."
    ritsuko "Huh? How did…"
    shinn "Don’t play dumb with me Ritsuko. I followed you earlier on when you met with the Principal in his office."
    "Ritsuko tries to play it cool."
    ritsuko "Oh? And so what if I did?"
    "To counter her arrogance, I flash the photos which I received from the Principal in front of her."
    shinn "I wonder if you are going to keep talking like that now… "
    ritsuko "What… How did you…"
    shinn "Surprised?"
    shinn "You should be. I struck a deal with the principal."
    ritsuko "That bastard!"
    ritsuko "Give me back that photos!"
    shinn "Oh? You sure you wanna do that? There are duplicate copies of it everywhere."
    shinn "Even if you destroy this, there will be more popping up…"
    ritsuko "…"
    "As I had master keys, I took it out and locked the door from behind."
    ritsuko "What… What do you want from me…?"
    "Ritsuko watches as she got herself into big trouble."
    ritsuko "What are you going to do with me!?"
    "I walked up to her slowly with a perverted smile."
    shinn "Well, shall I reenact what the principal did to you just now?"
    ritsuko "No. Go away!"
    "I grab her hands while she was struggling. It was difficult to do anything to her while she is struggling."
    "Luckily, there was a rope next to her and I tried to grab it while restraining her from running away."
    ritsuko "Let go of me you bastard!"
    ritsuko "What do you think you are doing?! Do you know how I am?!"
    "Not paying attention, I proceed to tied up her hands behind her back."
    "She was lay down restrained in the bench."
    shinn "That’s more like it now that you are restrain."
    ritsuko "You think you are going to get away with this!?"
    shinn "No. But I don’t think you are."
    ritsuko "What?"
    "I forced open her legs to reveal that beautiful pink stripped panties."
    shinn "Oh nice. It’s been a while since I see such a cute pantie."
    ritsuko "Wait. What are you doing? Stop it!"
    shinn "Stop? You must be joking. There’s no turning back now."
    ritsuko "No."
    shinn "Well. You should have thought about it when you tried to expose me."
    "I flopped out my erected dick after seeing how beautiful that pantie she was wearing at the moment."
    ritsuko "Get away from me, you creep."
    shinn "Creep? Ah! Says the one who is willing to use her own body for a cover up."
    ritsuko "…"
    shinn "Oh? Did I get it right?"
    ritsuko "Shut up!"
    shinn "This is even more exciting. I never had someone so resistant for quite a while now."
    shinn "Well then… Let’s begin."
    ritsuko "No."
    "I move open her panties to see her tainted vagina."
    shinn "It looks amazing even after its being recently used, Ritsuko."
    ritsuko "No. Please don’t."
    "I took my fingers out and place onto her vagina."
    ritsuko "What… What are you doing?"
    "Slowly, I stick my fingers into her vagina."
    ritsuko "Ah…"
    shinn "Heh."
    "I tried to push it in deeper inside her and she was sure finding it hard to resist."
    ritsuko "No~ Its too deep…"
    shinn "Deep? I have not even inserted completely yet."
    "As I push on, the wall within the vagina was crushing my fingers."
    "She was tightening it up her inside, this only mean that he is felling the pleasure."
    shinn "So tell me. My fingers feel good or was it the principal tongue? "
    ritsuko "…"
    shinn "No answer? Very well…"
    "I increase my fingers movement inside her. It is also like as if I am scrapping her inside."
    ritsuko "Ah~ "
    "This time round, she is feeling more now."
    shinn "See. You love it, don’t you?"
    ritsuko "No…"
    shinn "Well. I am going to keep fingering you till you cum, Ritsuko."
    ritsuko "Hmm…"
    "I increase my movement and the walls got tighter and wetter."
    "She started to pant and was feeling rather hot now."
    ritsuko "Ahh~"
    shinn "If you want to cum, you can just do so, you know? "
    "I finger her faster and faster."
    "She was breathing faster, which only means that her heartbeat is increasing."
    "She is clearly enjoying it at this point."
    shinn "I am going to show you who is the best. Not the principal, but me."
    "I finger her extremely fast now and her body was shaking."
    ritsuko "Ah! NOO!"
    shinn "Squirt it all out! Squirt it out like a dirty slut!"
    ritsuko "AHHH!"
    "She was at her limit as her pussy juice shot out like a fountain, while my finger was still inside."
    ritsuko "AH! I’m cumming!"
    "Her juice was all over her body and it was looking hot on her."
    shinn "Looks like you do love my fingering more than principal licking after all."
    shinn "I never seen you cum so much when the principal licks your pussy."
    "I took a closer inspection at her pussy…"
    shinn "Well… Seems like your pussy is now well marinated enough."
    shinn "I think it’s time for me to insert my dick."
    "I wasted no time and slowly inserted my dick into her vagina."
    shinn "Ah. Its still so tight after all the loosening up.  "
    ritsuko "Ah~"
    "As I slowly inserted in, pussy juice was starting to leak out bit by bit."
    shinn "Hahahaha… After cumming so much just now, your juice leaks out the moment I inserted in."
    ritsuko "No…."
    shinn "Haha… There is no point in saying no now."
    "I proceed to move up and down."
    shinn "How does it feel?"
    ritsuko "No…"
    shinn "Tell me… Does my dick feel better or the principal dick that you had tasted earlier on?"
    ritsuko "…"
    ritsuko "None…"
    shinn "None? But your pussy juice is leaking and you are getting more wet than before."
    ritsuko "That’s… not the case…"
    shinn "Are you sure? It seems more wet than when principal was fucking you just now."
    ritsuko "NO!"
    shinn "Oh. How aggressive."
    shinn "Well… We’ll see about that."
    "I started to increase my motion and it was getting faster and faster."
    ritsuko "Ah~"
    "She was starting to moan a little…"
    shinn "Heh… Look at you. Not being honest with yourself at all…"
    ritsuko "…"
    "I pounded her hips more and more."
    "She was letting out an even louder moan now."
    ritsuko "Hmm~ Ah~	"
    shinn "Yea. Keep moaning like a bitch, Ritsuko."
    shinn "This is you Ritsuko. This is your actual inner self. Embrace it!"
    ritsuko "Hmm~ No…"
    "As her moaning get more prominent, her inner wall is getting tighter."
    shinn "Arh. You are squeezing me really hard here."
    shinn "You really seems to be enjoying it now, huh?"
    shinn "I guess the principal must have screw you pretty well back there."
    shinn "So much so that you are getting the hang of it now."
    ritsuko "…"
    "She didn’t respond, but her body is telling me she is enjoying it."
    "By this time, her pussy was already wet and I was reaching my limit too."
    shinn "I’m at my limit Ristuko! I am going to shoot inside you!"
    shinn "Time for me to cum! Ritsuko!"
    "She didn’t say a word, but look at me with fear in her eyes."

    if persistent.cum == "inside":
        shinn "I am going to let you taste of different other guys cum are!"
        $ renpy.block_rollback()
        jump ritsuko__sex_scene_2_inside

    elif persistent.cum == "outside":
        shinn "I am going to let you taste of different other guys cum are!"
        $ renpy.block_rollback()
        jump ritsuko__sex_scene_2_outside

    else:
        menu:
            shinn "I am going to let you taste of different other guys cum are!"
            "Cum inside":
                $ renpy.block_rollback()
                jump ritsuko__sex_scene_2_inside
            "Cum outside":
                $ renpy.block_rollback()
                jump ritsuko__sex_scene_2_outside

label ritsuko__sex_scene_2_inside:
    shinn "I am going to cum, Ritsuko and you are going to take it all inside you!"
    ritsuko "Hmm. No. Please…"
    "I pound her even harder as I reached my climax."
    shinn "Argh! Here it comes!"
    "In one shot, I let it all out pouring directly into her womb."
    "It was so pleasuring fucking a rich girl, I shot out extra and my cum pour out of her vagina in excess."
    ritsuko "NOOOO~"
    "Ritsuko felt an electrifying sensation of pleasure from her body all the way up to her brain."
    "Her eyes rolled up and tongue stood out."
    "It was almost as if at the moment, all the energy she had was drained out from her."
    "I pull out my dick to reveal the creampie that I had made with a mixed of her pussy juice."
    shinn "Heh. What a wonderful sight this is."
    shinn "You look like you enjoyed it much more than the principal dick."
    "I proceed to untie her."
    shinn "There you go. You are free now."
    "Surprisingly enough, she didn’t respond, retaliate or something."
    thinking "Looks like I broke her."
    "I took out the photos…"
    shinn "These photos are going to be kept with me."
    shinn "Listen here, Ritsuko. If you ever tell anyone about this, I am going to expose you and your family is going to be a big trouble."
    "Ritsuko didn’t respond, but just stare at Shinn."
    jump ritsuko__sex_scene_2_end

label ritsuko__sex_scene_2_outside:
    shinn "I am going to cum Ristuko. And I am going to shoot it all out in your face."
    ritsuko "No. Stop it! Please!"
    "I pound her even harder as I reached my climax."
    shinn "Argh! Here it comes!"
    "I quickly pull out and spray directly into her face."
    ritsuko "Ahh~"
    "The cum was everywhere and it landed on all over her face."
    "The smell of my cum triggered her brain giving her a sensation of pleasure."
    "Her eyes rolled up and tongue stood out."
    "It was almost as if at the moment, all the energy she had was drained out from her."
    shinn "Look at that wonderful face."
    "I took out the photos… "
    shinn "These photos are going to be kept with me."
    shinn "Listen here, Ritsuko. If you ever tell anyone about this, I am going to expose you and your family is going to be a big trouble."
    "Ritsuko didn’t respond, but just stare at Shinn."
    "I removed the tied hands behind her back."
    shinn "There you go, you are free now."
    jump ritsuko__sex_scene_2_end

label ritsuko__sex_scene_2_end:
    shinn "Well then, in that case. I will take my leave."
    shinn "Oh. And before you go, today’s class is cancelled. You can take your time the whole afternoon to think what you have done."
    shinn "Bye now!"
    "I left the room leaving Ritsuko behind and the mess that I had made."
    $ renpy.end_replay()
    $ persistent.ritsuko__sex_scene_2 = True
    jump ritsuko__intermission_1

# Title: Ritsuko Arc – Day 3 –Afternoon– 3:30 PM
# Location: Haruka Academy, Classroom 3-2
# Background CG: As described   

label ritsuko__intermission_1:
    "I spend the whole day thinking about what I had done to her yesterday."
    "And here I am expecting her to come to class today."
    thinking "Hmm… Maybe I was a little too harsh on her yesterday?"
    thinking "I’m not surprised that she will be coming at all."
    "Nonetheless, I continue to wait."
    "However, as hours gone by and the sun was setting down. There is still no sign of her."
    thinking "Well. I guess that she is coming after all."
    thinking "Guess I will leave then."
    "I packed up and left the class."

# Title: Ritsuko Arc – Day 3 –Afternoon– 5:30 PM
# Location: Haruka Academy, Hallway
# Background CG: As described   

    "As I walked along the hallway, I saw Ritsuko in a distance from outside the window."
    thinking "Oh. She’s there."
    "She seems to be tennis court playing."
    thinking "Maybe I should check on her."
    "I proceed to head to the tennis court."
    jump ritsuko__tennis_scene_1

# Title: Ritsuko Arc – Day 3 –Afternoon– 5:35 PM
# Location: Haruka Academy, Tennis Court
# Background CG: As described   

label ritsuko__tennis_scene_1:
    "As I went there, Ritsuko instantly spotted me."
    ritsuko "You! Why are you here!"
    "Out of anger, she threw tennis ball at me."
    shinn "Ow! Hey! Stop it!"
    "I could see her eyes getting watery."
    shinn "Relax. I am not going to hurt you."
    ritsuko "Liar! All men are the same! All of you are pigs!"
    shinn "Woah. That’s a bold statement. You got to calm down girl."
    ritsuko "Shut up! I do not want to hear that from you."
    ritsuko "After what you have done. How could you!?"
    shinn "How could I what? It’s just sex. No big deal."
    ritsuko "No big deal? The principal took my first time! And I was humiliated!"
    shinn "So?"
    ritsuko "I am supposed to give it to someone special!"
    shinn "Pff… Only people like you believe in that kind of fairy tale. Grow up please."
    ritsuko "So what the hell do you want from me?!"
    shinn "Well… Let’s see…"
    shinn "Seeing how much of a snobbish person you are. I want to humiliate you."
    ritsuko "You…"
    ritsuko "You are really the worst of a kind."
    shinn "Just to let you know, I stuck a deal with the principal to turn you into a cum dump sex slave for the principal."
    ritsuko "What?"
    shinn "Yea. If not, why did you think I could get a hold on the photos."
    ritsuko "You are a monster…"
    "I let out a laugh."
    shinn "Hahahaha…."
    shinn "Monster? I have people calling me that before."
    shinn "Such insult and name calling is pretty immune to me right now."
    ritsuko "So the rumors and what I saw back then was true after all."
    ritsuko "You’re the bastard that screw around all of our female teachers and principal and force them to resign."
    shinn "Hahaha…"
    shinn "Well. Since it has come to this, there is no point in denying it."
    shinn "Yes. It is true in what you said. And what you almost saw back then was true too."
    ritsuko "So, you lied to me…"
    shinn "Heh… So, what if I do? What are you going to do about it?"
    ritsuko "…"
    shinn "Frankly speaking, if you had expose me at the storeroom back then, I would had done it back then on you too."
    shinn "Rather than having to wait till now…"
    ritsuko "you sicko!"
    shinn "That’s right keep calling me names. In the end, I have the upper hand here."
    ritsuko "You…"
    "I took out the photos and shown her."
    shinn "Yes. I almost thought you forgot about this."
    shinn "As long as I have this, you are going to be trained as a proper sex slave."
    shinn "And you know what? Let’s do it now."
    ritsuko "Huh?"
    shinn "Take off all your clothes."
    ritsuko "What? Here!? "
    shinn "Where else?"
    ritsuko "No way! I am not doing it here out in the public!"
    shinn "It’s here or leak photos. You choose."
    ritsuko "…"
    ritsuko "Fine…"
    "Ritsuko slowly stripped her clothes off in embarrassment"
    ritsuko "This… This is so embarrassing…"
    "Her face was blushing which gives off a cutesy charm in her."
    thinking "Damn… She is kinda cute even though she is such a bitch."
    "She took off everything and try to cover her chest and under area with her hands."
    "She was so embarrassed that she didn’t even want to look at me."
    shinn "Now wear your panties over your head."
    ritsuko "Huh? No…"
    shinn "Do it and after that, squat down."
    ritsuko "…"
    shinn "You sure you want to refuse?"
    ritsuko "Fi— Fine."
    "Ritsuko took the panties and wear over her head, while she tries to squat down, revealing her pussy to me."
    ritsuko "This… This is disgusting!"
    "The sight of the pussy remains me of all the good time I had yesterday with her."
    "Upon closer look, I saw leaks from her vagina."
    shinn "Haha… You are aroused by this, aren’t you?"
    ritsuko "No! I’m not!"
    shinn "Is that so? Your pussy looks so wet."
    ritsuko "That’s not it…"
    shinn "Tsk Tsk…"
    shinn "Ritsuko. You should be more honest."
    ritsuko "Shut up! What do you want me to do next!"
    shinn "Lift up your hands and fold them in the back so that I can see your armpits."
    "As she lifts up, her beautifully clean shaved armpit were being exposed."
    ritsuko "Li— Like this?"
    shinn "Yes. That’s right."
    shinn "Wow. I got to say. Your armpits look amazing. I bet it smells good too."
    ritsuko "You are such a sicko!"
    shinn "Now now… No need to be so rude."
    shinn "Let’s see what’s next?"
    thinking "She is in a humiliating position right now. Might as well as ask her to say some degrading statement."
    shinn "I want you to say out the following statement."

    menu:
        ritsuko "Huh?"
        "I am Shinn’s personal sex toy!":
            shinn "Say “I am Shinn’s personal sex toy!”"
            ritsuko "No! I am not going to do that!"
            shinn "Do it or else…"
            ritsuko "Fi— fine…"
            ritsuko "I’m Shinn’s personal sex toy…"
            "She was mumbling and it was hardly audible from my distance."
            shinn "What? You gotta say louder. I can’t hear you."
            "Ritsuko gives me a glaring, yet defeated look."
            ritsuko "I AM SHINN’S PERSONAL SEX TOY!"
            ritsuko "THERE! YOU HAPPY NOW?!"
            "She shouted at the top of her lungs. Bet that the entire school could hear her."
            shinn "Haha… Good girl."
            "I walked up to her and picked up the tennis racket at the side of her."
            shinn "Your wish is my command, Ritsuko."
            jump ritsuko__tennis_scene_1_urine
        "I want Shinn’s baby making seed inside me!":
            shinn "Say “I want Shinn’s baby making seed inside me!”"
            ritsuko "No! I am not going to do that!"
            shinn "Do it or else…"
            ritsuko "Fi— fine…"
            ritsuko "I want Shinn’s baby making seed inside me…"
            "She was mumbling and it was hardly audible from my distance."
            shinn "What? You gotta say louder. I can’t hear you."
            "Ritsuko gives me a glaring, yet defeated look."
            ritsuko "I WANT SHINN’S BABY MAKING SEED INSIDE ME!"
            ritsuko "THERE! YOU HAPPY NOW?!"
            "She shouted at the top of her lungs. Bet that the entire school could hear her."
            shinn "Haha… Good girl."
            "I walked up to her and picked up the tennis racket at the side of her."
            shinn "But today, there will be no baby seed inside your vagina."
            "I took the racket and jammed the handle inside her."
            jump ritsuko__tennis_scene_1_urine

label ritsuko__tennis_scene_1_urine:
    ritsuko "Ah! IT HURTS!"
    "She was shock and in pain. But as I inserted in, she immediately cum."
    ritsuko "Take it out!"
    shinn "Take it out? You seem to be enjoying it."
    ritsuko "No. That’s not true. Please take it out!"
    shinn "Heh. You wish."
    "I went around her back and unzip my pants."
    ritsuko "Wait. What are you doing?"
    shinn "Heh. Yesterday I had fun with your vagina. Today, I will have some fun with your anal."
    ritsuko "What?! No! You can’t do it!"
    shinn "Hahaha…"
    "Ignoring her pled. I stick my dick into her anal while she maintains her position."
    ritsuko "Ah! No!"
    "The moment I inserted it, she was legs were trembling in pleasure added with racket that is still inside her."
    "Her anal hole was warm and as I slowly move, she let out a moan."
    ritsuko "Ah~"
    shinn "See? You love it!"
    ritsuko "No! Ah~"
    shinn "Admit it, Ritsuko! You are nothing but a slut!"
    "I started to pound her ass harder and pleasure was building up in her."
    ritsuko "Mmm~ Please…"
    "Her eyes were getting blurry and she looks like she was about to give in."
    shinn "Just face it. You love sex. You love it so much like a slut."
    ritsuko "…"
    shinn "No answer? You will soon."
    "I violently push my dick in so fast that it snaps her."
    ritsuko "Ah!"
    shinn "You are mine Ritsuko. My sex slaves! You understand?!"
    ritsuko "Ah! Feels… Good…"
    "She continues to moan and this time round, it got louder."
    ritsuko "Ahh~ It felt good."
    "It felt good indeed that her pussy juice was leaking out down the tennis racket."
    shinn "That’s right. Now you starting to understand."
    "As I was doing her harder and harder, her anal hole got tighter."
    "It was squeezing my dick out and making it difficult for me to last."
    shinn "Hey Ritsuko. Do you want my cum?"
    ritsuko "Ye.. Yes…"
    shinn "Good girl."
    "I started to move faster and I can feel that cum are about to come out."
    shinn "Here it comes, Ritsuko! Take it all!"
    ritsuko "Ah! Yes!"
    "A sudden spurt of cum flows right into her anal."
    ritsuko "Ahh!! I can feel your warm cum in my stomach!"
    "The pleasure was overwhelming for her as her leg’s trembles in pleasure."
    "So much so that she ejected out the racket from her pussy by force."
    ritsuko "Ah! It feels so good!"
    "After releasing the last drip, I stick my dick out as the cum flow out of her anal hole."
    ritsuko "This is so good! I can’t take it anymore. I need to pee!"
    shinn "Pee? Did I give you permission to pee?"
    

    menu:
        ritsuko "Ah! Please, Shinn! Let me pee!"
        "Let her urine":
            shinn "Alright then. Since you are nothing but a dog now. Go ahead."
            ritsuko "Ah~ Thank you."
            "A yellow urine was squirting out from her urethra."
            ritsuko "Ah! It feels so good! I want more sex!"
            shinn "You want more? Good. Let’s do more!"
            shinn "Let’s bring you to my house for a good baby making session."
            ritsuko "Yes!"
            jump ritsuko__tennis_scene_1_house

        "Don’t let her urine":
            shinn "Pee? Who said you can do that? You are not allowed to pee."
            ritsuko "But Shinn! I need to pee. I can’t hold it."
            shinn "You are to hold it. You are not allowed to pee without my permission."
            ritsuko "No… I can’t hold much longer."
            "A sudden gush of urine squirted out from her urethra."
            ritsuko "Ah! I’m sorry Shinn!"
            shinn "What the…"
            ritsuko "Ah! Peeing suddenly feel so good!"
            shinn "Look at you. From being noble and elegant, now you are be reduced to nothing but a pet craving sex slave."
            shinn "Seems like I am going to punish you to teach you some manners."
            ritsuko "Ah yes! Please punished me Shinn!"
            shinn "Good. Let’s bring you to my house for a good lesson of manners."
            ritsuko "Yes!"
            jump ritsuko__tennis_scene_1_house

# Title: Ritsuko Arc – Day 3 –Night– 7:35 PM
# Location: Shinn’s Bedroom
# Background CG: As described   

label ritsuko__tennis_scene_1_house:
    "As it was still early in the night. I bought Ritsuko back to my bedroom after a good session at the tennis court earlier in the day."
    ritsuko "Ah Shinn~"
    ritsuko "Are you going to have more lesson here in your room?"
    "I look at her with a little arrogance."
    shinn "More than just a lesson, I am going to pound you hard."
    "Those words that utter out from my mouth, make Ritsuko feel excited."
    ritsuko "Let’s get started then!"
    "Rina stripped naked in front of me even without me telling."
    ritsuko "You like my body, right?"
    "Her body is simply out of this world for a tennis girl like her."
    "I sometimes wondered how did she get such body in the first place."
    "Or was she naturally gifted like that?"
    "As I continue to lust her body, I felt the sense of pity that I have to give her to the principal eventually."
    "It was inevitable since I made a deal. But before handing over to him, I am going to have my fun."
    "Without instruction, Ritsuko lied down on my bed facing me."
    ritsuko "Come on~ "
    shinn "Heh. Did I ask you to lie down and strip naked without my permission?"
    shinn "You were supposed to listen to orders!"
    "I striped myself naked and jump right on top of her."
    shinn "I am going to pound you hard so that you remember to do what you were told!"
    "I slammed my dick right into her vagina as she was screaming in pleasure."
    ritsuko "Ah~ Shinn!"
    "I continue to pound her."
    "She was showing no sign of resisting and even encourage for more."
    ritsuko "Yes. Shinn~ More~"
    shinn "Remember this pleasure! Remember this feeling! Cause that is what you are made for and what you are meant to do in life!"
    ritsuko "Yes. Yes master~"
    "There weren’t any form of hesitation from her or from me."
    "Pounding after pounding, I keep going like some wild animal on the loose."
    "I am intending to keep having sex like some crazy rabbits all night with her."
    "It didn’t take long before she desires of the one thing, she is made to received."
    ritsuko "Ah Shinn! I want your cum inside me so badly. Please give it all to me!"
    shinn "Heh. You love to have my cum, eh?"
    ritsuko "Yes. Please."
    shinn "As you wish!"
    "My whole body was pressing against her as I was trusting her hips."
    "The movement was so much that the bed was literally shaking."
    "I hope the bed is intact after this mating session."
    "As I pounded on, I tried to reach deep inside her as much as I could."
    "So that when I cum, it will directly into womb. Increasing her joy of pleasure."
    ritsuko "Ah! Shinn! You are so deep inside me! I love it!"
    ritsuko "I can feel the tip of your penis in my womb, it making me feel so good!"
    shinn "Yea. Keep taking it!"
    "Her pussy was slippery wet making it so easy for me to move about."
    "She still had the sweaty residue from all her tennis training earlier on."
    "I saw her armpits and it was amazing. I really want to have a taste of it."
    shinn "Ritsuko. Lift up your arms for me."
    ritsuko "Huh? O… Okay…"
    "She lifted her arms up to show me that amazing armpits of her."
    "It was hot and steamy. And I couldn’t resist it."
    "I stick my tongue out and started to lick it"
    ritsuko "Kya~ Shinn~"
    ritsuko "That’s dirty~"
    "I ignored her and continue to lick her."
    "The sweaty taste of a sport girl armpit was amazing."
    "It might be disgusting from someone point of view. But it wasn’t to me at all."
    "I enjoyed it very much and it was the tasty sweat that give its way."
    "As I continue to lick her, I kept pounding onto her hips even harder."
    ritsuko "Ah! Shinn! Kiss me!"
    ritsuko "Stop licking my armpit and give me a lovely kiss."
    "I stopped licking her and move my tongue closer to her and give her a good lovely kiss."
    "She stood her tongue and our tongue docked with each other so lewdly."
    "The sound of slurping and sucking at our own saliva was so lewd that Ritsuko wants more."
    ritsuko "Mmm~ Shinn…"
    "The kissing was intense as it should…"
    "In fact, it was so intense that Ritsuko didn’t want to stop."
    ritsuko "Mmm~"
    "We had been on for a while now, fucking and kissing her like that."
    "I can feel my balls are getting ready to explode soon."

    if persistent.cum == "inside":
        "The feeling of climax is coming…"
        $ renpy.block_rollback()
        jump ritsuko__sex_scene_2_house_inside

    elif persistent.cum == "outside":
        "The feeling of climax is coming…"
        $ renpy.block_rollback()
        jump ritsuko__sex_scene_2_house_outside

    else:
        menu:
            "The feeling of climax is coming…"
            "Cum inside her":
                $ renpy.block_rollback()
                jump ritsuko__sex_scene_2_house_inside
            "Cum onto her face":
                $ renpy.block_rollback()
                jump ritsuko__sex_scene_2_house_outside

label ritsuko__sex_scene_2_house_inside:
    shinn "Ah! I’m at my limit!"
    ritsuko "Yes! Shinn! Do it! Cum inside me!"
    thinking "Not sure if I want to take the responsibility though."
    thinking "But who cares? I can choose to take responsibility later on if I want to."
    ritsuko "Hurry up Shinn! Do it!"
    shinn "Here it comes!"
    "I give it a one last slam and my dick pierce through into her womb."
    "The gush of cum instantly releases and was overflow in seconds."
    ritsuko "Ah! Shinn’s cum! Its inside me!"
    ritsuko "I am going to get so full with Shinn’s cum!"
    "The cum was too much and started to leak out."
    shinn "That’s a lot of my cum milk flowing around. I’m pretty sure you are going to love it all."
    "The thought of it got Ritsuko excited."
    ritsuko "Ah. Shinn’s cum is inside me…"
    "Despite cumming so much, just the look of her creampied pussy got me hard again."
    shinn "Look at you. Completely mind broken, you are just the way I want."
    "I give Ritsuko a staring look into her eyes."
    shinn "If you think this is all, then you are wrong, Ritsuko."
    shinn "The night is still young."
    ritsuko "Ah yes! More! Give me more."
    shinn "Good girl. That’s the spirit."
    "I position my rock-hard dick onto her vagina again."
    shinn "Now then, let’s continue!"
    jump ritsuko__sex_scene_2_house_end

label ritsuko__sex_scene_2_house_outside:
    shinn "Ah! I’m at my limit!"
    ritsuko "Yes! Shinn! Do it! Cum inside me!"
    thinking "I want to cum inside her…"
    thinking "But I like the look of her face being smear with my cum all over."
    ritsuko "Hurry up Shinn! Do it!"
    thinking "What should I do…"
    thinking "Ah. Screw it. I have plenty more to go, I will just cum this round in her face."
    shinn "Here it comes!"
    "I pull out just in time and spray my cum all over her face like a firehose."
    ritsuko "Ah~ Shinn’s cum is all over me."
    "I stopped for a moment while admiring her slutty face."
    shinn "Hehe… Look at you."
    "Despite cumming so much, just the look of her face smear with cum kept me hard."
    "However, Ritsuko was feeling a little unsatisfied."
    ritsuko "Um… Shinn cum not inside me…"
    shinn "Don’t worry, Ritsuko. I have plenty more left for you to train."
    shinn "Besides, the night is still young. I’m pretty sure you are going to get satisfied all night long."
    "The assurance of it gotten her excited again."
    ritsuko "Really?"
    shinn "Yea. Of course."
    "I position my rock-hard dick onto her vagina again."
    shinn "Now then, let’s begin!"
    jump ritsuko__sex_scene_2_house_end

label ritsuko__sex_scene_2_house_end:
    ritsuko "Yes master!"
    $ renpy.end_replay()
    $ persistent.ritsuko__sex_scene_2 = True

# Title: Ritsuko Arc – Day??? –Afternoon – 2.10 PM
# Location: Principal Office
# Background CG: As described   

label ritsuko__threeway:
    "It has been days since…"
    "I trained her every single day and no had lost track of time."
    "Looking back, her slow transition from a rich snobbish girl to a sex craze bitch is astonishing."
    "She is now submitted to any form of pleasure given by us."
    "I decided that it is finally time to bring Ritsuko back to the principal office as promise."
    "She wore nothing but a sexy pink bikini slingshot with a dog collar around her neck."
    "Her erected nipples was showing and she was looking ready for more action."
    shinn "We are here, principal."
    principal "Ah. Shinn. I was wondering when are you ever going to show up."
    ritsuko "Hi! ~"
    principal "Oh. What do we have here?"
    ritsuko "It’s me! Slutty Ritsuko!"
    principal "Wow. You look so hot."
    shinn "Yes. As you can see, I had broken her, Principal."
    shinn "She is all well trained now to be your bitch."
    shinn "Just the way you wanted. You can do whatever you want to her and she will comply like a willing slave."
    ritsuko "Teehee~"
    ritsuko "I can’t wait to suck your big fat cock! ~"
    principal "Good."
    principal "You trained her well. As expected from you Shinn."
    shinn "Thank you, Principal."
    principal "Now then, shall we have some fun with her?"
    shinn "We?"
    principal "Yes. We. You work hard to make her like that, let’s have fun together."
    principal "You deserve it."
    thinking "Well… It isn’t as if I didn’t had fun training her."
    shinn "If you insist…"
    principal "Do you want to have a taste of my dick, Ritsuko?"
    ritsuko "Yes! ~"
    principal "Good girl. Come here."
    "The principal unzips his pants and show his steamy erected dick to Ritsuko."
    ritsuko "Ah! Dick!"
    "The principal approach her and carry her on his weight."
    ritsuko "Kya~"
    "The principal lifted up her both legs all the way and hang his dick out near her vagina."
    ritsuko "Ah~ Principal’s Dick. I can feel it."
    ritsuko "Please insert it in, principal! I want your dick so badly!"
    principal "Good girl. I shall grant you your wish!"
    "The principal slowly inserted his dick in."
    ritsuko "Ah~ It’s so big, I love it!"
    "The principal inserted all the way into the tip of her womb."
    ritsuko "Principal! Your dick is kissing my womb! It is making me crazy!"
    "Ritsuko took the initiative and stick her tongue out, requesting for a tongue kiss."
    ritsuko "Principal~ I want a tongue kiss too~"
    principal "Here you go."
    "The principal sticks his tongue out and dock with her tongue."
    "Both of them give each other a good licking, so much so that salvia was drooling out."
    ritsuko "Hmm~ Principal saliva is so tasty."
    principal "Hahaha…"
    "The principal was very pleased with my training on her."
    principal "Shinn! What can I say? You are one of a kind."
    shinn "Err… Thank you?"
    principal "Thank you?"
    principal "Come on! What are you waiting for?"
    principal "Didn’t you agree to have fun with us earlier on?"
    principal "Her anal hole is cold and in need of someone to warm it up for her."
    ritsuko "Yea~ Hurry up Shinn. Stick your dick into my shit hole!"
    shinn "…"
    thinking "These people are really on fire today…"
    "I approached Ritsuko from her back and unzip my pants."
    "Seeing how slutty Ritsuko acted on Principal makes me hard enough."
    thinking "Time to relieve my erection on her."
    "I slowly position myself and stick it into her anal."
    ritsuko "Ah! Two dicks inside me. Its feel so good!"
    ritsuko "I cumming! Ahh~"
    "Just by having two dicks, Ritsuko instantly came as her pussy juice was forced out."
    principal "Hahaha… "
    principal "I have not even started moving yet and you already cum!"
    principal "What a slut!"
    ritsuko "Please principal. Please move your big fat cock!"
    principal "Very well then, I shall start moving."
    "The principal started moving and I follow suit and move in unison."
    "The pace was rather slow at the beginning, but that was enough for Ritsuko."
    ritsuko "Ah! Yes~ Dicks! Dicks!"
    "Ritsuko mind was nothing but dicks and dicks."
    shinn "Hehe… You love dick, don’t you?"
    ritsuko "Yes. I love dick and I want to taste them all!"
    principal "Hahaha… You will get to taste them all you want today!"
    ritsuko "Yes. Thank you, principal. Be sure to give me all the semen in your balls today."
    ritsuko "I would love to have a taste of it!  "
    "The principal started to increase the speed of his penetration and I followed suit to keep the same pace as him."
    thinking "Damn this principal. Despite the fact that he is old enough, he still has a lot of energy pounding a girl."
    "As the penetration speed increases, Ritsuko was feeling the joy and pleasure like a proper slut."
    "On the other hand, I am struggling to keep up the pace. It does really show who is the alpha here."
    "I’m just lucky that he didn’t seek out doing such things like I did. Otherwise, I would have a rival to complete."
    "As both of us went on drilling her, her pussy juice was starting to leak out more after she came and it was making the floor wet."
    "The wet floor did not go unnoticed by the principal…"
    principal "Ah! Your pussy juice is making a mess on my office’s floor."
    principal "You’re a naughty girl, Ritsuko. I am going to punished you!"
    "Principal start to move his hips faster and faster."
    ritsuko "Kya~ "
    principal "You like that, don’t you? "
    ritsuko "Yes~ Harder! Please!"
    principal "Heh. Are you happy now? Being such cock worshipping slut?"
    ritsuko "Yes. I am happy now. I love it!"
    principal "Good girl. But your vagina is squeezing me, you want me to cum, eh?"

    if persistent.cum == "inside":
        ritsuko "Yes! I want your thick baby making milk!"
        $ renpy.block_rollback()
        jump ritsuko__threeway_inside

    elif persistent.cum == "outside":
        ritsuko "Yes! I want your thick baby making milk!"
        $ renpy.block_rollback()
        jump ritsuko__threeway_outside

    else:
        menu:
            ritsuko "Yes! I want your thick baby making milk!"
            "Cum inside her":
                $ renpy.block_rollback()
                jump ritsuko__threeway_inside
            "Cum Outside":
                $ renpy.block_rollback()
                jump ritsuko__threeway_outside

label ritsuko__threeway_outside:
    "The principal is almost reaching his limit…"
    principal "Ugh… I can’t hold on much longer."
    "On the other hand, I was reaching my limit too."
    shinn "Ugh… Me too."
    ritsuko "Please cum! Please!"
    ritsuko "Please cum on this slutty cum dump bitch!"
    principal "Alright Shinn, let’s cum together on her and give her shower of baby making milk!"
    ritsuko "Yes~"
    principal "Here it comes!"
    "Both me and the principal gave its last pound on her butt and hips hard and stick it out."
    "A burst of cum shower all over her body from the top to the bottom."
    ritsuko "Ah! Cum! It’s all over me!"
    ritsuko "I love the taste, I love the smell, I love it all!"
    "The overwhelming cum sent shockwave through her entire body."
    ritsuko "Ah~ Cum~"
    "From the looks of it, her desire of cum is going to go away anytime soon."
    principal "Hey. Could you do a slutty peace sign? "
    principal "I wanna see it."
    ritsuko "Okay!"
    "She lifted her hands up and give a peace sign between her eyes."
    ritsuko "Peace~"
    principal "Oh~ You are making me hard now."
    shinn "Heh. Its too bad that we didn’t creampie her."
    principal "Don’t worry. We have all day."
    principal "We are going to creampie her till she gets pregnant by today."
    ritsuko "Yes! Please make me your cumdump girl for pregnancy!"
    jump ritsuko__threeway_end
    
label ritsuko__threeway_inside:
    "The principal is almost reaching his limit…"
    principal "Ugh… I can’t hold on much longer."
    "On the other hand, I was reaching my limit too."
    shinn "Ugh… Me too."
    ritsuko "Please cum! Please!"
    ritsuko "Please cum on this slutty cum dump bitch!"
    principal "I am going to make you pregnant!"
    ritsuko "Yes! I want principal baby! I want it!"
    principal "Here it comes!"
    principal "Get pregnant Ritsuko! Get pregnant and have my baby!"
    "Both me and the principal gave its last pound on her butt and hips and shot it all inside her."
    "A burst of cum exploded into her vagina and her anal hole giving her a double creampie."
    "It was so much that some of the cum flow out and drip to the floor."
    ritsuko "AH! ITS INSIDE ME!"
    ritsuko "PRINCPIAL THICK BABY SEED IS INSIDE ME!"
    ritsuko "I can feel my egg being fertilized by principal sperm!"
    principal "Hahahaha!"
    principal "Hey. Could you do a slutty peace sign? "
    principal "I wanna see it."
    ritsuko "Okay!"
    "She lifted her hands up and give a peace sign between her eyes."
    ritsuko "Peace~"
    principal "Oh~ You are making me hard now."
    principal "I am going to fuck you everyday to make sure you are properly pregnant, do you understand?"
    ritsuko "Yes! Darling~"
    principal "Shinn. Let’s take turn today."
    shinn "Heh. Sure. Its going to a lot fun."
    jump ritsuko__threeway_end

label ritsuko__threeway_end:
    $ renpy.end_replay()
    $ persistent.ritsuko__threeway = True
    scene black with fade
    "END OF RITSUKO ARC"
    $ tennis_available = False
    jump map__school