label ask_about_aina:
    "When I first met Touko, she was together with Aina. And from the way they talked, it seems like they're very close."
    "Maybe Touko has some useful information I could use against Aina? I should ask what she has to say about her."
    shinn "Since it's just us here right now, there's something I'd like to ask you."
    touko "Hm? What is it?"
    shinn "When I first met the two of you, it seemed like you and Aina were very close. What's your relationship with her?"
    touko "Hmm? Why're you asking?"
    shinn "Since I'm going to be tutoring her too, I thought'd be good to get your impression on what kind of person she is."
    shinn "I'm just trying to be better prepared."
    touko "Ah, I see. Aina, huh?"
    touko "She's a good friend of mine. We used to attend the same middle school together before we came here."
    shinn "The same school?"
    touko "Yeah. We've known each other since a while back."
    touko "Actually, she was the first friend I made back in middle school, and the two of us have been close ever since."
    shinn "I see. What do you think of Aina as a person?"
    "Touko paused for a moment, processing her thoughts."
    touko "Hmm... I guess she's a nice person. She's also always been really energetic."
    thinking "Heh. \"Energetic\"."
    touko "She's also really determined and competitive."
    shinn "I see."
    shinn "Is there a reason why she's also been struggling in math then?"
    touko "Hmm... I guess she's basically like me? We both focus on our sports a lot, so the other stuff gets sidelined."
    touko "Also, she doesn't like math either. So that too."
    shinn "I see."
    touko "Usually, I spend time together with her, and we do some studying together and try to help each other out."
    shinn "Spend time together?"
    touko "Yeah. Like, every weekend, we'll spend time at her house or mine to study math."
    shinn "I see..."
    touko "Usually, when exams are coming up, one of us will stay over at the other's house and we'll stay up studying."
    touko "Like I said before, we're pretty close."
    shinn "Hmm..."
    jump touko_aina_day1_continued

label ask_about_academics:
    shinn "Since it's just us here right now, there's something I'd like to ask you."
    touko "Hmm? What is it?"
    shinn "Is there some reason why you've been struggling so much in math class?"
    touko "Well, I guess I'm mainly just doing bad because I kind of hate math."
    touko "But since I'm spending so much of my time focusing on other stuff I actually enjoy, I don't have a lot of attention left over for it."
    shinn "Ah. I see. Well, that's a pretty common problem."
    touko "Right. So, I was hoping you could help me out with that."
    thinking "Heh. Of course I'm going to \"help.\" "
    shinn "I see..."
    shinn "So, how do you usually study on your own when you're trying to catch up in math?"
    touko "Usually, I spend time together with Aina, and we do some studying together and try to help each other out."
    shinn "Spend time together?"
    touko "Yeah. Like, every weekend, we'll spend time at her house or mine to study math."
    shinn "I see..."
    touko "Usually, when exams are coming up, one of us will stay over at the other's house and we'll stay up studying."
    touko "Oh, I guess I didn't tell you this before, but me and Aina are really close friends."
    shinn "Hmm..."
    jump touko_aina_day1_continued

label touko_aina_day1_continued:
    thinking "Hmm... I think I see how it is."
    thinking "Since these two are such close friends, it should be easier to get the two of them together."
    touko "Erm... Shinn?"
    thinking "Maybe I could swing a threesome... Hehehe..."
    touko "Hello? Are you there?"
    "Realizing I'd gotten lost daydreaming, I quickly pulled myself back."
    shinn "Yeah. Sorry, I was thinking about something."
    "Touko looks at me with concern."
    touko "Are you okay?"
    shinn "Oh, I'm fine."
    shinn "I think that's it for now. Thanks for letting me know. I'll see you later."
    touko "Sure!"
    "I left her alone to her training. As I walked out of the court, my thoughts were focused on the two them."
    thinking "Hmm... this doesn't add up, does it?"
    thinking "The two of them don't seem so dumb that they'd be failing math if they get together every week to study."
    thinking "Especially if they go to the point of studying overnight together every time exams are coming up..."
    thinking "What are they really doing together?"
    thinking "Wait a minute..."
    "Some wild thoughts suddenly spring to mind"
    thinking "Could they be...? "
    "I can't help but give a sinister smile."
    thinking "Haha... If I'm right, this'll be pretty epic."
    thinking "But first, I'll need to investigate, see if I can dig up some proof."
    thinking "Hmm, how am I going to do this?"

    scene bg hallway 1 with irisin
    thinking "Shit!"
    thinking "Its 3.30 PM already. Today's lesson with Touko is supposed to be now. I wonder if she's already there."
    thinking "I should have kept better track of time and been there to wait for her."
    thinking "Let's hope she's not there yet."

    scene bg classroom with dissolve
    show touko angry school arms
    "I approach the classroom and slide open the door."
    "I was hoping to avoid this, but Touko was already there waiting for me."
    "She turns around and gives me an annoyed look."
    touko "You're late.  "
    shinn "Ah yes. My apologies. I wasn't looking at the time."
    touko "It's okay. Since you're here now, let's get this started so we can get it over with quickly."
    thinking "Heh. You sure seem to be in a hurry."
    shinn "Well, that that'll depend on how well you understand the content we'll be covering today."
    "I take out my materials and jot down some notes on the blackboard."
    "The lesson was in session. As I walk her through the material, and explain the various methods to solve the problems in her assignments, Touko seems to be attentive."
    "Or at least, she's trying to be. Now and then, a bemused expression crosses her face."
    shinn "Err... Touko? Do you understand my explanation here? "
    touko "Y.. Yes."
    thinking "Obviously not."
    shinn "You sure? "
    touko "Yes."
    "At this point, the scheduled lesson time is over. So, I decided to give her a little test."
    shinn "Alright, Touko. Since you've gotten the explanation down, you should be able to handle this problem sheet, right?"
    touko "Er... Yes?"
    show touko angry school
    thinking "Not exactly making that sound convincing."
    "Regardless, I pass her the paper."
    shinn "Here you go then. If you don't understand any of the questions, let me know. I'll do my best to help you out with anything you're having trouble with."
    touko "Okay."
    "She sat down with the paper, and started working her way through the questions."
    "While I watched, she seemed to be pretty intently focused on her work."
    thinking "Maybe I should take the opportunity to ask her some more questions and get to know her better."
    shinn "So Touko..."
    touko "Huh?"
    "She replies, half giving me her attention while trying to focus on the sheet."
    shinn "Tell me more about yourself."
    "She pauses, trying to think of something to say."
    touko "Hmm... What do you want to know?"
    shinn "I don't know. Stuff about your life, I guess? "
    touko "My life, huh? Why do you want to know all this?"
    shinn "To get to know you better. I'm probably going to be having these sessions with you for quite a while, after all."
    touko "Hmm, let's see..."
    "She mulls it over for a bit."
    touko "Well, I come from a very strict family."
    shinn "Strict family? What do you mean?"
    touko "Well, my parents are very conservative, and they've always had a lot of rules for me to follow."
    shinn "What? Like how? "
    touko " All sorts of stuff. To begin with, they put up a lot of fuss about me joining the basketball team."
    touko "It took a whole lot of convincing to get them to let me stay on it. And if I break any of their rules, they'll want me off the team right away."
    shinn "What do they want from you then?"
    touko "Well, they want me to be more ladylike..."
    touko "They think that playing basketball will give me a bad attitude and make me too much of a tomboy."
    shinn "Hmm... Interesting..."
    touko "Eh? What's so interesting about that?"
    shinn "I mean, it's pretty uncommon these days for parents to be that restrictive with their kids."
    touko "Yeah, and it gets worse from there."
    shinn "Oh? How so?"
    touko "One of the rules they've set for me is, they don't want me getting into any kind of a relationship."
    shinn "Wow."
    touko "Yeah. If I did, they'd really crack down on me, way more than just making me quit the basketball team."
    touko "Like, they might seriously disown me."
    touko "So, I really can't afford to let anything like that happen."
    touko "They say I'll be ready for a relationship when I have their say-so, and it has to be with a partner who has their approval."
    shinn "Really? You mean like an arranged marriage or something?"
    touko "Yeah, I guess you could put it that way."
    shinn "Yikes. That's harsh."
    shinn "But hey, you're pretty popular with the girls, aren't you?"
    touko "Huh? What you mean?"
    shinn "I've heard that some of the star female athletes here get a lot of attention from other girls in this school, including yourself."
    touko "Yeah, I guess..."
    touko "Honestly, I've gotten a fair number of love letters from other girls before, definitely more than I have from boys. I guess maybe my parents had a point when they worried about me being tomboyish?"
    "Touko stares off into space, apparently lost in thought."
    shinn "Hello? Touko? "
    touko "Oh! Sorry, I guess I kind of went on for a while."
    touko "I'll keep going with the worksheet."
    shinn "Alright."
    thinking "Hmm... Let me think."
    thinking "She did say she's received more love letters from girls than boys, but that doesn't mean that she's into that herself."
    thinking "But from her reaction just now, I have a feeling I'm onto something."
    thinking "I still need more evidence to confirm though."
    thinking "But how?"
    thinking "Hmm..."
    "Time passes by while I'm thinking it over."
    touko "I'm done! "
    "Touko's sudden announcement interrupts my thoughts."
    shinn "Oh, alright, let me take a look."
    "I stood up and approached her desk."
    "I take her paper and scan through it, looking over all her answers. At a glance, I can tell hardly any of them are right."
    shinn "Well, this isn't good, Touko. It seems like you missed most of them."
    "Touko cast her eyes down in shame, unable to meet my gaze."
    shinn "This is a pretty rough start. It looks like you're going to have a whole lot of work to do to catch up in this class."
    touko "Well... I tried my best."
    shinn "But it's not getting you there. You're going to need to build more effective study habits. Didn't you say you and Aina study together?"
    touko "Erm... Yeah."
    shinn "Then how have you ended up this far behind?"
    touko "Hehe..."
    "Unable to give me a straight answer, Touko gives a nervous, self-deprecating laugh."
    shinn "It's getting late now. I'm going to give you some practice papers, try to get them done tonight and hand them back to me tomorrow, got it?"
    "Touko sulked. She clearly wasn't happy with the idea of getting extra homework from me."
    shinn "..."
    shinn "Don't give me that face. I want it in by tomorrow."
    "Reluctantly, she took the papers and packed her bags. Seems like she's pretty eager to get out of here."
    touko "Alright. Thank you for today. I'll be going then."
    shinn "Goodbye."
    "Touko slid the door open and left the classroom."
    shinn "..."
    thinking "I need to find out more about her. Starting tomorrow, I'll try tailing her to see what I can dig up."
    thinking "Considering the situation with her family, any kind of dirt I can get on her should make for good leverage."
    thinking "Tomorrow is going to be a long day..."

    scene bg main gate with fade
    "Classes started 30 minutes ago..."
    "But I decided to come in a bit later, since there's no work for me now anyway. Not until afternoon, at least."
    thinking "Heheh...  I'll put that time to good use tailing Touko."
    thinking "Can't wait to see what kind of dirt I'll be able to dig up on her."

    scene bg hallway 2 with dissolve
    "I enter the hallway and go up to the floor where all the 3rd year students are."
    "I know her classroom is 3-5, not far from the classroom that I use for tutoring."
    "As I approached the class, I could see Touko heading towards it from the other direction as she returned from the bathroom."

    show touko happy school with moveinleft
    "We spotted each other at the same time."
    touko "Good morning, Shinn."
    shinn "Good morning to you too, Touko."
    "Touko seemed rather surprised to run into me here."
    touko "Erm, so, what brings you here?"
    "Well, I came here to stalk her, but obviously I can't just tell her that to her face."
    "Well, better bullshit something."
    shinn "Ah... I wanted to talk to you about something."
    shinn "Do you think you can spare a bit of time now?"
    "Touko looks a bit reluctant as she thinks it over, but eventually she nods."
    touko "Err... I'm having a class right now, but a few minutes should be fine."
    menu:
        thinking "Okay, shit, what can I ask her to eat up time?"
        "Ask her what she thinks about Rina.":
            $ renpy.block_rollback()
            jump ask_about_rina
        "Ask her what she thinks about Ritsuko.":
            $ renpy.block_rollback()
            jump ask_about_ritsuko

label ask_about_rina:
    "Struggling to come up with something, I spit out the first thing that comes to mind."
    shinn "So, what do you think about Rina?"
    touko "Rina? You mean the disciplinary teacher?"
    shinn "Yes."
    touko "Hmm? Why are you asking me?"
    "An explanation suddenly comes to Touko."
    touko "Oh. Don't tell me she's you type?"
    shinn "What? Hell no! "
    touko "Then why are you asking?"
    shinn "I am asking because I'm her colleague and it's hard to work with someone you don't understand."
    touko "Hmm... I guess that makes sense."
    shinn "So?"
    touko "Well, Rina is a very strict person. Actually, I guess she's the strictest person I know in this school."
    touko "I think she's kind of unpopular with the boys here, since she tends to go a bit easier on the girls."
    shinn "Is that so?"
    touko "Yeah. When I make a mistake, she tells me firmly, but she's still nice about it. When it's with the boys though, she can be kind of aggressive."
    shinn "Yikes."
    touko "Whatever it is, I think she might see you more like a student and not a staff member because of your age."
    shinn "Hmm... Alright."
    touko "Is there anything else you wanted to ask? Otherwise, I should get going."
    shinn "Ah, no, I think that's all."
    touko "Alright, I'll be going then. See you later for tutoring!"
    shinn "See you."

    hide touko happy school with moveoutright
    "As Touko left, I felt a sense of relief."
    "The info on Rina is probably irrelevant anyway. I'm just glad to have that over with."
    "Now, back to stalking. I want to see what she does during lunch."
    jump touko_aina_day1_continued_2

label ask_about_ritsuko:
    "Struggling to come up with something, I spit out the first thing that comes to mind."
    shinn "So, what do you think about Ritsuko?"
    touko "Ritsuko? You mean the one who's a star tennis player?"
    shinn "Yeah, that one."
    touko "Hmm... She comes from a rich family, and she's kind of well known for her whole ladylike act."
    touko "When it comes down to it though, she seems kind of useless for anything she can't get done by throwing her family's money around."
    shinn "Wow."
    touko "Yeah, I really don't have a good impression of her, sorry."
    touko "Anyway, why are you asking about this?"
    thinking "Shit, gotta come up with something..."
    "I toss out the first thing that comes to mind."
    shinn "Well, it's because Ritsuko is one of the girls I've been hired to assist."
    touko "Heh. She needs help with math?"
    touko "I figured they'd probably just chuck private tutors at her for whatever she had trouble with."
    shinn "Err..."
    touko "Sorry, my bad, I guess I shouldn't be talking like this behind her back."
    shinn "It's alright. At least I've learned something in the process."
    thinking "Not that the info on Ritsuko really matters."
    "Is there anything else you wanted to ask? Otherwise, I should get going."
    shinn "Ah, no, I think that's all."
    touko "Alright, I'll be going then. See you later for tutoring!"
    shinn "See you."

    hide touko happy school with moveoutright
    "As Touko left, I felt a sense of Relief."
    "The info on Ritsuko is probably irrelevant anyway. I'm just glad to have that over with."
    "Now, back to stalking. I want to see what she does during lunch."
    jump touko_aina_day1_continued_2

label touko_aina_day1_continued_2:
    scene bg hallway 1 with irisin
    "The bell for lunch rang."
    "I had already eaten lunch beforehand, so I decided to take the chance to follow Touko around and see what she gets up to."
    "While the other students were leaving class and heading for the cafeteria, I spotted Touko heading in the other direction."
    thinking "Hmm? Where's she going?"
    "I slowly follow along behind her, keeping out of her sight and avoiding the attention of of any of the other students nearby."
    "Touko walked further and further. The crowds of students started to thin, until almost nobody was left."
    thinking "Where is she going? I know this area. There are no classes in this part of the school, and students hardly ever come here."
    "As she walks towards the end of a dead-end hallway, she turns towards a utility closet off to the side."
    "She looks anxious, but doesn't bother to check her surroundings as she opens the door."
    "Confident that nobody is watching her, she enters the room."
    thinking "Hmm? Something strange is going on..."
    "I cautiously approach the door."
    "The door is cheaply made, and there's a wide keyhole under the knob."
    "I peer through the keyhole, hoping to get a view of whatever Touko is up to inside."
    jump touko_aina_sex_scene_1
            
label ask_about_day:
    shinn "So how is your day going?"
    touko "Erm... Great, I guess?"
    "She seems reluctant to continue this line of conversation, and her tone tells me she clearly doesn't want to be here."
    shinn "Good. I hope you've completed the homework I gave you yesterday?"
    touko "Of course! "
    play sound school_bell
    "However, before I could continue the conversation, the school bell signaling the end of lunch rang."
    touko "I'm sorry Shinn, but lunch is over. I have to get back to my classroom now."
    shinn "Okay. We'll talk later."
    hide touko happy school with moveoutleft
    "She turns around and hurries off."
    shinn "Damn it, she ran away before I could change the subject. Now what?"
    jump touko_aina_day1_continued_3

label ask_about_utility_room:
    shinn "Hey Touko. Just now I saw you coming out from the utility room. What were you doing in there?"
    "Touko's expression becomes even more nervous..."
    touko "Eh? Er..."
    play sound school_bell
    "Before Touko could even reply, the school bell rang signaling the end of lunch."
    touko "Oh, I'm sorry Shinn. Lunchtime's just ended, so I've got to get back to class."
    hide touko happy school with moveoutleft
    "Before I could give a reply, she turned around and hurried off."
    shinn "Damn it, and I was thinking I could expose her right now. Now what?"
    jump touko_aina_day1_continued_3

label touko_aina_day1_continued_3:
    "I turn around to look at the door of the utility room."
    shinn "Hmm... Maybe I should take a look?"
# *CG TRANSITION*

# Title: Touko Arc – Day 2 – Afternoon – 12:10 PM
# Location: Haruka Academy, Utility Room.
# Background CG: a small-sized room with two visible metallic shelves with several items of all types (most notably, sports and theater-related materials), a folded aluminum chair, and a small table as well.

    shinn "..."
    "The room is filled with a feminine smell."
    shinn "Huh, seems like they used a whole bunch of perfume to cover up the smell."
    "Looking at the place, I can't see any sign of their activities from before."
    shinn "These girls are pretty good at cleaning up. Not a trace of evidence after they're done."
    "Just to be sure, I took some time to look around room for more thorough search."
    shinn "Hmm... Nothing but cleaning stuff and stored equipment."
    "Just as I was about to give up searching..."
    shinn "Hmm? What's this?"
    "There seems to be something pink hidden behind a corner of shelving."
    "A bit of sunlight is shining on it from the window, but it's hard to spot at first due to its position."
    "I pick it up for a closer look."
    shinn "Hmm? Why does it feel wet?"
    "The object I grabbed was something I never expected."
    shinn "Wha- pink panties?"
    shinn "Huh?"
    "Why would this even be left behind here?"
    shinn "Wait. Could this be..."
    "The pink panties were tainted and soiled."
    "I brought it to my nose and took a whiff."
    shinn "Wow..."
    "Breathing it in almost feels like snorting drugs."
    shinn "There's no doubt that this is a high school girl's scent. And it's quite fresh."
    shinn "So, are these pink panties one of theirs?"
    shinn "Hmm... From the looks of it, it seems like one of them left her panties here in the sunlight to let them dry."
    shinn "Well... There's only one way to find out."
    "I take the panties with me and keep them in my pocket."
    shinn "Let's see who comes back to get these. If I'm on track here, they should be back for them as soon as classes are over."

# *CG TRANSITION*

# Title: Touko Arc – Day 2 – Afternoon– 3:00 PM
# Location: Hallway
# Background CG: Hallway

    "Classes have ended."
    "I've been waiting in this spot for over two hours now. I feel like an idiot."
    thinking "This was such a stupid idea."
    thinking "There's no guarantee that the person who left them behind will come back for them today."
    thinking "Besides, I need to be there for the tutoring sessions in just a bit."
    thinking "Maybe I should just give up and go."
    "Just as I was about to leave, I heard footsteps heading my way."
    # SFX: *School Shoes Footsteps*
    thinking "Oh shit! Someone's coming!"
    "I run back to my hiding spot to take a look at who it is."
    "A figure becomes visible."
    thinking "My my, what do we have here?"
    "Seems the owner of the panties was Touko after all."
    thinking "From the look of it, she seems pretty uncomfortable."
    thinking "Has she been attending afternoon classes without her panties? Wow, what a naughty girl."
    "She takes a quick look around before entering the utility room."
    thinking "There! She must have gone back to get her panties."
    thinking "Heheh. Wonder how she'll react when she sees they're nowhere to be found? "
    "A few minutes later, she comes back out of the room looking extremely anxious.   "
    "She walks away slowly."
    shinn "Checkmate."

# *CG TRANSITION*
# Title: Touko Arc – Day 2 – Morning – 3:30PM
# Location: Haruka Academy, Hallway
# Background CG: Hallway...

    "I feel a sense of victory welling up in me as I head towards the classroom."
    thinking "I've got the dirt on her. Now it's time for the payoff..."

# *CG TRANSITION*

# Title: Touko Arc – Day 2 – Afternoon– 3:35 PM
# Location: Haruka Academy, Class 3-2
# Background CG: A typical classroom with a blackboard. Chairs and desks stand in single-file rows.

    "As I slide open the door, I'm surprised as the sight of Touko waiting for me in the classroom."
    "Instead of her usual school uniform, she was dressed in her basketball team outfit."
    thinking "Heh... Afraid of being exposed?"
    touko "Good afternoon Shinn."
    shinn "Good afternoon Touko. I'm surprised to see you here in your basketball outfit."
    "Touko turns away, looking embarrassed."
    touko "Erm... Well, I splashed a bunch of water over my shirt while I was in the bathroom."
    thinking "Pfft... Is that the best lie you can come up with?"
    shinn "Is that so? Well, try to be more careful next time."
    touko "Yes, I will."
    "Touko takes the practice assignment I gave her yesterday out of her bag."
    touko "Here you go. I've completed it as promised."
    shinn "That's great. Give me a second to get my things ready and I'll give it a look over."

    menu:
        thinking "Hmm... Let's see. How should I do this?"
        "Expose her Immediately":
            shinn "Oh, before we get started, there's something I should probably show you."
            "I take out the pink panties from my pocket and flash them in front of her."
            "Touko gaped. The sudden turn in the conversation left her dumbfounded."
            touko "That's... my..."
            shinn "That's right, these are your panties."
            "Touko's distress is written all over her body. I can see her trembling, she might scream for help at any moment."
            touko "You... Per—"
            shinn "Now, hold on a second. Before you shout, you might want to know how I got ahold of this."
            "Touko freezes. She stares back at me with a look of pure venom."
            shinn "I've been keeping an eye on you since this morning, Touko. Observing your every action and movement."
            touko "You..."
            shinn "That's right. That includes the incident in the utility room."
            touko "No... That can't be..."
            thinking "Heh. She gets it now."
            "Sensing that I have Touko trapped like a cornered animal now, I give her a sinister smile."
            shinn "Now Touko. I think it would cause some rather serious problems for you if news of this incident became public, isn't that right?"
            jump touko__sex_scene_1
        "Wait a little longer":
            shinn "Alright. Let me see how you did."
            "I take the papers from her and scan through her answers."
            shinn "Hmm... Seems like you've missed quite a few of these, I'm afraid."
            touko "Oh..."
            shinn "Don't worry Touko. Practice makes perfect, just like in basketball."
            shinn "Let's go over your mistakes for this session, and then we'll move on to a new topic."
            touko "Okay."
            "We go through the usual routine, writing down questions and formulas on the blackboard and walking her thrugh them."
            "It wasn't long before we reached the end of the lesson."
            shinn "Alright, let's call that a day. I think you did great."
            touko "Thank you!"
            "She packs her bag and gets ready to head homleave classe."
            "I approach her with some practice papers in hand."
            shinn "Don't forget these ,Touko. I want to see your grasp of the new material."
            "Touko's cheery mood vanishes as she immediately falls into a sulk."
            touko "Ugh... Okay."
            shinn "Hey, don't be like that. Keep a positive attitude."
            touko "Alright."
            "She puts the papers in her bag and heads for the door. Just as she was about to open it, I call out to her."
            shinn "Oh, Touko, I think you forgot something."
            "I take the pink panties out from her pocket and flash them in front of her"
            shinn "Remember these?"
            "Touko gaped. The sudden turn in the conversation left her dumbfounded."
            touko "That's... my..."
            shinn "That's right, these are your panties."
            "Touko's distress is written all over her body. I can see her trembling, she might scream for help at any moment."
            touko "You... Per—"
            shinn "Now, hold on a second. Before you shout, you might want to know how I got ahold of this."
            "Touko freezes. She stares back at me with a look of pure venom."
            shinn "I've been keeping an eye on you since this morning, Touko. Observing your every action and movement."
            touko "You..."
            shinn "That's right. That includes the incident in the utility room."
            touko "No... That can't be..."
            thinking "Heh. She gets it now."
            "Sensing that I have Touko trapped like a cornered animal now, I give her a sinister smile."
            shinn "Now Touko. I think it would cause some rather serious problems for you if news of this incident became public, isn't that right?"
            shinn "I think your parents would be likely to have some pretty strong opinions on the matter, wouldn't they?"
            "Touko looks defeated. She casts her gaze downwards, refusing to make eye contact with me."
            touko "What... Do... You... Want?"
            shinn "Why don't you come back over and sit down for a bit?"
            "In silence, she slowly walks back to her desk and sits down."
            jump touko__sex_scene_1

label touko__sex_scene_1:
    "I walked up close, intimidating her with my presence."
    shinn "To be frank, Touko, when you told me about your friendship with Aina, this was not exactly the sort of relationship you described."
    touko "You leave her out of this! "
    "When I mention Aina, she immediately seems defensive. Seems like she wants to keep her out of this at all costs."
    shinn "Oh, how protective."
    shinn "You must really love her a lot, huh?"
    touko "..."
    shinn "Though I have to say, it takes a lot of guts to get involved in that sort of relationship, given your family circumstances."
    touko "Just leave Aina alone! She has nothing to do with this!"
    shinn "Don't worry. I won't do anything to her."
    thinking "At least for now."
    shinn "All you have to do is to listen to me and follow my instructions properly."
    touko "What do you want from me?"
    shinn "You know what I want from you."
    touko "What?"
    shinn "I heard all the action you had going on with Aina earlier. I was rock hard the whole time."
    shinn "So, I'm looking forward to having you relieve all that pressure you helped build up."
    "As Touko figures out my meaning, her face fills with revulsion."
    touko "No! There's no way in hell I'd do that sort of stuff with you!"
    shinn "What a stubborn girl. I don't think you're in any position to bargain here."
    shinn "Keep in mind what I have my hands on already."
    touko "..."
    shinn " That's right. Don't forget, carrying on relations like that at school is against the rules. As someone who's been put in charge of your education, I think it's my responsibility to teach you a lesson."
    touko "Fuck off, bastard."
    shinn "Right. Let's start off easy, shall we? Put your hands on the blackboard and lean forward with your hips out."
    touko "..."
    shinn "Come on. I don't have all day."
    "She stands up and walks over to the blackboard and does as I instructed, a look of disgust on her face."
    touko "Is that it?"
    shinn "Good."
    "I approach and stand directly behind her. I keep my eyes glued on her full and toned ass."
    shinn "Seems to me that you work your butt pretty hard for the basketball team."
    touko "Shut up!"
    shinn "Yeah, keep that up. I like to play with girls like that."
    touko "You—"
    "Before she can finish her sentence, I strip down her jersey shorts."
    touko "Kya. What— "
    "Since I already have her panties on me, her pussy and her asshole are completely exposed."
    shinn "Wow, not even wearing panties? You're a very naughty student, Touko."
    touko "Please, stop!"
    "I unzip my pants and place my erect dick right on her ass."
    shinn "I think you need to be disciplined."
    "I place my dick right up against her pussy, brushing up against her entrance."
    touko "No! Please don't! That thing is too big! It wouldn't fit!"
    shinn "Well, let's find out, shall we?"
    "I slowly thrust it in"
    touko "NOOOO!!"
    "As I thrust in, her inner walls wrap around me, clinging to my cock. She feels warm and wet inside."
    "Some of her juices leak out around me."
    shinn "No? Your pussy says otherwise."
    touko "No! Stop! Please!"
    shinn "Stop lying to yourself. You're a pervert just like me. You can't hold yourself back from doing naughty stuff even when you're at school."
    touko "That's not true!"
    "I begin to move."
    touko "No! Stop! "
    "I refuse to take heed of her pleas and push on. Her tightens every time I pound her."
    thinking "At this rate..."
    "Touko was sobbing. Just like that, she was being helplessly violated by me. It seems as if she's already been emotionally broken."
    "Now all I need to do break her mind as well, and she'll be all mine."
    touko "Ahh! Please stop!"
    "Her screams get even louder. At this rate, someone is bound to head her."
    "I take her pink panties and shove them into her mouth in order to muffle her."
    shinn "Shut up, bitch!"
    touko "Hmmpp..."
    "She's trying to shout for help, but with her voice muffled by her panties, nobody is going to hear her."
    "I continue to savor her pussy with my dick."
    "The sensation is breathtaking. I've never sampled an athletic girl's pussy before. It feels so different, so lively."
    "It doesn't take long before I start to feel the burning need to come welling up in me."
    "I want to savor more of her pussy, but I can't put off the inevitability."
    shinn "I'm gonna cum!"
    touko "HMM, PFF!!"
    "Her muffled noises get even more intense, pleading with me not to do it."
    shinn "Take it Touko!"
    shinn "Take all of my cum!"
    touko "UHMM!!!! "

    if persistent.cum == "inside":
        "Her pleas for me to stop make me even hornier. With a sudden rush of adrenaline, I pound her even harder."
        $ renpy.block_rollback()
        jump touko__sex_scene_1_inside

    elif persistent.cum == "outside":
        "Her pleas for me to stop make me even hornier. With a sudden rush of adrenaline, I pound her even harder."
        $ renpy.block_rollback()
        jump touko__sex_scene_1_outside

    else:
        menu:
            "Her pleas for me to stop make me even hornier. With a sudden rush of adrenaline, I pound her even harder."
            "Cum inside":
                $ renpy.block_rollback()
                jump touko__sex_scene_1_inside
            "Cum outside":
                $ renpy.block_rollback()
                jump touko__sex_scene_1_outside

label touko__sex_scene_1_inside:
    "Unable to resist any longer, I cum explosively inside her. It's so good, I cum enough that it gushes out from her pussy around me."
    shinn "Ahh!~"
    "Her legs shake and her pink panties fall as her mouth gapes open."
    "Her tongue sticks out and her eyes roll back in excitement."
    touko "AHH!"
    "She falls to the ground, unable to support her weight."
    jump touko__sex_scene_1_end

label touko__sex_scene_1_outside:
    "Unable to resist any longer, I take my dick out and spray it all over her back."
    shinn "Ahh!~"
    "Her legs shake and her pink panties fall as her mouth gapes open."
    "Her tongue sticks out and her eyes roll back in excitement."
    touko "AHH!"
    "She falls to the ground, unable to support her weight."
    "My cum was splattered everywhere, on the floor, across her back, covering her jersey."
    "Some of it is even clinging to her hair. I'm surprised it was able to shoot out over such a distance."
    jump touko__sex_scene_1_end

label touko__sex_scene_1_end:
    shinn "Heh. Look at you! What a shame that the beloved star athlete has degenerated into such a slut."
    touko "Ahh..."
    "She doesn't respond to my words. She's lost her sense of awareness."
    "I lean on Touko and whisper right into her ears."
    shinn "Listen, Touko. This isn't over yet. If you tell anyone what happened today, I'll make sure that Aina is next. You hear me?"
    touko "Ahh..."
    shinn "..."
    shinn "Now clean yourself up, bitch. And remember what I said."
    "I take one last look at her as I leave the class. Leaving her to her own demise."
    shinn "I'll look forward to even more fun tomorrow..."
    $ renpy.end_replay()
    $ persistent.touko__sex_scene_1 = True
    $ pool_gym_available = False
    jump map__school