label ask_about_aina:
    "When I first met Touko, she was together with Aina. And from the way they talked, it seems like they’re very close."
    "Maybe Touko has some useful information I could use against Aina? I should ask what she has to say about her."
    shinn "Since it’s just us here right now, there’s something I’d like to ask you."
    touko "Hm? What is it?"
    shinn "When I first met the two of you, it seemed like you and Aina were very close. What’s your relationship with her?"
    touko "Hmm? Why’re you asking?"
    shinn "Since I’m going to be tutoring her too, I thought’d be good to get your impression on what kind of person she is."
    shinn "I’m just trying to be better prepared."
    touko "Ah, I see. Aina, huh?"
    touko "She’s a good friend of mine. We used to attend the same middle school together before we came here."
    shinn "The same school?"
    touko "Yeah. We’ve known each other since a while back."
    touko "Actually, she was the first friend I made back in middle school, and the two of us have been close ever since."
    shinn "I see. What do you think of Aina as a person?"
    "Touko paused for a moment, processing her thoughts."
    touko "Hmm... I guess she’s a nice person. She’s also always been really energetic."
    thinking "Heh. \"Energetic\"."
    touko "She’s also really determined and competitive."
    shinn "I see."
    shinn "Is there a reason why she’s also been struggling in math then?"
    touko "Hmm... I guess she’s basically like me? We both focus on our sports a lot, so the other stuff gets sidelined."
    touko "Also, she doesn’t like math either. So that too."
    shinn "I see."
    touko "Usually, I spend time together with her, and we do some studying together and try to help each other out."
    shinn "Spend time together?"
    touko "Yeah. Like, every weekend, we’ll spend time at her house or mine to study math."
    shinn "I see..."
    touko "Usually, when exams are coming up, one of us will stay over at the other’s house and we’ll stay up studying."
    touko "Like I said before, we’re pretty close."
    shinn "Hmm..."
    jump touko_aina_day1_continued

label ask_about_academics:
    shinn "Since it’s just us here right now, there’s something I’d like to ask you."
    touko "Hmm? What is it?"
    shinn "Is there some reason why you’ve been struggling so much in math class?"
    touko "Well, I guess I’m mainly just doing bad because I kind of hate math."
    touko "But since I’m spending so much of my time focusing on other stuff I actually enjoy, I don’t have a lot of attention left over for it."
    shinn "Ah. I see. Well, that’s a pretty common problem."
    touko "Right. So, I was hoping you could help me out with that."
    thinking "Heh. Of course I’m going to \"help.\" "
    shinn "I see..."
    shinn "So, how do you usually study on your own when you’re trying to catch up in math?"
    touko "Usually, I spend time together with Aina, and we do some studying together and try to help each other out."
    shinn "Spend time together?"
    touko "Yeah. Like, every weekend, we’ll spend time at her house or mine to study math."
    shinn "I see..."
    touko "Usually, when exams are coming up, one of us will stay over at the other’s house and we’ll stay up studying."
    touko "Oh, I guess I didn’t tell you this before, but me and Aina are really close friends."
    shinn "Hmm..."
    jump touko_aina_day1_continued

label touko_aina_day1_continued:
    thinking "Hmm... I think I see how it is."
    thinking "Since these two are such close friends, it should be easier to get the two of them together."
    touko "Erm... Shinn?"
    thinking "Maybe I could swing a threesome... Hehehe..."
    touko "Hello? Are you there?"
    "Realizing I’d gotten lost daydreaming, I quickly pulled myself back."
    shinn "Yeah. Sorry, I was thinking about something."
    "Touko looks at me with concern."
    touko "Are you okay?"
    shinn "Oh, I’m fine."
    shinn "I think that’s it for now. Thanks for letting me know. I’ll see you later."
    touko "Sure!"
    "I left her alone to her training. As I walked out of the court, my thoughts were focused on the two them."
    thinking "Hmm... this doesn’t add up, does it?"
    thinking "The two of them don’t seem so dumb that they’d be failing math if they get together every week to study."
    thinking "Especially if they go to the point of studying overnight together every time exams are coming up..."
    thinking "What are they really doing together?"
    thinking "Wait a minute..."
    "Some wild thoughts suddenly spring to mind"
    thinking "Could they be...? "
    "I can’t help but give a sinister smile."
    thinking "Haha... If I’m right, this’ll be pretty epic."
    thinking "But first, I’ll need to investigate, see if I can dig up some proof."
    thinking "Hmm, how am I going to do this?"

    scene bg hallway 1 with irisin
    thinking "Shit!"
    thinking "Its 3.30 PM already. Today’s lesson with Touko is supposed to be now. I wonder if she’s already there."
    thinking "I should have kept better track of time and been there to wait for her."
    thinking "Let’s hope she’s not there yet."

    scene bg classroom with dissolve
    show touko basic
    "I approach the classroom and slide open the door."
    "I was hoping to avoid this, but Touko was already there waiting for me."
    "She turns around and gives me an annoyed look."
    touko "You’re late.  "
    shinn "Ah yes. My apologies. I wasn’t looking at the time."
    touko "It’s okay. Since you’re here now, let’s get this started so we can get it over with quickly."
    thinking "Heh. You sure seem to be in a hurry."
    shinn "Well, that that’ll depend on how well you understand the content we’ll be covering today."
    "I take out my materials and jot down some notes on the blackboard."
    "The lesson was in session. As I walk her through the material, and explain the various methods to solve the problems in her assignments, Touko seems to be attentive."
    "Or at least, she’s trying to be. Now and then, a bemused expression crosses her face."
    shinn "Err... Touko? Do you understand my explanation here? "
    touko "Y.. Yes."
    thinking "Obviously not."
    shinn "You sure? "
    touko "Yes."
    "At this point, the scheduled lesson time is over. So, I decided to give her a little test."
    shinn "Alright, Touko. Since you’ve gotten the explanation down, you should be able to handle this problem sheet, right?"
    touko "Er... Yes?"
    thinking "Not exactly making that sound convincing."
    "Regardless, I pass her the paper."
    shinn "Here you go then. If you don’t understand any of the questions, let me know. I’ll do my best to help you out with anything you’re having trouble with."
    touko "Okay."
    "She sat down with the paper, and started working her way through the questions."
    "While I watched, she seemed to be pretty intently focused on her work."
    thinking "Maybe I should take the opportunity to ask her some more questions and get to know her better."
    shinn "So Touko..."
    touko "Huh?"
    "She replies, half giving me her attention while trying to focus on the sheet."
    shinn "Tell me more about yourself."
    "She pauses, trying to think of something to say."
    touko "Hmm... What do you want to know?"
    shinn "I don’t know. Stuff about your life, I guess? "
    touko "My life, huh? Why do you want to know all this?"
    shinn "To get to know you better. I’m probably going to be having these sessions with you for quite a while, after all."
    touko "Hmm, let’s see..."
    "She mulls it over for a bit."
    touko "Well, I come from a very strict family."
    shinn "Strict family? What do you mean?"
    touko "Well, my parents are very conservative, and they’ve always had a lot of rules for me to follow."
    shinn "What? Like how? "
    touko " All sorts of stuff. To begin with, they put up a lot of fuss about me joining the basketball team."
    touko "It took a whole lot of convincing to get them to let me stay on it. And if I break any of their rules, they’ll want me off the team right away."
    shinn "What do they want from you then?"
    touko "Well, they want me to be more ladylike..."
    touko "They think that playing basketball will give me a bad attitude and make me too much of a tomboy."
    shinn "Hmm... Interesting..."
    touko "Eh? What’s so interesting about that?"
    shinn "I mean, it’s pretty uncommon these days for parents to be that restrictive with their kids."
    touko "Yeah, and it gets worse from there."
    shinn "Oh? How so?"
    touko "One of the rules they’ve set for me is, they don’t want me getting into any kind of a relationship."
    shinn "Wow."
    touko "Yeah. If I did, they’d really crack down on me, way more than just making me quit the basketball team."
    touko "Like, they might seriously disown me."
    touko "So, I really can’t afford to let anything like that happen."
    touko "They say I’ll be ready for a relationship when I have their say-so, and it has to be with a partner who has their approval."
    shinn "Really? You mean like an arranged marriage or something?"
    touko "Yeah, I guess you could put it that way."
    shinn "Yikes. That’s harsh."
    shinn "But hey, you’re pretty popular with the girls, aren’t you?"
    touko "Huh? What you mean?"
    shinn "I’ve heard that some of the star female athletes here get a lot of attention from other girls in this school, including yourself."
    touko "Yeah, I guess..."
    touko "Honestly, I’ve gotten a fair number of love letters from other girls before, definitely more than I have from boys. I guess maybe my parents had a point when they worried about me being tomboyish?"
    "Touko stares off into space, apparently lost in thought."
    shinn "Hello? Touko? "
    touko "Oh! Sorry, I guess I kind of went on for a while."
    touko "I’ll keep going with the worksheet."
    shinn "Alright."
    thinking "Hmm... Let me think."
    thinking "She did say she’s received more love letters from girls than boys, but that doesn’t mean that she’s into that herself."
    thinking "But from her reaction just now, I have a feeling I’m onto something."
    thinking "I still need more evidence to confirm though."
    thinking "But how?"
    thinking "Hmm..."
    "Time passes by while I’m thinking it over."
    touko "I’m done! "
    "Touko’s sudden announcement interrupts my thoughts."
    shinn "Oh, alright, let me take a look."
    "I stood up and approached her desk."
    "I take her paper and scan through it, looking over all her answers. At a glance, I can tell hardly any of them are right."
    shinn "Well, this isn’t good, Touko. It seems like you missed most of them."
    "Touko cast her eyes down in shame, unable to meet my gaze."
    shinn "This is a pretty rough start. It looks like you’re going to have a whole lot of work to do to catch up in this class."
    touko "Well... I tried my best."
    shinn "But it’s not getting you there. You’re going to need to build more effective study habits. Didn’t you say you and Aina study together?"
    touko "Erm... Yeah."
    shinn "Then how have you ended up this far behind?"
    touko "Hehe..."
    "Unable to give me a straight answer, Touko gives a nervous, self-deprecating laugh."
    shinn "It’s getting late now. I’m going to give you some practice papers, try to get them done tonight and hand them back to me tomorrow, got it?"
    "Touko sulked. She clearly wasn’t happy with the idea of getting extra homework from me."
    shinn "..."
    shinn "Don’t give me that face. I want it in by tomorrow."
    "Reluctantly, she took the papers and packed her bags. Seems like she’s pretty eager to get out of here."
    touko "Alright. Thank you for today. I’ll be going then."
    shinn "Goodbye."
    "Touko slid the door open and left the classroom."
    shinn "..."
    thinking "I need to find out more about her. Starting tomorrow, I'll try tailing her to see what I can dig up."
    thinking "Considering the situation with her family, any kind of dirt I can get on her should make for good leverage."
    thinking "Tomorrow is going to be a long day..."

    scene bg main gate with fade
    "Classes started 30 minutes ago..."
    "But I decided to come in a bit later, since there’s no work for me now anyway. Not until afternoon, at least."
    thinking "Heheh...  I’ll put that time to good use tailing Touko."
    thinking "Can’t wait to see what kind of dirt I’ll be able to dig up on her."

    scene bg hallway 2 with dissolve
    "I enter the hallway and go up to the floor where all the 3rd year students are."
    "I know her classroom is 3-5, not far from the classroom that I use for tutoring."
    "As I approached the class, I could see Touko heading towards it from the other direction as she returned from the bathroom."

    show touko basic with moveinleft
    "We spotted each other at the same time."
    touko "Good morning, Shinn."
    shinn "Good morning to you too, Touko."
    "Touko seemed rather surprised to run into me here."
    touko "Erm, so, what brings you here?"
    "Well, I came here to stalk her, but obviously I can’t just tell her that to her face."
    "Well, better bullshit something."
    shinn "Ah... I wanted to talk to you about something."
    shinn "Do you think you can spare a bit of time now?"
    "Touko looks a bit reluctant as she thinks it over, but eventually she nods."
    touko "Err... I’m having a class right now, but a few minutes should be fine."
    menu:
        thinking "Okay, shit, what can I ask her to eat up time?"
        "Ask her what she thinks about Rina.":
            $ renpy.block_rollback()
            jump ask_about_rina
        "Ask her what she thinks about Ritsuko.":
            $ renpy.block_rollback()
            jump ask_about_ritsuko

label ask_about_rina:
    "Struggling to come up with something, I spit out the first thing that comes to mind."
    shinn "So, what do you think about Rina?"
    touko "Rina? You mean the disciplinary teacher?"
    shinn "Yes."
    touko "Hmm? Why are you asking me?"
    "An explanation suddenly comes to Touko."
    touko "Oh. Don’t tell me she’s you type?"
    shinn "What? Hell no! "
    touko "Then why are you asking?"
    shinn "I am asking because I’m her colleague and it’s hard to work with someone you don’t understand."
    touko "Hmm... I guess that makes sense."
    shinn "So?"
    touko "Well, Rina is a very strict person. Actually, I guess she’s the strictest person I know in this school."
    touko "I think she’s kind of unpopular with the boys here, since she tends to go a bit easier on the girls."
    shinn "Is that so?"
    touko "Yeah. When I make a mistake, she tells me firmly, but she’s still nice about it. When it’s with the boys though, she can be kind of aggressive."
    shinn "Yikes."
    touko "Whatever it is, I think she might see you more like a student and not a staff member because of your age."
    shinn "Hmm... Alright."
    touko "Is there anything else you wanted to ask? Otherwise, I should get going."
    shinn "Ah, no, I think that’s all."
    touko "Alright, I’ll be going then. See you later for tutoring!"
    shinn "See you."

    hide touko basic with moveoutright
    "As Touko left, I felt a sense of relief."
    "The info on Rina is probably irrelevant anyway. I’m just glad to have that over with."
    "Now, back to stalking. I want to see what she does during lunch."
    jump touko_aina_day1_continued_2

label ask_about_ritsuko:
    "Struggling to come up with something, I spit out the first thing that comes to mind."
    shinn "So, what do you think about Ritsuko?"
    touko "Ritsuko? You mean the one who’s a star tennis player?"
    shinn "Yeah, that one."
    touko "Hmm... She comes from a rich family, and she’s kind of well known for her whole ladylike act."
    touko "When it comes down to it though, she seems kind of useless for anything she can’t get done by throwing her family’s money around."
    shinn "Wow."
    touko "Yeah, I really don’t have a good impression of her, sorry."
    touko "Anyway, why are you asking about this?"
    thinking "Shit, gotta come up with something..."
    "I toss out the first thing that comes to mind."
    shinn "Well, it’s because Ritsuko is one of the girls I’ve been hired to assist."
    touko "Heh. She needs help with math?"
    touko "I figured they’d probably just chuck private tutors at her for whatever she had trouble with."
    shinn "Err..."
    touko "Sorry, my bad, I guess I shouldn’t be talking like this behind her back."
    shinn "It’s alright. At least I’ve learned something in the process."
    thinking "Not that the info on Ritsuko really matters."
    "Is there anything else you wanted to ask? Otherwise, I should get going."
    shinn "Ah, no, I think that’s all."
    touko "Alright, I’ll be going then. See you later for tutoring!"
    shinn "See you."

    hide touko basic with moveoutright
    "As Touko left, I felt a sense of Relief."
    "The info on Ritsuko is probably irrelevant anyway. I’m just glad to have that over with."
    "Now, back to stalking. I want to see what she does during lunch."
    jump touko_aina_day1_continued_2

label touko_aina_day1_continued_2:
    scene bg hallway 1 with irisin
    "The bell for lunch rang."
    "I had already eaten lunch beforehand, so I decided to take the chance to follow Touko around and see what she gets up to."
    "While the other students were leaving class and heading for the cafeteria, I spotted Touko heading in the other direction."
    thinking "Hmm? Where’s she going?"
    "I slowly follow along behind her, keeping out of her sight and avoiding the attention of of any of the other students nearby."
    "Touko walked further and further. The crowds of students started to thin, until almost nobody was left."
    thinking "Where is she going? I know this area. There are no classes in this part of the school, and students hardly ever come here."
    "As she walks towards the end of a dead-end hallway, she turns towards a utility closet off to the side."
    "She looks anxious, but doesn’t bother to check her surroundings as she opens the door."
    "Confident that nobody is watching her, she enters the room."
    thinking "Hmm? Something strange is going on..."
    "I cautiously approach the door."
    "The door is cheaply made, and there’s a wide keyhole under the knob."
    "I peer through the keyhole, hoping to get a view of whatever Touko is up to inside."
    jump touko_aina_sex_scene_1
            
label ask_about_day:
    shinn "So how is your day going?"
    touko "Erm... Great, I guess?"
    "She seems reluctant to continue this line of conversation, and her tone tells me she clearly doesn’t want to be here."
    shinn "Good. I hope you’ve completed the homework I gave you yesterday?"
    touko "Of course! "
    # SFX: *School Bell Rings*
    "However, before I could continue the conversation, the school bell signaling the end of lunch rang."
    touko "I’m sorry Shinn, but lunch is over. I have to get back to my classroom now."
    shinn "Okay. We’ll talk later."
    hide touko basic with moveoutleft
    "She turns around and hurries off."
    shinn "Damn it, she ran away before I could change the subject. Now what?"
    jump touko_aina_day1_continued_3

label ask_about_utility_room:
    shinn "Hey Touko. Just now I saw you coming out from the utility room. What were you doing in there?"
    "Touko’s expression becomes even more nervous..."
    touko "Eh? Er..."
    # SFX: *School Bell Rings*
    "Before Touko could even reply, the school bell rang signaling the end of lunch."
    touko "Oh, I’m sorry Shinn. Lunchtime’s just ended, so I’ve got to get back to class."
    hide touko basic with moveoutleft
    "Before I could give a reply, she turned around and hurried off."
    shinn "Damn it, and I was thinking I could expose her right now. Now what?"
    jump touko_aina_day1_continued_3

label touko_aina_day1_continued_3:
    scene black with fade
    "End of Touko and Aina's current arc reached."
    $ pool_gym_available = False
    jump map__school