label touko_aina__day2:
# *CG TRANSITION*

# Title: touko_aina Arc – Day 3 – Morning – 8.00AM
# Location: Haruka Academy, Staff Room
# Background CG: Same as before, only this time the timing as changed. 

    "I came very early to school today just to check and ensure that everything was alright."
    "And also, to make sure that Aina doesn't suspect anything yet."
    "After all, I wasn't sure if Aina cleaned up all the mess from yesterday."
    "But thankfully, it seems everything is in the clear."
    "After everything yesterday, hopefully she'll still come in to school today."
    "I take a look at the clock and realize that school is just about to start."
    thinking "Hmm... Maybe I should pop by her class before lessons, just to give her a little surprise."
# *CG TRANSITION*

# Title: touko_aina Arc – Day 3 – Morning – 8.15AM
# Location: Haruka Academy, Hallway.
# Background CG: Same as before, only this time the timing as changed. 

    "I stand in the hallway outside Touko's classroom, leaning by the window, waiting for Touko to arrive."
    "However, before long, I start to realize that this might not be the greatest idea."
    "Some of the students start to take notice of my presence here. Considering that I'm not wearing my old school uniform, and don't look old enough to fit in among the faculty, I can't help standing out."
    thinking "This was a bad idea..."
    "Just as I'm about to give up and leave, a familiar person appears on the far end of the hallway."
    thinking "There she is."
    "Touko seems normal. In fact, she's walking along talking with some friends who I suppose are admirers of hers."
    "As she gets closer, she notices me, and a look of disgust passes over her face. She passes by me without giving me another glance as she heads straight into her classroom."
    thinking "Heh. Ignore me all you want. Pretty soon I'll have you wrapped around my finger anyway."
    "Feeling reassured that things are still going smoothly, I head back to my workplace in the staff room."
    "As I'm on my way there, I hear someone behind me call out my name."
    unknown "Good morning, Shinn!"
    shinn "Huh?"
    aina "It's me, Aina!"
    thinking "Oh, perfect timing."
    shinn "Good morning, Aina."
    aina "How are you?"
    shinn "I'm fine."
    aina "That's great to hear!"
    shinn "Don't forget your tutoring session with me next week."
    aina "I won't."
    "Aina walks away without the slightest inkling that my trap is already closing in on her."
    thinking "This is going to be fun."
    "Just as I'm about to walk away, a familiar figure appears."
    shinn "Hmm? Satsuki. Is that you?"
    satsuki "Good morning Mr. Shinn."
    "Satuski greets me in a ladylike fashion. As elegant as always."
    shinn "Ah, you're heading to class, right?"
    satsuki "Yes. My class is right there, next to Touko's."
    shinn "I see..."
    thinking "Hmm... Maybe she knows something about Touko."
    shinn "Say Satsuki..."
    satsuki "Hmm?"
    shinn "Would it be possible for you to tell me more about Touko?"
    "Satsuki gives me an uncertain look in response. It seems like she's weighing whether it's appropriate to reply."
    satsuki "..."
    thinking "Shit. She may get the wrong idea."
    shinn "Well... I don't mean that way..."
    satsuki "Well, she's certainly attractive and popular, so I can see where you're coming from."
    shinn "No no no..."
    shinn "I just mean that I want to get to know and understand her better as an instructor."
    shinn "That way, I should be able to offer her better support in math."
    "Satsuki seems somewhat relieved."
    satsuki "Oh. I see."
    satsuki "Hmm..."
    satsuki "I don't really speak with Touko much, but from what I know..."
    satsuki "She and Aina seem very close to each other. Apart from their positions in different sports clubs, it seems like the two of them are almost always together."
    satsuki "If anything, they might be too close..."
    "Satsuki stares off into space. It seems like she has something pretty serious on her mind."
    shinn "Err... Satsuki? Hello?"
    satsuki "Oh, sorry. I'm afraid I might have been getting a bit carried away with my thoughts."
    satsuki "But anyway, that is all I know. If you want to know more about Touko, you would probably be best off asking Aina."
    thinking "Well, it's not like I hadn't thought about going to her already."
    shinn "Alright then. Thanks for your help, Satsuki."
    shinn "I hope that we'll also be able to start working together soon."
    satsuki "Sure. When I have the time available in my schedule, I'll look forward to receiving your guidance."
    satsuki "If there is nothing else, I should be going now."
    "Satsuki walks off in her usual ladylike manner."
    thinking "Hmm... Seems like Aina is the key to Touko."
    thinking "Haha... Or vice versa I should say."
    jump aina__sex_scene_1

# *CG TRANSITION*

# Title: touko_aina Arc – Day 3 – Afternoon– 3:35 PM
# Location: Haruka Academy, Swimming Pool
# Background CG: A typical classroom with a blackboard. Chairs and desks stand in single-file rows.
label aina__sex_scene_1:
    "After giving the matter careful consideration..."
    "I think the best course of action is to proceed with Aina and see where things go from there."
    "I mean, I have the upper hand. What could go wrong for me?"
    "I pay a visit to the swimming pool, but no one seems to be around."
    thinking "Hmm... Weren't they supposed to have a practice session today?"
    thinking "Where have they all gone?"
    "Just then, a familiar person emerges from the girls' changing room."
    aina "Oh, Shinn?"
    "Target acquired."
    "Aina walks up to greet me, wearing her swimsuit."
    thinking "I have to admit, wearing a skintight swimsuit really shows off her figure."
    thinking "Considering her looks, it's no wonder she's so popular with the boys and girls in this school."
    "The more I look, the more I can feel my arousal growing. I can feel a familiar pressure building by the second."
    thinking "Shit. This isn't the time for a boner, hide it!"
    "As she arrives, I do my best to conceal the unsubtle bulge."
    aina "What brings you here?"
    shinn "I was looking for you."
    aina "Oh, what's up?"
    shinn "Is no one here for practice aside from you?"
    aina "Yeah, today's an off day. But since I have nationals coming up, I thought it'd be good to get in some extra practice."
    shinn "I see..."
    aina "So, you said you were looking for me?"
    shinn "Yes. Since we're alone here now, this should be a perfect time for it."
    aina "Huh?"
    "Since I'm going to confront her anyway, I guess there's no point hiding."
    "After all, this erection is getting pretty hard to conceal."
    "I give her a smile as I adjust my angle, leaving my boner on full display."
    "Of course, it's big enough to grab Aina's attention immediately."
    aina "Shinn?"
    aina "What... What are you doing?"
    shinn "Heheh... You look so hot with your swimsuit on. Can I have sex with you?"
    aina "What the fuck? Are you crazy?"
    aina "I didn't expect something like this from you, Shinn."
    shinn "Expect what? You should have seen it coming."
    "I grab her hand while teasing her."
    shinn "Come on... Let's do it."
    "Looking repulsed, Aina shoves my hands away."
    aina "Get away from me you pervert! I'm going to call for help!"
    "She turns her back on me, about to run away."
    thinking "Shit."
    shinn "I'm not so sure about that, calling for help when Touko is in trouble."
    "The moment I mention Touko's name, Aina freezes."
    shinn "That's right."
    "I slowly walk up to her and whisper right into her ear."
    shinn "I know everything..."
    "I walked around and face her. Her expression has changed to one of anxious uncertainty."
    aina "What? What did you know about her!?"
    thinking "Hmm... I wonder what I should say here?"
    shinn "I saw the two of yu having a good time in the utility room yesterday."
    shinn "And after that, I went into the room to investigate."
    aina "Then what!?"
    shinn "Then I happened to see Touko's wet panties hanging out to dry."
    shinn "I took it and show it to Touko."
    shinn "Guess what I did with her?"
    "The sudden realization make Aina sick."
    aina "You bastard! How could you!"
    "I took out my phone and show her the picture of what I did to Touko."
    shinn "Here you go. Take a look at your love, drowning in my semen."
    aina "You..."
    aina "You're not going to get away with this!"
    shinn "Well, there are two ways that this can go. One is that I expose this on the internet and around the school, and your lover Touko's career and school life are over.  "
    shinn "The other is that you can have sex with me right now, and I'll keep this a secret."
    aina "You..."
    shinn "So? What's it going to be? Protecting your lover by tasting this dick of mine, or ending things with Touko with the click of a button?"
    aina "..."
    "The gravity of the situation is slowly starting to sink into Aina."
    "For her, there's simply no choice between the options I offered her."
    "If she's acting for Touko's sake, there's no question that she'd choose to let me fuck her."
    "She gives me a look filled with rage."
    aina "So, if I have sex with you, you won't tell anyone."
    shinn "Tch. Of course. Who do you think I am?"
    shinn "I may be hungry for sex, but I do keep my word."
    aina "Fine..."
    aina "So... How do you want to do it...?"
    shinn "Glad you asked. Now, all I need you to do is to lay down by the side of the swimming pool."
    "Without giving any reply, Aina does as I instructed."
    "I strip down, showing off my huge erection to Aina."
    "She blushes as she catches sight of it, and through the thin fabric of her swimsuit, I can see her nipples getting hard."
    shinn "So, you like my dick, huh?"
    aina "Shut up..."
    "The latex of the swimsuit, slick and wet from her shower, turns me on like crazy."
    "Just fucking her isn't going to be enough, it makes me want to toy with her first."
    "I bend down beside her, and place my dick near the armpit opening of her swimsuit."
    "Slowly, I insert my dick into the opening, sandwiching it between the latex and her skin."
    "The size of my erection is enough that my dick reaches all the way to her nipple."
    aina "Mm..."
    "Aina doesn't say anything, but from the look on her face, this isn't a bad feeling for her."
    "I begin to rub my dick along her breast underneath the swimsuit."
    "The slick wet elastic and the softness of her breast feels so good, it's almost as if I'm having sex with a real pussy."
    aina "..."
    "As I continue to rub, her expression begins to shift from anger to embarrassment."
    "Could it be that she's actually enjoying this?"
    "Her breasts are bouncing with my thrusts, and I can see her nipples protruding sharply under the latex."
    "Each time the tip of my dick brushes her nipple, the desire to ejaculate grows inside me."
    "I start to rub harder, feeling the sensation rising up."
    shinn "Agh! Aina, I'm cumming!"
    aina "..."
    shinn "I'm gonna cum inside your swimsuit!"
    aina "Mmm..."
    "As I reached the point where I couldn't hold it any longer, I ejaculate, spilling my semen across the top of her swimsuit and around the armpit opening."
    shinn "Ahh..."
    shinn "That felt so good..."
    aina "...."
    "Aina examines herself, looking shocked as she realizes how much of my semen has spilled inside her suit. It's even coming out through the neck opening"
    "But apart from that, she seems to be taking the situation in stride."
    aina "So, I guess you're planning to move on to the real thing from here, huh?"
    shinn "Oh, what a surprise."
    shinn "Seems like you know your stuff after all."
    shinn "Do you do research on the internet or something?"
    shinn "Maybe look up tips and moves you can try out on your girlfriend?"
    aina "Stop talking and let's get this over with."
    shinn "Hah. And to think people at this school see you as a cheerful, pure and caring girl."
    shinn "Seems that after all you're a real slut and just keep it hidden away."
    aina "I'm not a slut. I'm just curious and got carried away with Touko before."
    shinn "Yeah, I hear excuses like that all the time."
    shinn "But from the look of it, it seems like you're starting to get pretty attached to my dick yourself."
    aina "Just shut up and finish this."
    aina "Asshole."
    thinking "Seems like she has a hard time denying that she knows a thing or two about sex."
    thinking "Considering what I saw before, it seems like she's the pushy one in her relationship with Touko."
    thinking "I guess I shouldn't be surprised."
    thinking "But if she's that horny to begin with, this should be a walk in the park for me."
    shinn "Well, alright then."
    "I move around behind Aina, where I position myself to penetrate her."
    shinn "So, I assume you've got a dildo already which you've tried out on yourself and Aina before?"
    aina "You don't need to know anything like that."
    shinn "You two must have a lot of fun times together."
    shinn "It's a shame I haven't been there to see any of it for myself."
    aina "..."
    "I took a look at her pussy before I get started."
    shinn "Look at this. It's all wet."
    shinn "Getting excited by the incoming dick, huh?"
    aina "..."
    shinn "Now, it's time for you to see which is better. A plastic dick, or a real meat rod that shoots cum out into your slutty pussy!"
    "I plunge right in, and waste no time forcing myself all the way to her deepest parts."
    aina "Kya!"
    shinn "Oh? Too much for you to take?"
    shinn "I bet a dildo doesn't feel as good as my dick now, does it?"
    aina "Shu... Shut up."
    shinn "By the end of today, I am going to make sure you won't be satisfied by anything but my dick from now on!"
    aina "Like hell I will!"
    "Since she's feeling so defiant, I decide to go even deeper, and thrust myself all the way into her womb."
    aina "Ahh~"
    "Her face started to show the pleasure of feeling my dick going in and out of her womb."
    "I can also feel her pussy getting even wetter."
    "In fact, with how wet she is now, no matter what she might say, there's no question that she's enjoying this."
    "I grab her breast to ramp up her pleasure even more."
    "The feeling of her breasts as I grab at them through her swimsuit is simply out of this world."
    "The latex of the swimsuit is slippery under my hands."
    "Not only that, the sound it makes is pretty erotic as well."
    "As I watch, Aina seems to be getting more and more aroused."
    "It shouldn't be long now before she starts to give in."
    shinn "Now tell me. Which is better. My dick or your dildo?"
    aina "Your..."
    thinking "Oh, she was about to say it..."
    shinn "What? I didn't get that."
    "It's obvious that Aina is feeling pleasure along with the embarrassment."
    "The look of anger in her face is almost gone now."
    aina "Shinn's cock..."
    shinn "Heh... Good."
    shinn "You're gonna enjoy my dick from now on, you get me?"
    aina "Y... Yes..."
    shinn "Now as a reward, you'll get to enjoy the thick milk from my balls."
    aina "What? No!"
    aina "No, not today. Today isn't safe!"
    shinn "No? But your pussy keeps squeezing me the more I move."
    shinn "You aren't being very honest with yourself, aren't you?"

    if persistent.cum == "inside":
            aina "No, I am! Please!"
            $ renpy.block_rollback()
            jump aina__sex_scene_1_inside

    elif persistent.cum == "outside":
        aina "No, I am! Please!"
        $ renpy.block_rollback()
        jump aina__sex_scene_1_outside

    else:
        menu:
            aina "No, I am! Please!"
            "Cum inside":
                $ renpy.block_rollback()
                jump aina__sex_scene_1_inside
            "Cum outside":
                $ renpy.block_rollback()
                jump aina__sex_scene_1_outside

label aina__sex_scene_1_inside:
    shinn "Please, do you think I care?"
    aina "No..."
    shinn "Hahaha!"
    shinn "What happened to your know-it-all attitude?"
    shinn "Got scared just because I'm gonna cum inside you?"
    aina "Please..."
    "I ignore her plea and plow ahead."
    shinn "Here it comes! Accept my milk in your womb!"
    aina "No!"
    "I give Aina one last pound and my milk shoots out instantly right into her womb."
    shinn "Argh!"
    "It's so much that the milk gushes out from her pussy."
    aina "Ah~"
    "I pull my dick out to inspect the mess I've made of her."
    jump aina__sex_scene_1_end

label aina__sex_scene_1_outside:
    "Since she's begging me to cum outside, I decide to humor her."
    "After all, she's already done a lot for me today."
    "Letting her decide for once isn't so bad."
    shinn "Alright, if that's how you want it..."
    "I give Aina one last pound before pulling my dick out."
    shinn "Here it comes!"
    "In an instant, the cum shoots out all over her body, covering her swimsuit."
    aina "Ah~"
    "Some of it even gets on her face."
    aina "Mm~"
    jump aina__sex_scene_1_end

label aina__sex_scene_1_end:
    "She's exhausted from all the pleasure she's felt, and looks too tired to respond to anything."
    shinn "Mission accomplished."
    thinking "Well, I hope you had fun with my dick. Besides, this is just the beginning."
    thinking "There's going to be a lot more to come for you and Touko."
    shinn "I'll be going now. Go have a swim to clean yourself up or something."
    shinn "And remember, if you tell anyone about this, you know what'll happen then."
    $ renpy.end_replay()
    $ persistent.aina__sex_scene_1 = True
    jump touko_aina__intermission_1

# *CG TRANSITION*

# Title: touko_aina Arc – Day3 – Morning – 10:00AM
# Location: Haruka Academy, Hallway
# Background CG: Hallway

label touko_aina__intermission_1:
    "I come in early in the morning to check things out with Aina"
    "Afterall, what I did with her yesterday was kind of amazing."
    "I think today I'm gonna bring her along for a sex field trip."
    "As I walk across the hallway to my staff room, I spot the person I'm looking for."
    thinking "There she is."
    "I walk up to her casually, as if nothing's happened between the two of us."
    "She's looking at the floor as she walks. She certainly doesn't look like she's in a good mood."
    "But who can blame her? After what I did with her yesterday, it's only natural for her to feel upset."
    shinn "Hey Aina. Good morning."
    "Just hearing my voice seems to give her a start, and she raises her head."
    "Her eyes bore into me, like in her head, I've already become a murder victim."
    aina "You..."
    shinn "I what?"
    aina "You have some nerve to come and talk to me like this."
    "Aina raises her voice, and some of the bystanders around us start to look our way."
    "The situation is starting to get a bit tense. I don't want things to get out of hand with everyone watching like this."
    thinking "Shit, I need to defuse this."
    shinn "Well Aina, I'm sorry, but I don't know what you're talking about."
    shinn "I'm just here as your math tutor, and that's it."
    "Aina is still looking at me like she's killing me in her mind."
    "In turn, I give her my “if you expose me, you're dead” look."
    "She gets the signal, and it seems she's decided to play nice for now."
    "She takes a deep breath."
    aina "Ahem. Good morning, Shinn."
    thinking "Phew..."
    shinn "Good morning, Aina."
    aina "So? What business do you have with me today?"
    "With the tension defused, the other students start to walk away, apparently deciding we're not interesting enough to bother with."
    "Since their attention is no longer on us, I walk up close to her and gently whisper in her ear."
    shinn "Meet me at the utility room during lunch. Don't be late."
    aina "What? Why would I..."
    "I interrupt her reply."
    shinn "You know what'll happen if you don't..."
    "Before she has the chance to reply, I walk away."
    thinking "Heh. Let's see if you'll show up."
    thinking "She already knows what'll happen if she doesn't."
    jump aina__sex_scene_2



# *CG TRANSITION*

# Title: touko_aina Arc – Day3 – Afternoon – 1:00PM
# Location: Haruka Academy, Utility Room
# Background CG: Utility Room
label aina__sex_scene_2:
    "I came ahead of time to make preparations for what I'll be doing with Aina today."
    "I expect a bit of resistance from her, but not too much."
    "When you consider what I already did with her yesterday..."
    shinn "Heheheh."
    shinn "Can't wait to get a taste of that sexy swimmer's body again."
    "Time continues to pass as I wait for her arrival."
    shinn "Ugh, It's getting late. Is she even coming?"
    shinn "If she isn't coming, I am going to find her it'll be a whole lot more trouble for that bitch."
    shinn "I'll give her 5 more minutes."
    "I stare at my phone as I wait, counting down five minutes by the clock."
    shinn "Well, looks like she's not coming. Guess that's it."
    shinn "Time to go find her."
    "But before I could leave the room to start my search, Aina opens up the door."
    shinn "Tsk. You sure took your time."
    aina "..."
    aina "Fuck off, Shinn."
    shinn "Woah. Watch your attitude young girl."
    aina "Cut the crap. What do you want with me now?"
    shinn "Ah. Good question, Aina."
    shinn "You see... When you and Touko were enjoying a fun and sexy time in here..."
    shinn "I was left out all by my lonesome, having a sad look through that little keyhole."
    aina "So?"
    shinn "I was thinking that you could reenact with me the same thing you did with Touko."
    shinn "I'm sure this will satisfy the craving I built up watching that juicy yuri scene."
    aina "You're a sick fuck."
    shinn "Hahaha... Watch your language there."
    shinn "You don't want to offend me, do you?"
    aina "..."
    aina "I am sick and tired of your games."
    shinn "Games? Heh, what games?"
    aina "Whether I say yes or no, you're going to do it anyway, so why bother to even ask me?"
    shinn "Smart girl, Aina. Probably the smartest I've come across so far."
    aina "..."
    shinn "You see, it's very simple."
    shinn "Ever since I saw you, I knew I couldn't let you go without having sex with you."
    shinn "Your body is too irresistible. There's nothing that could make me give up on that."
    shinn "So, it doesn't really matter what you try to come up with to get in my way. I'm just going to keep at it one way or another."
    shinn "If it comes to that, there are all kinds of ways I can make your life difficult if I don't get what I want."
    shinn "But, if you go along with this now, I'll delete the dirt I have on Touko and forget about things with the two of you."
    shinn "After that, it'll be over between you and me."
    thinking "Well, if you're not addicted to my cock by then, that is."
    "I corner her against the walls."
    shinn "So why don't we stop the chatting and get down to business?"
    "Cornered like this, Aina seems unable to think straight."
    "Maybe she's decided that her best option is to go along with things as I said, or maybe she just doesn't have the nerve to resist, but her body seems to loosen up."
    "I decide to take a chance, and reach slowly reach out my hand to feel her pussy."
    aina "Mmm~"
    aina "Don't... don't move too fast, okay?"
    shinn "Too fast? Heh..."
    shinn "Alright then. What do you want me to do?"
    aina "..."
    aina "A... Kiss..."
    shinn "A kiss? From me, huh? Not Touko?"
    aina "..."
    shinn "What changed your mind?"
    shinn "Did you realize after you got a taste of my cock before that you were missing out on the good stuff?"
    aina "Shut... Up..."
    shinn "I expected better from you, Aina."
    "Despite my words, Aina continues to stare at me, as if she'expecting something."
    shinn "You really want that kiss, huh?"
    shinn "Okay then."
    "I lean my face forward, extending my tongue."
    "She opens up her mouth to let me in, and begins to interlock her tongue with mine."
    "Unlike those forced kisses from before, this one was a surreal experience."
    "She begins to work her tongue against mine, and I can feel her saliva dripping into my mouth."
    "The excess saliva starts to trickle out from our mouths, even dripping from out chins."
    "During all of this, I've continued to gently stroke my fingers over her pussy.."
    "It's almost an exact repeat of the scene with Touko from before. Except for the part where Touko didn't have a dick."
    "Speaking of dick, the feeling of our kiss, and of her smooth pussy against my hands, has gotten me completely hard."
    "In fact, I'm so hard now that the pre-cum has already started leaking out, and Aina hasn't even touched me yet."
    "I stop the kiss for a moment to examine the wet spot growing against the bulge in my pants."
    "As I pull back, Aina takes notice of it as well, and begins to stroke the tip."
    "Without my instruction, she takes the initiative and unzips my pants."
    "My dick immediately springs free, catching her by surprise."
    shinn "Whoa, looks like you know what you're doing after all."
    shinn "Just like I thought, I had you pegged as the really horny one between you and Touko."
    shinn "Tell me, do you watch porn every day to pick up tips?"
    aina "I started watching lesbian porn after I got together with Touko... but I've watched straight porn a few times too."
    shinn "I bet you got curious after seeing a man's dick on the internet."
    shinn "You must have wanted try tasting it for yourself, right?"
    aina "..."
    "She doesn't answer, but with this girl, I can tell that it's true."
    "My dick is quivering while we speak."
    shinn "My dick is hungry for some attention. Why don't you try out some of your techniques from the internet on me?"
    aina "..."
    "Aina begin to stroke my dick slowly."
    aina "Its... warm..."
    shinn "Heh. You like it, don't you?"
    shinn "Come on, stroke it harder, pleasure me if you can."
    shinn "In return, I'll make you feel good with my fingers."
    "Aina doesn't reply, but from her expression, I can see I've got the go ahead."
    "I shift her underwear to the side and begin to insert my finger as she strokes."
    aina "Ah~"
    "I begin to finger her gently. I can't be bothered to go soft like this all the time, but I feel like showing her a bit of consideration."
    "In retun, she strokes my dick at a matching pace."
    "Our movements are perfectly synchronized so that the two of us can cum at the same time."
    "She's staring straight at my face as she jerks me off, and I can feel the hot, steamy air of her breath against my skin."
    "She's getting more into this by the moment."
    "Her expression right now looks so different compared to yesterday."
    "Far from being repulsed, it looks like she's started embracing this."
    "The more I look at her, the sexier she seems."
    "Just watching her builds up my tension, making my dick even harder."
    "And of course, her stroking is out of this world as well."
    shinn "Ah... Aina, you're so good at this."
    aina "You... too..."
    "Hearing my voice seems to get her even more excited."
    "She starts to stroke even faster..."
    "And I start to finger faster."
    aina "Ah~ Shinn..."
    aina "I can't..."
    shinn "Let it out, Aina."
    shinn "Unh~"
    "I can feel something rising up in me, about to erupt."
    shinn "Ugh, I can't take it! I'm gonna cum soon!"
    shinn "Hey Aina, come on! Let's cum together!"
    "She speeds up her hand as she approaches her climax, while I speed up my fingers."
    aina "Ah~!"
    aina "I- I'm cumming!"
    "At that moment, a flood of her juices gush from her pussy."
    aina "Ah~ It feels so good!"
    "As she cums, she violently jerks at my penis."
    shinn "Agh, me too!"
    "The sight of her, and the sudden movement, force me over the edge as well."
    shinn "Ahh~ "
    "The feeling is incredible. It's enough that the two of us nearly black out."
    "The two of us lean against each other, panting as we try to regain our senses."
    "The area around us is a mess. Her skirt is covered with my cum, while my hand and her panties are drenched with her pussy juice."
    "From the look on Aina's face, it seems like she's still hungry for more."
    shinn "Not enough, eh?"
    shinn "Seems like you're ready to move on to the main course."
    aina "Yeah..."
    shinn "Alright then. Since you're being a good girl today, I'll give you a treat."
    "I lift up one of her legs, exposing her soaking wet panties."
    aina "What are you doing?"
    shinn "Oh, you'll see."
    "I shift her underwear out of the way to get a clear view of her pussy hole."
    "Without giving any warning, I slam my dick straight into her pussy."
    aina "Oww~"
    shinn "You love it. Don't you?"
    "It looks like the sudden thrust sent a shock of pain through her."
    "But that doesn't stop her from enjoying my dick."
    aina "Yes..."
    "I fall into my usual forceful pattern as I penetrate her."
    "I thrust deep inside her, all the way to her womb. And damn, but she sure shows that she's feeling it."
    aina "Ah~ Harder!"
    "I pick up the pace as the raw pleasure shows itself on her face."
    aina "Yes~!"
    "She holds onto me tightly, like she can't bear to let go or let this end."
    "She's completely drowned in the act now. There's nothing on her mind but my cock."
    "I think she's well and truly addicted now, but just to be sure..."
    shinn "So tell me Aina, what do you love the most?"
    shinn "My dick? Or Touko's pussy?"
    aina "Your dick!"
    aina "Your dick is the best!"
    shinn "Heh. That's what I thought!"
    shinn "Since you're being such an obedient and good girl today, I'm going to pump my full load of cum inside you."
    shinn "Make sure you savior the taste, okay?"
    aina "Yes..."
    shinn "Just a yes? That's not right. From now on, you call me Master."
    shinn "Understood?"
    aina "..."
    shinn "Come on..."
    shinn "With me as your master, I can give you the love and pleasure Touko can't, every single day."
    aina "Yes, master."
    shinn "Good girl. Now, what about Touko?"
    "Without taking a moment to think, she responds."
    aina "Touko? What about her?"
    "Seems like she's finally snapped."
    aina "Why should I think about Touko? She doesn't have a dick and can't make me feel like this."
    aina "Dicks are the best after all, especially yours!"
    shinn "Hahaha..."
    shinn "That's what I want to hear."
    "As she said that, I could feel her pussy clamping down on me even tighter."
    "Seems like her desire for my cum is getting stronger by the minute."
    "At the same time, it feels like my balls are almost desperate to shot it out."
    shinn "Heh. You really want my cum, huh Aina?"
    aina "Yes~"
    shinn "Well then, how about this? From now on, you can be my sex slave, and I'll give you loads of my cum every single day."
    shinn "What do you say?"
    aina "Yes..."
    aina "Yes Master!"
    shinn "Good. Now before you get your treat, there's something I want you to promise me."
    aina "Ah, hurry up Master, tell me! I can't wait for your cum!"
    shinn "Help me make Touko my sex slave too."
    aina "Geez, aren't I enough?"
    shinn "Oh, are you jealous? Don't worry, you're still my favorite pet."
    shinn "Now, will you do it?"
    aina "Yes master! I'll do whatever you say!"
    shinn "Good. Now here's the reward you've been waiting for!"
    if persistent.cum == "inside":
        aina "Yes! It's coming!"
        $ renpy.block_rollback()
        jump aina__sex_scene_2_inside

    elif persistent.cum == "outside":
        aina "Yes! It's coming!"
        $ renpy.block_rollback()
        jump aina__sex_scene_2_outside

    else:
        menu:
            aina "Yes! It's coming!"
            "Cum inside":
                $ renpy.block_rollback()
                jump aina__sex_scene_2_inside
            "Cum outside":
                $ renpy.block_rollback()
                jump aina__sex_scene_2_outside

label aina__sex_scene_2_outside:
    "Her pussy was squeezing me like mad."
    "I'd reached the point where I couldn't hold out any longer."
    aina "Hurry up, master!"
    shinn "It's coming!"
    "I pound her womb one final time, then just as I'm about to explode, I pull it out and spray my cum all over body."
    aina "Ah~! Shinn's cum~"
    aina "It smells so good!"
    "The room is filled with the smell of my cum."
    "Aina has really milked me dry with this. It'll be a while before I'm ready to go again."
    "But her body, and face are completely covered with my jizz, and Aina seems fully sated."
    "She's blissed out, basking in the feel, smell, and taste of my cum, which overpowers her senses."
    "It looks like she doesn't even know what's going on around her anymore."
    jump aina__sex_scene_2_end

label aina__sex_scene_2_inside:
    "Her pussy was squeezing me like mad."
    "I'd reached the point where I couldn't hold out any longer."
    aina "Hurry up, master!"
    shinn "It's coming!"
    "In an instant, I spray everything that's left inside my balls straight into her womb."
    "Aina convulses as she feels the boiling heat of my cum flooding her insides."
    aina "Ah~! Shinn's cum!"
    aina "It feels so good inside me!"
    aina "I can't take it all!"
    "Seems like she's gotten so into this, she's lost all awareness of what's going on around her."
    jump aina__sex_scene_2_end

label aina__sex_scene_2_end:
    aina "Ah~ Shinn's cum. I love it!"
    aina "Men are the best after all!"
    shinn "Heh. That's right."
    shinn "Now, if you do as I said, I'll give you a bigger treat next time. Alright?"
    aina "Yes master!"
    shinn "Good."
    shinn "Today, Touko will have another tutoring session, I want you to attend it."
    shinn "From there, it'll be up to you to convince her. You got that?"
    aina "Yes master!"
    shinn "Alright. See you later."
    $ renpy.end_replay()
    $ persistent.aina__sex_scene_2 = True
jump touko_aina__intermission_2


# *CG TRANSITION*

# Title: touko_aina Arc – Day 3 – Afternoon– 3:35 PM
# Location: Haruka Academy, Hallway
# Background CG: Hallway

label touko_aina__intermission_2:
    "The tutoring session was supposed to start at 3.30pm, but I'm running a little bit late."
    "You can chalk that up to the work I've had to go to to get Aina properly ready."
    "She's waiting in the wings to get things started now, wearing nothing but a dog collar."
    thinking "Yeah, this is definitely a good look for her."
    "I take my time to look her body up and down as I approach."
    shinn "So? You ready?"
    aina "Yes!"
    shinn "Alright. Keep quiet for now keep yourself out of the way until I need you."
    shinn "I'll call you in when I'm ready."
    aina "Got it!"
    jump touko_aina__threeway_1

# *CG TRANSITION*

# Title: touko_aina Arc – Day 3 – Afternoon– 3:40 PM
# Location: Haruka Academy, Class 3-2
# Background CG: A typical classroom with a blackboard. Chairs and desks stand in single-file rows.

label touko_aina__threeway_1:
    "I slide the door opened to find Touko already waiting for me."
    "She tenses up the moment I come into the room."
    "Well, that can't be helped considering what I've already done with her."
    "I keep my eyes locked on her as I head over to my seat at the teacher's desk."
    "By the time I get all my things out, Touko is already looking seriously unnerved."
    shinn "What's wrong, Touko? You seem nervous."
    touko "..."
    touko "You're not going to do anything with me again today, right?"
    shinn "Well... we'll see about that."
    touko "Please..."
    "Her voice is a soft, pleading whisper."
    touko "Please leave me and Aina alone. We were already having a hard enough time being together through everything."
    touko "Why are you doing this to us?"
    "As she pleads with me, I can see her eyes starting to fill up with tears."
    thinking "Uh-oh. Here come the waterworks I guess."
    touko "I'm begging you to let us go, please."
    shinn "Heh. What exactly am I supposed to get in return for letting you off?"
    touko "..."
    touko "I could give you money."
    shinn "Money? I'm already fine on that front. What I want is sex. And you don't want to give that to me, so where does that leave us?"
    touko "Then use me! Use my body! Just leave Aina alone! As long Aina stays safe and we can be together, I'll put up with anything!"
    shinn "You sure?"
    touko "Yes, I'm sure! Please!"
    shinn "Well you see, about that..."
    "This seems like the perfect time to call on her."
    shinn "Aina! Come in!"
    aina "Yes Master!"
    touko "M... Master...?"
    "The door slides open to reveal Aina, naked and hungry for sex."
    aina "Aina, reporting for service!"
    "Touko turns around and stands up with a jolt as she looks at Aina with a mixture of horror and confusion."
    touko "No..."
    touko "This can't be..."
    "The sudden revelation had an overwhelming impact on her. I could see Touko's heart sinking as she stared at Aina, taking in what this meant."
    touko "..."
    shinn "Hahahahaha!"
    shinn "Sorry Touko, I'm afraid it's already too late for that!"
    shinn "You can offer anything for her that you want, but all your precious girlfriend cares about now is my cock!"
    touko "..."
    touko "Aina.... Why?"
    aina "Why? Because I love Master's cock!"
    aina "It's big and feels the best!"
    aina "When Master fucked me, it felt better than anything. So there's no way you could ever take his place, Touko."
    touko "...."
    touko "No way... This is a joke, right?"
    shinn "A joke? Maybe for me. But this is definitely real. You should get used to where you stand here."
    shinn "Give it up, Touko! It's over for you."
    shinn "If you love Aina and want to be with her that much, go ahead and join her! The two of you can service me together."
    shinn "There's always room for more in my harem!"
    "Aina slowly walks up to Touko"
    aina "Come on, Touko. Why not join me? We can have fun together all the time with Master's cock!"
    aina "Don't you want to be really satisfied?"
    "Touko looks completely lost. Her expression is blank and unchanging, but I can tell she's breaking down."
    touko "I..."
    "Aina cuts in, doing her best to persuade her for me."
    aina "If you really love me, we should stick together! Stay with me, and we can keep having fun all we want!"
    "Touko looks Aina in the eye."
    touko "Is... Is this what you really want? Do you love doing this?"
    aina "Of course! Why would you even need to ask?"
    "Aina was so emphatic, Touko's reslve was starting to waver. No matter how far this might have been from what she expected, Aina was utterly sincere."
    "I walk up to stand alongside them and apply a little more pressure to Touko."
    shinn "Look at her, Touko. Have you ever seen Aina this happy before?"
    "Touko looks over Aina again, examining her blissful expression."
    "There's no question, she's never seen Aina looking like this before."
    touko "No..."
    "Finally seeming resigned, Touko asks one more time."
    touko "Aina, is this really what you want?"
    aina "Yes, it is!"
    shinn "Come on, Touko. What are you waiting for!?"
    "Touk seems to have finally come to terms with the fact that she's powerless to stop this. She stands in silent agony as the situation sinks in."
    "She unbuttons her clothes and skirt, undoes her black lace bra, and pulls down her panties."
    "Her luscious breasts and the pussy I enjoyed so much yesterday are now fully exposed."
    shinn "Oh? Good girl."
    aina "Yeah! Touko is part of the family now!"
    "It's a wonderful sight having these two beautiful and well-developed girls on display like this. I join in too, and strip down along with them."
    "My dick flicks out, standing to attention as I pull my pants down. Touko is flushed with embarrassment, while Aina is enthralled."
    aina "Wow, Master's big cock!"
    "Seeing the contrasting reactions of the two in front of me, it's impossible for me to resist. And why should I?"
    shinn "Both, of you kneel down and suck my dick."
    aina "Yes Master!"
    shinn "You heard me. You too, Touko."
    "At this point, Touko has given up on fighting back. She's accepted this as reality, and follows suit along with Aina, even as her face shows that she's still repulsed by all of this."
    "The two of them kneel down in front of me side by side. With the two of them on the ground like this, the tip of my dick nearly reaches out to touch their foreheads."
    "Touko, who's never seen a dick up close before, is clearly intimidated at the sight of it."
    thinking "Looks like she's wondering if it's even possible for her to take it in her mouth."
    shinn "Well ladies, what are we waiting for?"
    "Aina knows what to do, and makes the first move, licking my cock along the side. Seems like she's trying to lead Touko by example."
    "Touko takes a look at Aina's skillful tongue work, and does her best to follow suit."
    "Aina continues to lick while keeping a watch over Touko. She works her tongue down the length of my shaft, even taking my balls into her mouth."
    shinn "Ahhh... Touko, this feels great."
    "As Touko begins to pick up a feel for what she's doing, she takes a bold step and takes my cock into her mouth, filling up her throat as far as she can while Aina continues to suck off my balls."
    touko "Enngh... It's salty."
    "Touko makes a sour face as she finally gets her first taste of a real dick in her life. Hardly surprising in her case."
    "But, she should be used to it pretty soon."
    shinn "Aww, yeah... You guys are doing great."
    "They keep sucking and licking together, trading off on my cock and balls between them. It feels amazing."
    aina "Mmm..."
    "Aina's clearly enjoying this. Seems like her lesson this afternoon really sunk in."
    "Her sucking feels like it's trying to pull my cum straight out of me. Considering how much time she's probably spent licking Touko's pussy, it seems she's probably picked up a thing or two."
    shinn "Ugh... I'm gonna cum..."
    "Touko understood what was coming, but she didn't want to think about it, and kept on at her regular pace."
    "Meanwhile, Aina picks up the intensity in anticipation of what's coming,"
    aina "Ah, Master is going to cum! Please shoot out your thick juicy cum for us!"
    shinn "Ugh! Stick your tongues out!"
    "They both hold their tongues out for me, like they're waiting for the taste of my cum."
    "Without their mouths to stimulate me, I take over with my hand, forcefully jerking myself off to the finish."
    shinn "Here it comes!"
    "I aim between their faces as I shoot out my cum. It sprays out all over them, across their faces, their bodies, a little even landing in their mouths."
    aina "Ah~ Master's cum! It's all over me! I love it!"
    "No wonder that Aina is enjoying it. But Touko seems a little surprised at the taste."
    touko "So... this is what cum is like..."
    touko "It tastes... salty, huh."
    aina "Master's cum tastes great! Isn't that right, Touko?"
    touko "..."
    "Both of them really seem to get into the taste and smell of my cum. Although Touko still seems a bit reserved, it looks like she's adapting to this pretty fast."
    shinn "Heh. It's not over yet."
    "I strip off the rest of my clothes, and lie down on the classroom floor."
    shinn "Alright. Touko, I want you to ride my dick."
    touko "W... What?"
    shinn "You heard me. Go ahead. ."
    "Touko still seems a bit reluctant."
    touko "..."
    "But Aina doesn't have much patience for Touko's resistance."
    aina "Come on Touko, listen to Master's orders. Be a good girl, and we'll both be rewarded with lots of his cum."
    shinn "Come on, Touko,Take a cue from Aina. She's being such a good girl trying to convince you."
    "Touko slowly gets into place and positions herself for insertion."
    shinn "Well, what are you waiting for? Hurry up and put it in."
    "The size is a bit much for her to handle, but Touko works up her resolve and finally brings herself down onto it."
    "She takes my dick inside her, bit by bit, the pleasure starting to show on her face."
    touko "Ah~ "
    "Finally, she manages to sink down all the way onto me, my dick fully inserted inside her."
    "At this depth, I can feel the head of my cock rubbing up against her womb."
    touko "Ah~! It's so deep inside me!"
    aina "Isn't it amazing?"
    touko "I guess..."
    "My cock is throbbing for more action, so I push Touko to get started."
    shinn "Come on and move Touko. My cock isn't going to milk itself."
    "Touko starts to move up and down. She's riding my cock slowly, but for an amateur like her, it's a good start."
    shinn "That's more like it."
    touko "Mmm~"
    "This must be reminding her of the pleasure she already got a taste of last time."
    shinn "You missed that feeling, didn't you?"
    shinn "I know you fell in love with my cock the moment you tasted it."
    touko "..."
    shinn "It happened to Aina too. Just one round with my cock was enough to get her completely hooked."
    shinn "Just a little bit of training was all it took to bring out the animal in her. Her true, uncontrollable lust for sex."
    shinn "You've got the same thing inside you, Touko. You can be just like Aina, with the same thirst for cocks and cum."
    touko "..."
    shinn "So now, I'm going to bring out the animal inside you, and show you who you really are."
    "I begin thrusting myself up from the floor, slamming my cock deep inside her. It's a lot of effort, forcing her whole body weight up with every single stroke, but for Touko's sake, I'm going to put out everything I've got."
    touko "Ahh~ Too fast~"
    shinn "Heh... Not fast enough."
    "While all this was going on, Aina was watching from the sidelines."
    aina "Hmmph..."
    "Looks like she's pretty jealous that Touko's getting to have all the fun.  "
    aina "No fair~ Aina wants to play with Master too!"
    "Well, considering her good work, it'd be a shame to leave her out."
    shinn "Alright Aina, why don't you sit on my face so I can lick your pussy?"
    aina "Okay~"
    "Aina hurries over and gets on top of me without hesitation."
    "She faces Aina as she rests her cushion-like ass against my face."
    "Seems like all the time she's spent training her body for swimming has really paid off."
    thinking "Damn... If her ass was this soft, I should have tried this before."
    "I stick out my tongue, running it over her pussy."
    aina "Ahh... Master's tongue is licking my pussy! You're sucking out all the juice from my pussy!"
    aina "Amazing! It feels so good!"
    "Unable to resist the feeling of my tongue, Aina rocks her hips against me, grinding herself against my face."
    "Her butt feels so soft against me, I can't help but let her go at it."
    "It's like having a plush, warm pillow squashed against my face."
    "It's a special kind of bliss all on its own."
    "Meanwhile, Touko is rocking her hips against me as well like there's no tomorrow."
    "Seems like she's really getting into it now."
    "Their bodies are heating up as they get more and more wild and horny."
    "Even like this, the two of them still love each other, and they look at each other with hazy eyes as they bounce against me."
    "Seems like they're flashing back to all the dirty stuff they've done together."
    "It almost feels like their hearts and minds are being connected through me right now."
    "They reach out for each others' hands, holding on tight, not needing to hide anything now."
    "Touko is the first one to speak out."
    touko "Aina, I love you!"
    "Aina follows suit"
    aina "I love you too, Touko!"
    "Aina leans forward, moving her face in close and opening her mouth, inviting Touko in for a kiss."
    "As Touko follows her lead, the two of them lock mouths in an energetic and passionate kiss."
    touko "Mmm~"
    aina "Mmm~"
    "The two of them let their saliva run into each other's mouths, drip down each other's faces, even dripping onto me underneath them."
    "Of course, I don't mind. I'm getting the most out of their love of anyone after all."
    "Touko pulls back first, and gazes at Aina with hearts in her eyes."
    touko "Whatever you do, Aina, I'll always be with you."
    aina "I feel the same way. I'm glad we can stay together like this."
    "Looks like Touko doesn't care about the circumstances anymore. As long as Aina is with her, she's happy."
    "She's finally accepted the fact that the only way she can stay together with Aina is to give in and become my sex slave."
    "She's finally realized just how amazing my dick really is, and why Aina loves it so much."
    "She lets out an even louder moan as she grinds herself against me."
    touko "Ahh~"
    "As she senses Touko enjoying herself more and more..."
    aina "Touko, Master's dick is amazing isn't it?"
    touko "Yeah..."
    aina "This is what we're meant for, Touko. Being Master's cumdump is the best!."
    aina "So let's do our best and give Master lots of love, okay?"
    touko "Ahh~"
    touko "Okay..."
    touko "Let's cum together and give him our love."
    "Aina gives her a bright smile back."
    aina "Hmm! Let's do that."
    thinking "Wait a minute..."
    thinking "How the hell did this turn into a lovey-dovey situation?"
    thinking "Pffft... Whatever. As long as it keeps going well for me, I'm fine with it."
    "Both of them start to rock faster."
    "Their pussies are getting tighter, and it's getting harder and harder to get my tongue inside of Aina."
    touko "Ah~! Aina, I'm cumming~ "
    aina "Me too! Let's cum together with Master!"
    touko "Yes! Let's all cum together!"
    touko "Ah~ Ah~ Ah~!"
    aina "Ah~ Ah! I'm cumming!"
    "A sudden squirt of juices gushes from their pussies as the two of them cum together."
    touko_aina "Ahh~ "
    "I tasted Aina's sweet pussy juice as it runs into my mouth and trickles out along my jaw."
    "Unable to resist the taste of the sweet high school girl on top of my, I finally cum, hard, into Touko's pussy."
    "My cum mixes together with Touko's own juices as they splash out."
    touko "Ah~ Master's cum!"
    "The whole space around us is a mess. My cum and their juices are mixed together in a puddle on the floor."
    "That was a hell of a good time. But for all I enjoyed myself, it was nothing compared to the number it did on Touko."
    "Just like Aina, she's completely mine now."
    "The two of them stand up and pull me to my feet."
    touko "Master~"
    shinn "Heh. Good girl. Looks like you get your purpose in life now."
    aina "Yeah, we get to have fun with master now! I'm so proud of you, Touko."
    aina "We're going to be together forever!"
    touko "Yes~"
    $ renpy.end_replay()
    $ persistent.touko_aina__threeway_1 = True
    jump touko_aina__gangbang_1

label touko_aina__gangbang_1:
    "I over a dog collar to Touko."
    shinn "Wear this, Touko. You can be just like Aina now."
    "Touko wastes no time putting it on.."
    aina "It's a perfect fit! And it looks just like mine!"
    touko "It does!"
    shinn "Alright, enough chatting. I have a mission for the both of you."
    aina "Master is giving us a mission? What is it?"
    thinking "Heheh. They have no idea."
    shinn "Well... Let me bring you to the gymnasium first, and you'll find out soon."
    touko_aina "Okay!"

# *CG TRANSITION*

# Title: Aina Arc – Day 3 –Late Afternoon– 5:00 PM
# Location: Haruka Academy, Gym Hall
# Background CG: Typical Gym hall  

    "It was a long and exciting walk. Since the two of them were following along behind me naked,we were flirting with the risk of getting caught the entire time."
    "Of course, at this hour, everyone has usually already gone home, but I have to count myself lucky that we didn't run into any last-minute surprises."
    "Of course, there are some people I already knew were still here today."
    "As we reach the entrance of the hall, I can already hear the chatter of a large number of boys' voices inside."
    shinn "Ah, looks like they've made it..."
    "I open the door, and show the girls the crowd I've assembled for them."
    "When the boys inside catch sight of Touko and Auna's faces, they immediately go wild."
    male_1 "Seriously? Aina and Touko? Fuck YES!"
    male_2 "Alright! I can't believe we're seriously gonna do this!"
    male_3 "Yes!! This is a dream come true!"
    "There's no way I can keep count of them all, but from the look of it, almost everybody showed up."
    "The guys here are all members of the school's sports clubs; baseball, football and so on."
    "Right now, the hall is filled with at least a hundred boys, almost the entire male athlete population of the school."
    "These guys have always had their eyes on the choicest girls in the school's sports clubs."
    "After having spent day after day watching these girls practice, their ability to control their hormones has already been taxed to the limit."
    "And in terms of stamina, these boys should be able to last all day."
    "The whole bunch of them have already gotten themselves ready ahead of time. They've been standing around in their underwear waiting for us."
    "To properly kick things off, I step forward to introduce the girls to the crowd."
    shinn "Gentlemen, welcome to tonight's fuck fest! I know you've been looking forward to this!"
    shinn "I've brought with me a couple of girls you've had your eyes on for a long time! You all know know them, and you all want them!"
    shinn "Let' give a warm welcome to the bright and cheerful Aina, and the tomboyish and sexy Touko!"
    "When they hear the girls' names, the crowd goes wild."
    male_1 "FUCK YEAH!"
    male_2 "ALRIGHT!"
    male_3 "WOOOOOOOO!!"
    "As the crowd gets a bit crazy, Touko and Aina start to draw back, looking unnerved."
    shinn "Getting a bit scared?"
    aina "Master... Why are all these people here?"
    shinn "Don't worry, love. These people are just here to have fun with you."
    touko "Really?"
    shinn "Yeah, I'm sure you'll love it."
    shinn "After all, they all came here to enjoy and appreciate your bodies just like I do."
    touko "Okay~"
    "Just hearing that from me is enough to alleviate the girls' worries, and I can see them start to relax."
    shinn "Come on, girls. Let's go."
    "As I lead them to the center of the crowd, the boys look on with hungry eyes. Some of them are actually drooling."
    "Down to the last one, I can see the obvious bulges protruding at the fronts of their underwear."
    shinn "Look at them all, Aina, Touko. You see how much they all love your lustful bodies?"
    "Aina gazes around at the crowd wth excitement, paying particular attention to the cocks that are going to be used on her soon."
    aina "Wow, there's so many!"
    "Touko, on the other hand, was overwhelmed by the sheer number of people lusting after her and Aina."
    touko "Wow..."
    "As Aina and Touko start to come to grips with the situation they've gotten involved with, I can see their bodies are starting to react."
    "Naked as they are, I can watch their pussies getting wet before my eyes."
    shinn "Heh. You girls are leaking already. Can't wait, eh?"
    touko_aina "Master~"
    "As they watch the girls chatting in front of them, the boys start to grow restless."
    male_1 "Oi, Shinn! When can we start? We can't wait anymore longer!"
    male_2 "Yeah! I want to fuck them now!  "
    shinn "Calm down, you hungry bastards."
    shinn "Now girls, remember, you're here to enjoy the wonders of men's dicks."
    shinn "Let them use whichever part of your body they want. They will reward you with your favorite cum."
    aina "Ok~"
    "I release the rope from the collar and step away. Immediately, all the boys jumped in."
    male_1 "Aina!"
    male_2 "Oh~ Touko body!"
    "All of the boys took off their underwear and begin to use whatever body parts they can find on Aina & Touko for pleasure."
    "Aina was as usual more daring and willing person. As soon as the boys approached them, Aina shows no sign of any resistance or hesitation."
    "One of the boys push her down and lifted up her legs and immediately mate press on Aina's pussy and she was feeling the wonderful pleasure."
    aina "Ah~"
    male_11 "Its amazing! Her wet pussy is so tight. Shinn must have trained her well!"
    "The boys starts to slowly pound her, making his dick reached all the way inside her womb."
    aina "Ah~ More~ More~"
    "Seeing how Aina was being screwed, more boys started to jump into the action."
    male_1 "Ugh. Aina. Please use your hand and rub my dick!"
    aina "Sure~"
    "Aina comply and stroke the person dick hard too."
    male_2 "Aina! Me too!"
    "Aina uses her other hand stroke his dick."
    aina "Ahh~ You boys cock are so hard and thick~"
    male_3 "Oh. Slutty talk from Aina! I can't wait anymore!"
    "Upon hearing the talk, one of the boys stood near Aina face kneel down and force grind his dick into Aina mouth pussy."
    male_3 "Aina. Please accept my sweaty cock in your mouth!"
    aina "MMM~"
    "Aina was taking on every dick she can possibly get on."
    male_3 "Aina mouth pussy is so great. It felt like my dick was melting away in her mouth!"
    male_4 "Ugh. Not just her mouth her pussy felt so tight, its driving me mad!"
    male_2 "Even her hands too! This is almost heaven. I can't believe Aina is such a slut!"
    male_3 "Her tongue is moving around my dick so well."
    aina "Mmm~"
    aina "Hmm... Please give me more of your juicy cock!"
    male_3 "Sure thing!"
    "Not to missed out on the action, Touko started doing the same thing as Aina did."
    "She lay down on the floor and got pressed down by one of the boys from basketball team."
    male_5 "Yes. Touko's pussy! I have been dreaming about this since day one!  "
    male_5 "Everyday I watch you practice; your movement and your body make me want to fuck you so badly."
    male_5 "I always go home after that to masturbate about you!"
    "Seeing how much the boy truly love Touko lusty body so much, she gives him an assurance to enjoy as much as he could."
    touko "Its okay! You can now enjoy my real slutty pussy as much as you want!"
    male_5 "Ah~ I can't wait!"
    "The student slowly inserts his dick into Touko's pussy!"
    male_5 "Ah! Touko's pussy! I have been waiting for this for my whole life! It's so tight and wet. Its simply out of this world!"
    "One of the boys quickly jumped in for a request."
    male_6 "Ah! Touko. Please rub my dick with your precious hand!"
    touko "Hm? Ah~ Sure..."
    "Touko uses her hand to slowly stroke his dick and soon another person request the use of her other hand."
    male_7 "Me too! Touko! Please!"
    touko "Okay~ "
    "Touko slowly stroke both of the boy's dick."
    touko "Ah~ So big..."
    male_6 "Touko hands are so soft and delicate. It felt amazing in my dick!"
    male_7 "Yea!"
    male_8 "Heh... Look at the both of you. I didn't know you girls are such naughty in nature."
    male_9 "Yea. I am so glad that I came today. This is a once in a lifetime opportunity!"
    male_4 "Hey! Why not we cum all together and mind break her on the first round."
    male_1 "Yea! Let's do that!"
    "All the boys started to get more aggressive with their actions."
    "To keep up the pace, Touko and Aina both stroke they boys dicks faster. Anticipating for a cum shower."
    touko "Hmm... Everyone dicks feel so good. Please give me all of your cum!"
    touko "Shower me with all your juicy and tasty cum!"
    male_5 "Yes! You are going to get all of it. Make sure take every single drop of it!"
    touko "Ahh~ "
    "Meanwhile, the boys fucking Aina can't take it anymore."
    male_1 "Oh... Aina! I can't take it anymore. Please accept all of my cum!"
    aina "Hmm~"
    male_5 "You too Touko! Accept my seed in your pussy!"
    touko "Ahh~ Yes. I will accept every single last drop of your seed!"
    touko "Please give it to me~"
    "The boys give both of these girls a sudden bust of cum right into them."
    "The came together as planned they shoot their cum all over Touko & Aina's body. Leaving both of them completely drenched in the boy's cum."
    "Some of it got into their mouth..."
    "The girls felt the sticky cum in their skins, the taste in the mouth and pussy. They went crazy over it."
    "It is also seeming like the both girls are addicted to cum like how a person would be addicted to drugs."
    aina "Ah... There is so many cum and it smell so good. I'm going crazy!"
    touko "Hmm~ Taste so good."
    aina "Please give us more!"
    male_1 "Heh. No worries. There is plenty to come."
    male_2 "It's not the end of it yet, ladies. So, make sure you take it all of it."
    touko_aina "Sure! ~"
    "Time goes by, as the next 15th batch of boys getting ready to fuck both of them."
    "They bodies were filled with cum and black marks to indicate how many guys had used them."
    male_11 "Wow. Aina pussy is being used 45 times."
    male_12 "Heh. Touko even better! 60 times!"
    male_11 "And from the long of their faces, both of them want more!"
    "Bit and pieces of pubic hair was seen sticking around their mouth and hips area."
    "The boys must have done the girls hard."
    "Both of them were worn out. But they seem to be wanting to keep this up as they love doing it."
    "Touko was so happy to be part of all this. Thinking how all of these wouldn't had happened if it was Aina."
    "Still loving Aina and Touko wanting to let Aina know."
    "Touko crawl forward to her with cum still leaking out from pussy."
    male_8 "Hey! Where are you going?"
    "Touko reached in front of Aina."
    aina "Hmm? Touko?"
    touko "She move forward and give Aina a passionate kiss.  "
    aina "Touko?"
    touko "Aina. I love you."
    touko "Thank you for everything."
    touko "You show me the real side of me. The side of my love for you and dicks."
    "Aina smiled at Touko,"
    aina "Me too, Touko. I love you too."
    aina "Let's enjoy our new life as a cumdump sex slave, okay?"
    touko "Okay!"
    male_2 "Aww... Look at them. They both having their lovely dovely moment."
    male_1 "Aww... Isn't that cute?"
    "Not paying attention to what the boys said, both Aina and Touko started slurping each other tongue."
    aina "Mmm..."
    touko "Mmm..."
    "The straight on lesbian action caught the boys off caught."
    "It makes the boys even more hard."
    male_3 "Oh. What's this?"
    male_4 "Both of them kissing each other "
    male_2 "Damn it! It's making me hard again!"
    male_1 "Hey! Let's make their love more fulfilling with our cum!"
    male_6 "Heck yea! Let's do it! I want to fuck them again even though I cum so many times already."
    "The boys surrounded both of them and begin to jerk off."
    "Two boys begin to fuck them from behind in doggy style."
    "Aina & Touko kissing got sluttier. Which had excited the boys even further."
    "Both of them was enjoying the moment. Behind fucked from behind while kissing each other."
    "Amidst of all these, the boys were looking at them jerking their dick, preparing to give both of them cum shower."
    "As the kissing between both of them intensified, they got more aroused and let out an erotic moaning."
    aina "mmm~"
    touko "Mmm~"
    "At the same time, their pussy wall got tighter and tighter. Making the guys fucking them unbearable to hold on."
    male_1 "Ugh. She is squeezing me. I can't hold on much longer!"
    male_2 "Yea. Me too. I am gonna cum soon."
    "Both of them pounded their asses even harder."
    male_1 "Here it comes!"
    "In an instant, both of them shot out their cum deep into their womb."
    male_1 "UGH!"
    male_2 "UGH!"
    aina "Ah!~"
    touko "Ah!~"
    "The boys stick out their penis and load of cum was gushing out."
    male_3 "MY TURN!"
    "But that didn't stop the rest of the boys. Each of them takes turn to stick and pour they're cum into both of them."
    male_4 "Yes. Please accept my cum Aina! Get pregnant!"
    aina "Ah!~ You guys..."
    "Both Aina and Touko felt like they were in heaven. Their eyes roll up in pleasure."
    aina "Ahh! It felt so good!"
    touko "I love it!"
    male_5 "Ah! Aina, Touko. Please take my cum!"
    "Some of the boys were inpatient and couldn't wait. They simply just aim and shoot at which ever part of their body."
    aina "Ah So much cum. I love it!"
    "Both of them were drenched in cum. So much so that the entire gym hall was nothing but the smell of it."
    "The boys continue took turn to cum into them as the girls are receiving cum like a free flow buffet."
    "By now, both Touko and Aina had their stomach inflated due to the amount of cum intake."
    "It is also as if they look pregnant. But considering how much cum they have today, I am not surprised if it did happen."
    "As the boys release their last cum in the current session, the boys begin to show sign of exhaustion."
    "I thought this could be the end of the session as they might have ran out of fuel to carry on."
    "I walk up to check out the situation of both of the girls."
    shinn "So. How are my girls doing?"
    aina "Ah! Master! You are here! I love it. I want more dicks inside nonstop 24/7."
    touko "Me too!"
    "I let out a smile."
    shinn "Good. Would you like to take a rest before carrying on?"
    aina "Ah! No master! I want more! No rest is needed!"
    touko "Yes. I will die without tasting cock! Master! ~"
    "Heh. it seems like they are having fun after all. Good."
    shinn "Hmm... What about the boys? Can you guys continue?"
    male_1 "Are you kidding me? We still have some left in our balls."
    male_2 "We are not dried yet. We are not going anywhere until the last drip is out."
    male_3 "We will continue even if it takes the entire night till morning!"
    shinn "Alright then. Let's continue this all the way into the night."
    shinn "One thing is for sure; they have found their true destiny."
    $ renpy.end_replay()
    $ persistent.touko_aina__gangbang_1 = True

    "END OF TOUKO AND AINA ARC"
    $ pool_gym_available = False
    jump map__school