label rina_special_1:
    if not _in_replay:
        jump end
    "It's after hours, and everyone has cleared out."
    "Nobody is around in school anymore, except for one other person."
    "I slide open the door and enter the classroom."
    "That one remaining person is waiting for me there as I approach her."
    "As I get closer to her, I can feel the sense of tension in the air."
    shinn "Well, have you done what I told you to do?"
    rina "Yes, Master."
    shinn "Just a simple acknowledgement? Have you forgotten how you were taught to greet me?"
    "She responds by kneeling down on the floor like a slave."
    rina "I'm sorry Master. I will not forget again."
    shinn "Heh. Good. Now show me what you've done."
    "Rina stands up and removes her long overcoat."
    "She reveals her slutty body, the one I've used countless times by now."
    "She has a dildo inside her all the time now, keeping my place in her pussy while I'm away."
    "She enjoys it anyway, so why not?"
    "I admire her new nipple and clit piercings. Along with the tattoo she's gotten, they really complete the erotic effect."
    shinn "Heh... looks like you're ready."
    "Rina flushes with the embarrassment of showing me such an indecent body."
    "But at this point, there's nothing she can do about that."
    shinn "Well I think that congratulations are in order Rina. You've made yourself properly ready for the ritual."
    rina "Ritual?"
    shinn "Oh, you didn't know?"
    shinn "Since the beginning, all of your training was just a test to see if you were really fit to be my personal sex slave."
    shinn "By now, you've confirmed for me that your body and your willingness exceed my expectations."
    rina "S-so what do you want me to do?"
    shinn "Oh, it's very simple."
    shinn "First, you will need to masturbate, with your pierced nipples, while you apologize for all disobedience you've ever offered to me and my commands."
    shinn "Next, you will renounce your position as a disciplinary teacher, and any position of authority over others in your life."
    shinn "Finally, you will announce that you are now my personal property and sex slave."
    rina "..."
    shinn "Well? What are you waiting for?"
    rina "I, Rina Akiyama, formally renounce my position as a disciplinary teacher. I promise that I will faithfully serve Master Shinn's dick, and live only to be his sex slave. I live only to listen, obey, and fulfill my Master's desires."
    "While she saying this, she squeezes and fondles her nipples, tugging at her piercings."
    rina "Ahh~"
    "Even as she's just beginning, her arousal is already obvious."
    shinn "Hahaha!"
    shinn "Horny already?"
    rina "Ahh~ Yes Master..."
    shinn "Well... Let's step things up a bit, shall we?"
    "I take out the vibrating dildo's remote control and switch it on, shifting it up to the maximum setting."
    rina "AHH~! "
    shinn "Enjoying it? "
    rina "Yes, Master ~"
    shinn "Well it isn't over yet."
    shinn "As proof that you have renounced your life old life as an independent disciplinary teacher, let me see you piss on that desk that you used to work on."
    rina "Okay~"
    "She complies without hesitation, peeing all over her old desk."
    rina "Hehe. Goodbye, old life."
    rina "Welcome to my new life as sex slave to my Master Shinn~"
    shinn "Fantastic. Let's take a picture to commemorate this ceremony."
    rina "Cheese~"
    "I snap a photo to commemorate the occasion of Rina becoming my officially dedicated sex slave."
    "Now that that's taken care of, the first order of business is fucking my sex slave's pussy."
    "I waste no time and thrust my dick right inside her."
    rina "Ah~ Master~!"
    "As I begin to move, Rina gets even more excited."
    rina "Ah~! Master! Harder please!"
    rina "Fuck me harder! "
    "I start to pound her even faster as I marvel at my sex slave's abilities."
    "Even after keeping a dildo in her pussy 24/7, she still has the energy to fiercely squeeze down on my dick."
    shinn "Heh. What an amazing pussy."
    shinn "Seems like you deserve some of my baby seed."
    rina "Ah~ Yes! Please, Master! Give it to me! Give me more!"
    shinn "Heh. Then let's turn it up a notch, shall we?"
    "I start to flick at her pierced nipples."
    rina "Ahh~ YES!"
    "At this point, she's almost overwhelmed with the pleasure."
    shinn "Feeling good?"
    rina "Yes~! I want to cum! Please, Master, let me cum!"
    shinn "Hahaha..."
    shinn "Sure, but let's cum together, shall we?"
    rina "Yes~ Let's do it together! "
    rina "Let's cum and let our juices mix together! "
    shinn "Hahaha!"
    shinn "I love that slutty talk! Looks like I've trained you well."
    "It won't be long at this rate before I give in to the urge to cum."
    shinn "Alright, it's coming. Are you ready Rina?"
    rina "Yes Master! Let's do it! Let's do it together!"
    shinn "Here it comes!"
    "I approach the end at a violent pace. Each of my thrusts pounds all the way against her innermost depths."
    rina "Ah~ Master's so violent~! I love it!"
    "Before I know it, I'm bursting, letting my cum gush out inside her pussy."
    rina "Ahh~! Master's cum!"
    rina "It's pouring out inside me!"
    "Rina cums instantly as she feels my cum inside her."
    "Her eyes are rolled back and her tongue hanging out in an expression of pure ecstasy."
    "I think all the pleasure just broke her mind. Just as I wanted her."
    rina "Ahh~ More..."
    rina "Please give me more Master....."
    shinn "Don't worry. There's plenty more for my faithful slut. A whole lot more. Your life from now on as my sex slave is going to be filled with pleasure."
    rina "Yes~ Thank you, Master."
    rina "I love you Master Shinn."
    shinn "Heh. Me too, Rina."
    $ renpy.end_replay()