label rina_dog_scene_1:
    $ rina_finale = True
    scene bg hallway 1 with fade
    "A day has passed since our training session on the rooftop."
    "I thought I could parade her around all the students here how much she loves cock now."
    "And what better time than in the morning when everyone is coming in to school? "
    "She was excited, to say the least. After all, she’d completely turned into a sex-crazed bitch by now."
    "I pull the dog leash as I hurry her along beside me."
    "She was crawling like an obedient dog."
    "It didn’t take long for the other students to notice it..."
    female_1 "Wait, what the hell!"
    female_2 "Is that Ms. Rina?"
    male_1 "What the hell is going on?"
    male_2 "Is this for real?"
    "The students in the hallway instantly froze when they saw Rina in such a state."
    "They couldn’t believe their eyes."
    "I could hear whispers spreading through the crowd as they watched her."
    "I could even make out some of their conversations..."
    male_1 "Wow. To think we’d see a disciplinary teacher do something like this..."
    male_2 "I know right? This looks like something straight out of a porn scene."
    "That’s right. Well, it’s possible I got the idea from something like that to begin with."
    "Some of them were openly commenting on her figure."
    male_3 "I knew she was hot and had big tits, but I didn’t expect her to have a figure like that."
    male_4 "Yeah, her boobs are amazing. Makes me want to suck on ‘em."
    shinn "Look around you, Ms Rina. Everyone is looking at you."
    shinn "They love your body and how slutty you’ve become. Everyone is lusting after you now."
    rina "Ah, everyone is looking at me!"
    "Rina lets out a whine as the whole crowd’s attention is focused on her."
    shinn "How does it feel, letting your students see what a slutty bitch you are?"
    rina "Ahhh..."
    rina "Ah! I’m too excited, I can’t take it! I’m gonna cum!"
    "While Rina was working herself up to the point of orgasm, I took a moment to take in the crowd watching us."
    "At the same time, a group of boys was starting to gather around us."
    "Just by the excitement of being watched, Rina came in front of everyone, her pussy juices dripping onto the floor of the school hallway."
    shinn "Wow. You came just like that?"
    rina "Ah, my pussy is so wet right now. I want cocks inside me."
    shinn "You are really a dirty whore, aren’t you?"
    rina "Yes. Rina is a whore who loves cock!"
    shinn "Heheh..."
    shinn "Is there anything you want to say to your beloved students?"
    rina "Y.. Yes..."
    rina "Everyone! Ms. Rina here! I love big cocks! "
    rina "I love the taste and smell of men’s cum. If you have any, please give it to me!"
    "I burst into laughter."
    shinn "Hahahaha... Alright guys. You heard her. She wants your cum."
    male_1 "..."
    male_2 "..."
    male_3 "Oi. Is this for real?"
    shinn "What do you think?"
    male_4 "She looks so sexy..."
    shinn "Then what are you waiting for?"
    male_4 "Will we get in trouble?"
    shinn "Don’t worry. Nothing is going to happen to anyone."
    shinn "She is a willing participant after all."
    shinn "Besides, it’s a once in a lifetime opportunity to do it with a woman with a figure like that, don’t you think?"
    "While the guys were lusting after Rina, the female students interrupted."
    female_2 "This is disgusting."
    female_1 "You know that I looked up to you Ms. Rina?"
    male_4 "Oi, get lost, girls. This has nothing to do with you."
    male_3 "Yeah! Go away before this happens to you!"
    female_1 "..."
    shinn "You heard them. Get lost!"
    "As the girls in the hallway slowly walk away in horror, the male students move in closer towards to Rina."
    "Rina takes a look at the boys who’re now surrounding her."
    rina "Ah, boys! Give me cum! "
    shinn "You heard her. Do it guys!"
    "The boys started to unzip their pants and flash their hardened dicks in front of Rina."
    rina "Ah, cocks! "
    rina "I can smell it! It smells so good!"
    rina "Please! I want more. I want your cum!"
    male_1 "Wow. You are really a slut."
    male_2 "You asked for it!"
    "The boys started to jerk off in front her."
    "Staring at Rina’s luscious body, the virgin boys were unable to hold out for long."
    "After all, they’d probably never seen a naked woman in real life before."
    male_2 "Ms Rina, your body is so hot!"
    male_3 "Yeah, I can’t hold out much longer!"
    rina "Its okay. Just let it all out on me. I’ll savor it all."
    "The boys were at their limit now."
    male_2 "Arh! She’s just too much! I’m cumming!"
    male_1 "Argh! I’m cumming!"
    male_3 "Me too!"
    male_4 "Take it all, Ms Rina!"
    rina "Yes! Give it to me! Give it all to me!"
    "Almost at once, the boys ejaculated, shooting their cum out onto Rina."
    "Her entire body was covered."
    rina "Ah! Cum! It feels so good!"
    shinn "Look at you, Rina. Aren’t you happy getting showered with these boys’ cum?"
    rina "Yes! I’m happy!"
    "I took a quick look at the boys. Clearly, they weren’t done yet."
    "Even after ejaculating, their dicks were still rock hard."
    "The kept staring at Rina, giving off a predatory vibe."
    "Meanwhile, Rina was still far from sated."
    rina "I want more~"
    shinn "Heh. Alright."
    shinn "Hey guys. Do you want have sex with Rina?"
    male_1 "We can?"
    male_2 "Seriously? "
    shinn "Of course."
    male_4 "Hell yeah! This is a dream come true."
    shinn "Alright. Let’s bring this slut to an empty classroom to get started."
    shinn "Also, I take it this is you guys first time, right?"
    male_1 "..."
    male_2 "..."
    male_3 "..."
    male_4 "..."
    thinking "Not a single reply. It has to be, poor guys."
    shinn "It’s alright. I’m gonna teach you how to pleasure her."
    shinn "You guys can all enjoy popping your cherries on this slut."
    shinn "Follow me."

    scene bg classroom with dissolve
    "I gathered all the boys hanging around in the hallway, and brought them here."
    "It was an unused classroom with tables and chairs lying around."
    "I brought Rina to the front of the class so that everyone could see her clearly."
    shinn "Alright boys. I know you can’t wait to get a real piece of the action."
    shinn "But I would like to show you how to tame a bitch like her."
    "I took off my pants and lay down on the floor."
    shinn "Rina. Come here."
    rina "Yes master."
    shinn "Use my cock, Rina."
    rina "Yes, master."
    "Rina crawled over and wasted no time in lowering herself onto my dick in cowgirl position."
    "Rina was facing the room full of boys."
    "As she looked on, she could see the bulges straining at all of their pants."
    rina "Don’t be shy, boys. Let me see your huge throbbing cocks."
    shinn "Heh. You heard her. Let her see ‘em."
    male_3 "O— Okay..."
    "The boys slowly comply and unzip their pants."
    rina "Ah. There we go."
    "The view further excited Rina as she started to bounce her hips up and down on her own."
    shinn "Yeah, that’s the spirit."
    "Rina lifted up her shoulders to show off her beautiful armpits."
    "They were clean-shaven, according to my taste."
    male_2 "Wow, her armpits look amazing..."
    male_1 "Yeah..."
    "Eventually, some of the boys started to jerk off watching the scene I’d provided for them."
    "As for me, I lay and let Rina slam her hips against me, letting off a slapping sound throughout the room."
    rina "Ah! Dick! Dick! It feels so good inside me!"
    "She’s obviously enjoying this."
    "I let her plunge down to penetrate herself on me all the way to her womb, her pussy juice dripping out over me."
    "The wet and slippery sound as she brings herself down on me over and over again is incredibly erotic. So much so that I can’t hold on for much longer."
    "I’m gonna cum, Rina!"
    rina "Yes, cum! Give it to me! Give me all of your cum!"
    "The boys were reaching their limits too."
    male_1 "Me too. This... this is too good!"
    shinn "Let’s all cum together and give Rina a wonderful experience, shall we?"
    male_2 "Hell yeah!"
    rina "Ah~"
    "Her pussy clamped down on me, like she was trying to squeeze the cum from me."
    shinn "Here it comes! "
    rina "Ahh~"
    "In an instant, I shot right into her womb."
    "There was so much, it was impossible for her to contain it all, leaving my creampie spilling from her pussy."
    "At the same time, all the boys came together, shooting out over her body."
    "The covered her hair, her armpits, her belly and her hips."
    "Everywhere you could see, her body was covered in cum."
    "It was enough for the smell of it to fill the whole room."
    rina "Ah! Cum! There’s so much! I love it!"
    "Rina’s mind was addled all over again. And it seems she wasn’t ready to stop here."
    rina "More~ I want more!"
    "With just a glance around the room, I could see that all the boys were staring straight at her creampied pussy."
    "Clearly, the boys weren’t about to stop here either."
    shinn "Heheh..."
    shinn "I see you boys still want more."
    rina "But master, I want more too~"
    shinn "Of course you do. But let me think how the boys should give it to you."
    "It took just a moment to come up with an idea I was sure Rina would love."
    shinn "Alright guys."
    shinn "Why don’t you each take turns cumming in her mouth?"
    shinn "She’ll drink it all down."
    rina "Ah! Master! I get to drink all the boys’ cum?"
    shinn "Yeah, they’ll be your own personal cum buffet. You like that idea, don’t you?"
    rina "Yes master! I love it!"
    "Rina widened her mouth, licking her lips in anticipation."
    rina "Come on, boys, what are you waiting for? Who’s first?"
    male_1 "Me! I’ll go first!"
    male_2 "Me next!"
    "With Rina’s erotic face spurring them on, the boys quickly lined themselves up."
    "The first boy wasted no time inserting himself into her mouth."
    male_1 "Oh my god, her mouth is heaven! "
    rina "Mmm~ Tastes so good!"
    "The in line stood transfixed, watching what was unfolding in front of them."
    "They watched the boy in front with envy and anticipation, jerking themselves off while waiting their turns."
    "Meanwhile, Rina was deepthroating the boy hard, doing her best to suck out the contents of his balls."
    "She wrapped her tongue around his dick, giving off a slurping sound that was audible throughout the room."
    "Though I couldn’t see it from my place on the floor, her face must have been quite a sight to see."
    "As the sucking became more and more intense, the boy was reaching his limit."
    male_1 "Agh, I can’t take any more. I’m gonna cum!"
    "The realization that the boy was about to cum in her mouth got Rina even more excited."
    "And that excitement made her go even faster."
    "With the boy at the very edge, she pulled away for just a moment to speak."
    rina "It’s okay. You can cum inside me. I’ll drink it all!"
    male_1 "Argh! Here it comes!"
    "The cum shot out of his dick directly into Rina’s throat as she took it all down."
    rina "Hmm~ Cum! "
    "The mere taste of cum got her so excited that she couldn’t think about anything else."
    "The boy pulled back as soon as she’d taken everythinghe had."
    "Her eyes were rolled back and her tongue lolled out of her mouth while she panted like a dog."
    rina "Ah~ cum! More! More!"
    shinn "Alright, who’s next?"
    male_2 "Me!"
    shinn "Alright. Go on then!"
    "The cycle repeated again and again. As time went by, I lost count of the number of boys who used her mouth."
    "She took in so much cum that her stomach was left swollen."
    rina "Ah... So much..."
    shinn "Look at you, you look like you’re pregnant."
    rina "..."
    "She’s unable to respond, so full she can barely make herself speak."
    shinn "I think could go without any more food for a few days now."
    shinn "Hahaha..."
    male_1 "We want to taste the real stuff, Shinn!"
    male_2 "Yeah! Give us the real stuff!"
    "The boys were staring at Rina. Even after several ejaculations, they still hadn’t calmed down."
    "It seems the bunch of them won’t be satisfied without a taste of Rina’s pussy."
    "The pussy that’s still clamped down on my dick as she sits on top of me."
    shinn "Alright, relax, guys."
    shinn "Go ahead and use her however you want. You can use her pussy, her ass, however you like it."
    male_3 "R— Really?"
    shinn "Yea? Isn’t this what you guys wanted?"
    male_1 "Fuck yeah! "
    male_2 "Let’s do it!"
    "As the boys got themselves ready, Rina looked thrilled."
    rina "Yes~ More~"
    shinn "It’s going to be a long day for you, Rina."
    $ persistent.rina_dog_scene_1 = True
    $ renpy.end_replay()
    jump rena_finale