label rina_finale:
    scene black with moveinleft
    "???"
    "Since I first started letting other students fuck Rina..."
    "It’s been months, I guess. I’m not sure quite how long."
    "Rina herself has certainly lost all track of time."
    "After all, what does time matter to a meat toilet? "
    "But even if I’ve lost track of the days, that doesn’t mean things have gotten dull."

    scene bg classroom with fade
    "The room was filled with naked and hungry schoolboys."
    "In the middle of the class, strung up and suspended with ropes, is Rina."
    "I tied her up here myself, in this pose which shows off free and easy access to her pussy."
    "I’ve spent quite a while getting her ready for this sort of play."
    "The drugs I’ve been giving her should increase her libido even compared to before. And maybe also make her lactate as a side effect..."
    "This whole setup looks the scene of a BDSM porno."
    "The students here aren’t just any boys. They’re all thugs from the school who had serious beef with Rina from before. As a disciplinary teacher, she’d picked up quite a few of them."
    "So, I thought I’d make a pastime of inviting them to use her. These events have just gotten bigger over time as more and more of them have gotten involved."
    "Rina has completely accepted her fate. You can’t even call her resigned to it, since the very start, she’s been living like she was bown for this."
    "Once a strong-minded person and a respected authority figure, she’s come to embrace being a public meat toilet."
    "It’s quite a thing to see how just one chance encounter can turn someone’s whole life around."
    "I sit at the front of the class, watching Rina while she stares back at all the boys surrounding her."
    rina "Ah... So many... I... want them all..."
    "Her eyes were hazy, surrounded by cock, she could no longer think about anything else."
    "Overcome with anticipation, her pussy was leaking while her body quivered against ropes."
    "Some guys were getting impatient..."
    thug_1 "Oi, Shinn! When can we start!?  "
    shinn "Go ahead. Fuck her till you’re all dry."
    thug_1 "All right!"
    thug_2 "Let’s do it."
    "Everyone clustered in around Rina, fanning her lust even more."
    rina "Ah~ it’s starting!"
    "Before we start the feast, I thought I’d give Rina a little surprise."
    shinn "Hang on guys. Let’s loosen her up a little first."
    "One of the boys has a lit candle ready, and approaches Rina from the back."
    rina "Ah~ What’s this?"
    "Rina has never experienced this type of foreplay before, but she can’t help but anticipate pleasure."
    thug_3 "Take this!"
    "The student dripped the hot melted wax onto Rina’s sensitive breasts."
    "The wax is hot enough to inflict pain, but in her current state, Rina immediately embraces it as pleasure."
    rina "Ah!~ It hurts~"
    "The sensation causes her pussy to twitch a little, with more of her juices trickling outf."
    thug_4 "It’s not over yet!"
    "Another student uses a whip to lash at Rina’s thighs. Again, Rina takes the pain as pleasure."
    rina "Ah! MORE! MORE!"
    "At this point, driven by her pleasure, a spring of milk starts to flow from her breasts."
    "The student with the whip picks up the pace, leaving marks on her legs with each lash."
    rina "GIVE IT TO ME! GIVE IT TO ME!"
    "The combined pleasure of the whip and the hot wax was enough to drive her over the edge."
    rina "Yes! I’M CUMMING. I’M CUMMING AHHHH~~"
    "The pleasure causes a gush of juice from her twitching pussy, and a sudden spurt of milk from her breasts."
    rina "Ah~"
    thug_1 "Woah! Check it out, she’s squirting milk!"
    "Seems like that side effect is for real after all."
    "As the milk continues to drip from her breasts, one student decides to have a taste."
    thug_2 "Let me try it~"
    "The student bites down on Rina’s nipple as he begins to suck."
    rina "Ah~ Not my breast!"
    "He takes his time sucking at her lactating breast."
    "When he finally pulls away, he licks his lips."
    thug_2 "Mmm.... So Rina’s breast milk is sweet."
    "The school gang boss was getting impatient sitting back and watching one of his underlings breastfeed."
    thug_boss "Move away guys! This is a waste of time!"
    "Seems he can’t wait any longer to enjoy her pussy."
    "The gang boss pushes his way through the crowd and immediately thrusts his dick straight inside her, not giving her even a moment to prepare."
    "Rina immediately went wild."
    rina "Ah!!! COCK!"
    "The boys at her side started jumping in, grabbing at her hands and urging her to jerk them off."
    thug_1 "Come on Rina! Use your hands too!"
    rina "Ah~ Okay~"
    "She eagerly goes along with it, vigorously stroking off the boys at her sides."
    "The rest of the boys stand around watching the action, jerking themselves off while waiting for their own turns with her pussy."
    thug_boss "Damn! Her pussy is still this tight even after she’s been used this many times!"
    thug_1 "Eh? Are you kidding me? Her pussy is tight even after everything we’ve put into her!?"
    thug_2 "Hey, lemme check!"
    thug_boss "Heh, wait your turn. Everyone gets to use her eventually."
    thug_1 "Yeah. We can all use her to the fullest!"
    "Amid all this conversation, Rina desire for cocks has reached its peak. She’s panting with her tongue out like a dog, demanding more."
    thug_1 "Haha! Look at her! She’s like a fucking dog!"
    thug_2 "What a slut!"
    "She rocked her hips up and down with as much force as she could while jerking the boys off even faster."
    rina "More! Give it to me! Shoot it all! I want it all!"
    thug_1 "Ahaha! She’s gone mad!"
    "Her hips were moving unstoppably, like a machine. With such forceful movement and her tight pussy, the boss couldn’t last long inside her."
    thug_boss "Alright, since you asked for it!"
    "The boss began pounding her even harder, bouncing her up and down on top of him. Rina moaned out load, urging him on."
    rina "I LOVE IT! GIVE IT TO ME! GIVE ME MORE!!"
    thug_boss "Here you go!"
    "The boss came inside her, the pleasure for both of them reaching a peak."
    "Rina came along with him, shuddering against him, another spurt of milk splashing from her breasts."
    rina "MORE! I WANT MORE!"
    "The boys jerking off around her quickly began to empty their loads as well, splashing their cum across her body, leaving her covered."
    rina "Ugh~ So much cum! ~"
    "Her eyes rolled back with satisfaction. But, it was clear she was still ready for more."
    "Her pussy was twitching as the boss’s cum started to leak out."
    shinn "Good job there."
    thug_boss "Eh, thanks. If it weren’t for you, we’d never have had the chance to enjoy all this."
    shinn "No problem, man."
    "All the guys waiting around her were getting eager to jump in. They couldn’t wait for their own turn at her pussy. Even after cumming once, all of them were still rock-hard."
    "Getting impatient, some of them start trying to force their way to the front."
    thug_4 "My turn!"
    thug_5 "Hey!"
    principal "Hang on."
    "A familiar voice emerge from the back."
    thinking "Wait a minute. That voice..."
    "Everyone is shocked as they realize who it is walking to the front of the classroom."
    thug_2 "No way..."
    thug_1 "It’s the principal!"
    thug_boss "Shit! Are we all screwed?"
    principal "No worries, guys. I’m just here to join in the fun."
    "Of course, this is no surprise to me. I invited the Principal along myself when I found out how eager he was to have a taste of Rina."
    principal "Sorry I’m late, Shinn."
    shinn "No problem.  "
    principal "Looks like you guys have already gotten her basted and ready."
    shinn "Well, not a bad time for you to jump in then, is it?"
    principal "Certainly."
    "Realizing what’s going on, Rina perks up in excitement, recognizing her boss."
    rina "Ah~ The Principal is here! Are you here to have fun with me?!"
    principal "Yes, of course."
    rina "Ah~ I can’t wait! I’m sorry for being such a slutty teacher inside your school."
    principal "Heh. Don’t apologize. I’m here to reward you for your work."
    "The principal unzips his pants and positions himself."
    principal "Time to taste this slutty bitch’s pussy!"
    "The principal violently thrusts in and begins pounding away at her."
    rina "Ah! Principal! Your dick is amazing! I love it!!"
    principal "Ooh! Looks like her pussy is still tight after all this!"
    rina "Give it to me, Principal! Shoot everything inside me. I want the taste of your cum so badly! Please!"
    principal "Not yet. I want to savor this pussy for a while."
    "The principal started moving even faster, sending Rina into a frenzy."
    rina "Yes! More! More!"
    "He kept hammering away at her until he was finally ready to unload."
    principal "Alright, get ready. Make sure you enjoy every single drop of my cum!"
    rina "Yes! The Principal is cumming inside me! I love it! Do it!"
    "With a sudden gush, the Principal came inside her. Rina shuddered, dazed with pleasure."
    "The principal pulled out, letting the flood of cum drip fom her pussy."
    principal "There. All done."
    "The schoolboys looked on in awe at how much he’d cum inside her. And incredible display for a man of his age."
    "Satisfied, the Principal zips up his pants."
    shinn "That’s all? "
    principal "I’ll be back for more later."
    shinn "Alright then. Come back whenever you feel like it, she’ll be here all day."
    "As the principal left, the clamor started up again as the boys fought for a place at the front of the line."
    "I offer some reassurance to calm them down."
    shinn "Don’t worry guys, there’s plenty of time today for everyone to fuck her!"
    "After a few hours, Rina was thoroughly fucked, but still far from finshed."
    "The marks left on her tights counting the rounds she’d been through today were now too numerous to track."
    "She was exhausted, but still eager, happy to be able to fuck her fill. Seems like she’s been enjoying it more than the boys."
    rina "Yes... More... Give me more!"
    shinn "Heh. Good girl."
    "As the others started to filter out of the classroom, thoroughly spent, I walk up to her to look her over in her current state."
    rina "Ah~ Shinn~"
    shinn "Heh..."
    shinn "Did you enjoy yourself today?"
    rina "Yes! I love it!"
    shinn "Then let’s end the day with my cock, shall we?"
    "Rina’s sudden rush of enthusiasm wiped away all the signs of her exhaustion."
    rina "Yes! Nothing beats Shinn’s big fat cock!"
    shinn "Good girl. Looks like you’re still loyal to me after everything."
    "I strip off my pants and expose my cock in front of her. The sight of it makes Rina tremble."
    rina "Ah! Shinn!~"
    shinn "As a reward for your loyalty, I’m going to let you taste it."
    rina "Yes!"
    "Lubed up with all the cum that’s been spilled inside her, I slide it in easily."
    rina "Ah! Shinn’s cock! It’s in!"
    "She squeezes down tight around me in her excitement. Even after all the boys who’ve used her, her body is still eager."
    shinn "Ugh. It really is tight. You’re a one of a kind slut, aren’t you?"
    "As my hips pound against her ass, I can feel my balls getting ready to release my load."
    rina "Ah! Shinn! HARDER! HARDER!"
    "I speed up, pounding even harder against her womb."
    rina "YES! MORE!"

    if persistent.cum == "inside":
        $ renpy.block_rollback()
        jump rina_finale_inside

    elif persistent.cum == "outside":
        $ renpy.block_rollback()
        jump rina_finale_outside

    else:
        menu:
            "Cum inside":
                $ renpy.block_rollback()
                jump rina_finale_inside
            "Cum outside":
                $ renpy.block_rollback()
                jump rina_finale_outside

label rina_finale_inside:
    "Going all out at the end, I finally reached my limit. In an instant, I let everything out!"
    shinn "Ahh!"
    "My cum poured out inside her pussy, enough that some of it splashed to the floor beneath her."
    rina "AH! SHINN! I’M SO HAPPY!"
    "My balls were empty. She’d sucked me dry of cum, like some kind of vampire."
    rina "Ah~ Shinn’s cock is still the best!"
    jump rina_end

label rina_finale_outside:
    "Going all out at the end, I finally reached my limit. In an instant, I pull out, spraying my cum across her body like a fountain."
    rina "Ah!! Shinn’s cum! It’s everywhere!"
    "My balls were empty. She’d sucked me dry of cum, like some kind of vampire."
    jump rina_end

label rina_end:
    "She seems broken again, completely unaware of what’s going on around her."
    "Looking at her right now, I think I can say I’m properly satisfied with my job training her."
    "Looks like my job is done here. As far as what’ll happen to her from now on, I can’t be bothered."
    "It’s not like I have any plans to take responsibility. Hell, I don’t think anyone would want to take responsibility for her now."
    shinn "Good luck, Rina. Have fun with all the boys’ cocks in school."
    rina "Yes~ I will!"
    $ persistent.rina_finale = True
    $ renpy.end_replay()
    scene black with fade
    "End of Rina's arc reached."
    jump map__school