label rina__rooftop_scene_1:
    scene bg rooftop with map_fade
    "It's evening, and the sun has already started to set. I'm still waiting for Rina to show up."
    thinking "Where is she?"
    "Just then, the door creaks open, and a familiar figure emerges behind it. Looks like she's decided to show after all."
    shinn "There you are. What took you so long?"
    rina "Shut up, you piece of shit. You don't need to know."
    "Taking a look at her, it seems like the hold-up might have something to do with how she's dressed. She's wearing a brown trenchcoat which hangs all the way to the floor."
    "She must have walked through the school in that to get here."
    shinn "Heh. Must be pretty embarrassing for you walking around school with nothing but that coat on, huh?"
    rina "Shut the fuck up."
    shinn "Well. I guess it doesn't matter right now. Unbutton it, I want to see that naked body of yours."
    "Flushed with shame and seeming even shyer than before, she strips herself down in front of me once again."
    "Rather than being completely naked, she's left her stockings on."
    shinn "Oh, looking pretty sexy there..."
    rina "..."
    shinn "Ha, I didn't expect you'd go to the trouble of dressing yourself up for me."
    rina "..."
    shinn "I guess you're really looking forward to what I have in store for you."
    rina "Shut up!"
    shinn "So tell me Rina, how do you feel, exposing yourself in the open like this?"
    rina "..."
    "She doesn't reply, and tries to cover herself with her hands while refusing to meet my eye."
    shinn "Good. I like you this way."
    "I made my own preparations before I came here as well. This bag contains a supply of sex toys I can use to train her all night long."
    "Hopefully, by the end of the day, I'll have made her putty in my hands. Just like I used to do in the old days."
    shinn "Now. Get in the doggy position."
    rina "W.. Wh—"
    shinn "You heard me. In the doggy position."
    "Rina was frozen in hesitation."
    shinn "Do you want your phone back or not?"
    "She glares at me with hatred before she complies getting down on her hands and knees."
    
    scene rina_rooftop_1 1 with fade
    shinn "Good girl."
    "Once she's assumed the postion, I walk up to her and lean over, looking her in the face."
    "From my bag, I retrieve a set of pink anal beads, and hold it up in front of her."
    shinn "We had some fun with your pussy before. So now, let's have fun with your ass."
    rina "Wait what?"
    shinn "You heard me."
    rina "No way..."
    "Having informed her of my intentions, I move around behind her to inspect her ass more closely."
    "Taking a close look at it, it seems to be completely unused."
    shinn "Hmm... Any guys ever play with your ass before?"
    rina "What are you on about!"
    shinn "I'm saying, judging by the look of it, it seems untouched. Looks like I'm going to be the first."
    rina "Don't you dare..."
    shinn "Hahaha!"
    "I start to stroke and touch around her back hole."
    rina "Wait, what are you doing?!"
    shinn "Wow, you seem pretty soft back here."
    shinn "Here, let me try out the inside."
    "As I insert my finger, her body immediately reacts."

    scene rina_rooftop_1 2
    rina "No! What are you doing!? Stop!"
    shinn "Wow. Your really is soft inside."
    rina "It hurts! Please!"
    shinn "It hurts, huh? Well, let's see if we can turn that pain to pleasure."
    "I twist my finger around and angle it inside her to target her weak spots."
    rina "Ah~ No~"
    "Rina lets out a little moan."
    shinn "Feeling it already, huh? Looks like your body is built for this."
    rina "Stop it!"
    shinn "A man never puts down what he's doing halfway through!"
    "I increase the pressure a bit more, pushing her to climax from her ass."
    rina "Ah~"
    shinn "What's the matter? Just give in to the pleasure."
    "It's clear that Rina is trying to hold back the feeling as much as she can."
    "So, I increase the intensity on my end to compensate."
    rina "Mm!"
    "At this point, I can see the juices slowly starting to leak from her pussy."
    shinn "See! You're getting this wet already. Just let go, Rina."
    shinn "Indulge in the pleasure! Let it all out!"
    rina "..."
    "She's still being stubborn. So, I decide to work my way further into her ass."
    rina "Ah~"
    "She felt my fingers plunging all the way in."
    rina "No~"
    "I ramp up the intensity in a bid to make her climax."
    shinn "Time to turn it up!"
    rina "Ah~"
    rina "I can't..."
    shinn "You can't? Then let it out. You'll feel better that way."
    "Her legs have started to tremble, and her juices have started dripping down her thighs."
    "It's only a matter of time now."
    rina "Ah~"
    rina "I can't hold it!"
    "Her pussy twitches as her juices start gushing out."

    scene rina_rooftop_1 3 with cum_flash
    "Looks like she finally submitted to the pleasure from her ass."
    "I remove my fingers from her anus."

    scene rina_rooftop_1 4
    "Surprise surprise, her hole is twitching like mad."
    shinn "Good girl, Rina."
    shinn "I told you you'd enjoy it."
    rina "..."
    "Her expression is vacant and hazy from her climax. All the better for me."
    shinn "Well, let's get on to the next play, shall we?"
    "I pick up the set of anal beads I showed off to Rina before."
    
    scene rina_rooftop_1 5
    shinn "Remember these? I think you've gotten enough of a warm-up now."
    rina "..."
    "Rina doesn't respond, but I see a hint of curiosity on her face."
    shinn "Let's get you lubed up first."
    "I run my fingers along her pussy, coating them in her juice, before inserting them back into her ass."
    rina "Ah~"
    "I rub around inside her hole again for a bit to make sure she's ready."

    scene rina_rooftop_1 6
    "Her insides felt loose and steamy hot from her last orgasm."
    "Now that she's ready, I position the first bead at the entrance of her anus."

    scene rina_rooftop_1 7
    "She felt the tip of the sex toy pushing up against her."
    rina "Ah~ No."
    "I slowly push the first bead inside."
    rina "Mmm~"
    "She lets out a little moan, but I don't give her a response this time. Her asshole seems soft and pliant, easy to tease."
    "Without further ado, I switch on the anal bead. The sudden vibration sends a shock of pleasure through her body."
    rina "AHH!"
    "She lets out a wild scream. Sounds like unrestrained pleasure to me."
    shinn "Enjoying it so far?"
    "Her face shows a look of shock. Compared to my finger before, the stimulation from the vibrating bead is far more vigorous."
    rina "No! Please take it out! It's disgusting!"
    shinn "Pfft... Relax,Rina, we're just getting started here."
    "Despite her protestations, I can see more juice leaking from her twitching pussy. She's definitely feeling it."
    shinn "Why lie to yourself Rina? You're enjoying this."
    rina "NO!"
    shinn "Come on. Be honest with yourself. You see how wet you've gotten? Why not come to terms with the slut you are?"
    rina "NO! Please stop!"
    shinn "Heh. Like hell I'm going to stop now."
    "I push my head in close and start to lick her clit. I can feel her body shivering in excitement against me."

    scene rina_rooftop_1 8
    rina "Ah~ No..."
    shinn "See? You like it after all."
    "Using my index and middle finger, I begin to penetrate her pulsing wet pussy. She's so soaking wet inside, it feels like dipping my fingers into a warm pool. She lets out a moan as she feels my fingers thrust inside her."

    scene rina_rooftop_1 9
    rina "Ah~"
    "It was soft, but I could hear it clearly."
    shinn "I gonna make you cum, Rina"
    "I start to work my fingers around inside her, stimulating the walls of her vagina."
    rina "Ah~ No! Stop!"
    "I can tell it's getting to her. Her pussy is streaming with her juices, and her legs have started to quiver again. It seems like she's getting close."
    "Her reactions spur me on, and I start to move my hand even more aggressively."
    rina "NO! PLEASE STOP!"
    "Her legs buck as a sudden splash gushes from her pussy. Her eyes roll back as she shudders with more pleasure than she can take."
    "The convulsions of her orgasm force the beads out from her ass all at once."

    scene rina_rooftop_1 10 with cum_flash
    "The string of anal beads falls to the ground, still vibrating."
    rina "AAAHH!"
    "Her legs were shuddering, and her pussy pulsing wildly, clamping down on my fingers."
    "I guess that means she wants more. I unzip my pants to reveal the cock she'd sucked before."
    shinn "Look at it. You like it right?"
    rina "..."
    "Her asshole was twitching. I guess she wants it there."
    shinn "Looks like want to have some more fun with your ass."
    rina "Wait... No..."
    "Rina looked back with a worried face."
    shinn "No what?"
    rina "Please don't stick it into my ass..."
    shinn "Heh. Why not?"
    rina "It's dirty..."
    shinn "Dirty? Nah. It's okay."
    shinn "I'll clean it up for you with my dick."
    "I set the tip of my cock against her ass."
    rina "No! Please..."
    shinn "Here it comes!"
    "I slowly thrust inside her slippery asshole."
    rina "Mmm~"
    "Once again, Rina lets a little moan slip out."
    "The more we continue, the more her real self is starting to show through."
    "I continue thrusting into her as I feel the walls of her rectum squeezing against me."
    shinn "Man. I didn't your ass would be this tight."
    shinn "It's almost like I'm fucking a real pussy back here."
    rina "No~"
    "I can feel her clamping down on me with every thrust."
    shinn "Heh... Seems like you really want me to cum."
    rina "No~ That's not true. Please take it out!"
    rina "Its disgusting!"
    shinn "Ah! Disgusting?!"
    shinn "Why are you so concerned with what's disgusting?"
    shinn "Look at yourself! Look at how dirty you are!"
    shinn "Out here getting fucked in the ass on the roof of the school."
    shinn "What does that make you? You're nothing but a pig whore!"
    rina "..."
    "The more I mock and shame her, the harder I can feel her clamping down on my dick."
    rina "You're... too... rough..."
    shinn "Too rough?"
    shinn "I don't think so..."
    "I start to rail her ass even harder. She's feeling the pleasure and pain blending together."
    rina "Ahh~"
    shinn "That's right. A whore like you loves it like this."
    "With every insult and bit of dirty talk, I can feel her squeezing down more against me."
    shinn "You really do want me to cum, huh?"
    rina "No..."
    shinn "Stop lying to yourself."
    "I slam my dick into her even harder..."
    rina "..."
    "Rina is left speechless for a moment by the intensity of the feeling."
    "I was getting close to cumming. But, not without letting the little slut know first."
    shinn "Time for an anal creampie!"
    rina "Mmm~"
    "I shot my cum out into her ass."
    rina "Ahh~! Cum!"
    rina "Its flowing into my stomach! I can feel it!"
    "Her entire body was trembling again. I get the impression this is going to be a routine thing for her."
    "In fact, I'm going to make sure of that myself..."
    shinn "That's right. Feel that hot cum inside your stomach."
    shinn "You dirty whore."
    "I took out my dick, letting the jizz I'd shot inside her flow free."
    shinn "Wow. That's a lot."
    shinn "Heheh... I wasn't expecting your ass to squeeze out so much."
    rina "..."
    "I took a look at her eyes. She looks drunk with lust."
    thinking "Seems like she's already half broken..."
    thinking "Time for the final step."
    shinn "Done already? I'm not done yet."
    "My cock was still rock hard."
    shinn "See what I've got ready for you, Rina?"
    rina "..."
    "She looks at my cock with a dreamy expression."
    shinn "If you want my cock, go ahead and beg for it."
    rina "..."
    "For a moment, a look of shock penetrates her haze of lust."
    shinn "Don't play dumb with me. I know you want my cock now. If you want it, show me and beg for it."
    rina "..."
    "I can tell she wants it, but she still resists saying it."
    "I keep pushing her for an answer, trying to force her the rest of the way."
    shinn "Don't want it? Fine. We can end this right now and I can give you your phone back. But, you'll never see my cock again."
    rina "..."
    shinn "So? What's it going to be?"
    rina "Shinn... cock..."
    "She was whispering. I could just make her voice out, but I want to hear her loud and clear."
    shinn "What? You've gotta say it louder, I couldn't hear you."
    "I apply a little more pressure, placing the tip of my cock at the entrance of her pussy."
    thinking "I can tell she's about to give in."
    shinn "Come on... Say the magic words."
    "Feeling the sensation of my cock against her pussy, her control was starting to give way."
    "The more I rub up against her, the more impossible it becomes for her to restrain herself."
    "Her desire for my cock is overriding everything else in her mind."
    thinking "Anytime now..."
    "Just as I predicted, she hold herself back any longer."
    rina "I WANT SHINN'S BIG FAT COCK IN MY SLUTTY PUSSY!"
    "Just what I was waiting for."
    shinn "That's what I wanted to hear."
    "I push inside her without hesitation."
    rina "Ah! Shinn!"
    "The inside of her pussy was amazing. It's so tight, I can feel it squeezing down on me, even soaked with all her orgasms so far."
    "I start to pound her hard, her body reacting to every thrust."
    rina "Yes! More! More!"
    thinking "Looks like I've really done a number on her. I bet she doesn't even know who she is right now."
    rina "Harder, Shinn! HARDER!"
    shinn "You've got it!"
    "I thrust even harder, causing her to tighten around me."
    "I can feel her squeezing down more and more as I pound her insides."
    shinn "Fuck, Rina! Your pussy feels so good!"
    rina "Yes! Love it more, fuck me harder!"
    "It's getting hard to hold myself back now."
    shinn "It's too much, I'm going to cum!"
    rina "YES! SHINN, CUM INSIDE ME! FILL ME UP WITH YOUR THICK BABY MILK!"

    if persistent.cum == "inside":
        thinking "Ugh. Hearing her talk dirty like that, I can't take any more!"
        $ renpy.block_rollback()
        jump rina__rooftop_scene_1_inside

    elif persistent.cum == "outside":
        thinking "Ugh. Hearing her talk dirty like that, I can't take any more!"
        $ renpy.block_rollback()
        jump rina__rooftop_scene_1_outside

    else:
        menu:
            thinking "Ugh. Hearing her talk dirty like that, I can't take any more!"
            "CUM INSIDE":
                $ renpy.block_rollback()
                jump rina__rooftop_scene_1_inside
                
            "CUM OUTSIDE":
                $ renpy.block_rollback()
                jump rina__rooftop_scene_1_outside

label rina__rooftop_scene_1_inside:
    "I fulfill her wish and let out everything I've got into her womb."
    "It was so much that it filled all the way to the brim, trickles leaking out from around my dick."
    rina "Ah! Shinn's baby seeds are inside me!"
    thinking "Eh. Pretty likely she'll get pregnant from this after all."
    "As soon as I'm done, I pull my dick out, sending the cum gushing out from her like a waterfall."
    jump rina__rooftop_scene_1_finish

label rina__rooftop_scene_1_outside:
    "I ignored her plea and pull out quickly. The cum sprays out across her butt covering her entire back."
    rina "Ah! Shinn's cum is everywhere!"
    jump rina__rooftop_scene_1_finish

label rina__rooftop_scene_1_finish:
    "She could no longer hold herself in position, and collapsed to the ground, a shaking mess."
    "I take a look over her, completely broken, paralyzed with pleasure. Seems to me like this lesson was a success."
    rina "Ughh~ Se... Sex..."
    "She was mumbling something incoherent. Maybe she wants more. I stand up and plant my foot on her ass."
    shinn "You are mine now, Rina. Understand? I want you to call me master from now on."
    rina "Ah~ Yes Master!"
    $ renpy.end_replay()
    $ persistent.rina__rooftop_scene_1 = True
    jump rina__dog_scene_1

# *CG TRANSITION*

# Title: Rina Arc – Day 2 –Morning– 7:30 AM
# Location: Haruka Academy, Hallway
# Background CG: As described.

label rina__dog_scene_1:
    "A day has passed since our training session on the rooftop."
    "I thought I could parade her around all the students here how much she loves cock now."
    "And what better time than in the morning when everyone is coming in to school?"
    "She was excited, to say the least. After all, she'd completely turned into a sex-crazed bitch by now."
    "I pull the dog leash as I hurry her along beside me."
    "She was crawling like an obedient dog."
    "It didn't take long for the other students to notice it..."
    female_1 "Wait, what the hell!"
    female_2 "Is that Ms. Rina?"
    male_1 "What the hell is going on?"
    male_2 "Is this for real?"
    "The students in the hallway instantly froze when they saw Rina in such a state."
    "They couldn't believe their eyes."
    "I could hear whispers spreading through the crowd as they watched her."
    "I could even make out some of their conversations..."
    male_1 "Wow. To think we'd see a disciplinary teacher do something like this..."
    male_2 "I know right? This looks like something straight out of a porn scene."
    "That's right. Well, it's possible I got the idea from something like that to begin with."
    "Some of them were openly commenting on her figure."
    male_3 "I knew she was hot and had big tits, but I didn't expect her to have a figure like that."
    male_4 "Yeah, her boobs are amazing. Makes me want to suck on ‘em."
    shinn "Look around you, Ms Rina. Everyone is looking at you."
    shinn "They love your body and how slutty you've become. Everyone is lusting after you now."
    rina "Ah, everyone is looking at me!"
    "Rina lets out a whine as the whole crowd's attention is focused on her."
    shinn "How does it feel, letting your students see what a slutty bitch you are?"
    rina "Ahhh..."
    rina "Ah! I'm too excited, I can't take it! I'm gonna cum!"
    "While Rina was working herself up to the point of orgasm, I took a moment to take in the crowd watching us."
    "At the same time, a group of boys was starting to gather around us."
    "Just by the excitement of being watched, Rina came in front of everyone, her pussy juices dripping onto the floor of the school hallway."
    shinn "Wow. You came just like that?"
    rina "Ah, my pussy is so wet right now. I want cocks inside me."
    shinn "You are really a dirty whore, aren't you?"
    rina "Yes. Rina is a whore who loves cock!"
    shinn "Heheh..."
    shinn "Is there anything you want to say to your beloved students?"
    rina "Y.. Yes..."
    rina "Everyone! Ms. Rina here! I love big cocks!"
    rina "I love the taste and smell of men's cum. If you have any, please give it to me!"
    "I burst into laughter."
    shinn "Hahahaha... Alright guys. You heard her. She wants your cum."
    male_1 "..."
    male_2 "..."
    male_3 "Oi. Is this for real?"
    shinn "What do you think?"
    male_4 "She looks so sexy..."
    shinn "Then what are you waiting for?"
    male_4 "Will we get in trouble?"
    shinn "Don't worry. Nothing is going to happen to anyone."
    shinn "She is a willing participant after all."
    shinn "Besides, it's a once in a lifetime opportunity to do it with a woman with a figure like that, don't you think?"
    "While the guys were lusting after Rina, the female students interrupted."
    female_2 "This is disgusting."
    female_1 "You know that I looked up to you Ms. Rina?"
    male_4 "Oi, get lost, girls. This has nothing to do with you."
    male_3 "Yeah! Go away before this happens to you!"
    female_1 "..."
    shinn "You heard them. Get lost!"
    "As the girls in the hallway slowly walk away in horror, the male students move in closer towards to Rina."
    "Rina takes a look at the boys who're now surrounding her."
    rina "Ah, boys! Give me cum!"
    shinn "You heard her. Do it guys!"
    "The boys started to unzip their pants and flash their hardened dicks in front of Rina."
    rina "Ah, cocks!"
    rina "I can smell it! It smells so good!"
    rina "Please! I want more. I want your cum!"
    male_1 "Wow. You are really a slut."
    male_2 "You asked for it!"
    "The boys started to jerk off in front her."
    "Staring at Rina's luscious body, the virgin boys were unable to hold out for long."
    "After all, they'd probably never seen a naked woman in real life before."
    male_2 "Ms Rina, your body is so hot!"
    male_3 "Yeah, I can't hold out much longer!"
    rina "Its okay. Just let it all out on me. I'll savor it all."
    "The boys were at their limit now."
    male_2 "Arh! She's just too much! I'm cumming!"
    male_1 "Argh! I'm cumming!"
    male_3 "Me too!"
    male_4 "Take it all, Ms Rina!"
    rina "Yes! Give it to me! Give it all to me!"
    "Almost at once, the boys ejaculated, shooting their cum out onto Rina."
    "Her entire body was covered."
    rina "Ah! Cum! It feels so good!"
    shinn "Look at you, Rina. Aren't you happy getting showered with these boys' cum?"
    rina "Yes! I'm happy!"
    "I took a quick look at the boys. Clearly, they weren't done yet."
    "Even after ejaculating, their dicks were still rock hard."
    "The kept staring at Rina, giving off a predatory vibe."
    "Meanwhile, Rina was still far from sated."
    rina "I want more~"
    shinn "Heh. Alright."
    shinn "Hey guys. Do you want have sex with Rina?"
    male_1 "We can?"
    male_2 "Seriously?"
    shinn "Of course."
    male_4 "Hell yeah! This is a dream come true."
    shinn "Alright. Let's bring this slut to an empty classroom to get started."
    shinn "Also, I take it this is you guys first time, right?"
    male_students "..."
    thinking "Not a single reply. It has to be, poor guys."
    shinn "It's alright. I'm gonna teach you how to pleasure her."
    shinn "You guys can all enjoy popping your cherries on this slut."
    shinn "Follow me."

# *CG TRANSITION*

# Title: Rina Arc – Day 2 –Morning– 7:30 AM
# Location: Haruka Academy, Some random class.
# Background CG: As described.

    "I gathered all the boys hanging around in the hallway, and brought them here."
    "It was an unused classroom with tables and chairs lying around."
    "I brought Rina to the front of the class so that everyone could see her clearly."
    shinn "Alright boys. I know you can't wait to get a real piece of the action."
    shinn "But I would like to show you how to tame a bitch like her."
    "I took off my pants and lay down on the floor."
    shinn "Rina. Come here."
    rina "Yes master."
    shinn "Use my cock, Rina."
    rina "Yes, master."
    "Rina crawled over and wasted no time in lowering herself onto my dick in cowgirl position."
    "Rina was facing the room full of boys."
    "As she looked on, she could see the bulges straining at all of their pants."
    rina "Don't be shy, boys. Let me see your huge throbbing cocks."
    shinn "Heh. You heard her. Let her see ‘em."
    male_3 "O— Okay..."
    "The boys slowly comply and unzip their pants."
    rina "Ah. There we go."
    "The view further excited Rina as she started to bounce her hips up and down on her own."
    shinn "Yeah, that's the spirit."
    "Rina lifted up her shoulders to show off her beautiful armpits."
    "They were clean-shaven, according to my taste."
    male_2 "Wow, her armpits look amazing..."
    male_1 "Yeah..."
    "Eventually, some of the boys started to jerk off watching the scene I'd provided for them."
    "As for me, I lay and let Rina slam her hips against me, letting off a slapping sound throughout the room."
    rina "Ah! Dick! Dick! It feels so good inside me!"
    "She's obviously enjoying this."
    "I let her plunge down to penetrate herself on me all the way to her womb, her pussy juice dripping out over me."
    "The wet and slippery sound as she brings herself down on me over and over again is incredibly erotic. So much so that I can't hold on for much longer."
    "I'm gonna cum, Rina!"
    rina "Yes, cum! Give it to me! Give me all of your cum!"
    "The boys were reaching their limits too."
    male_1 "Me too. This... this is too good!"
    shinn "Let's all cum together and give Rina a wonderful experience, shall we?"
    male_2 "Hell yeah!"
    rina "Ah~"
    "Her pussy clamped down on me, like she was trying to squeeze the cum from me."
    shinn "Here it comes!"
    rina "Ahh~"
    "In an instant, I shot right into her womb."
    "There was so much, it was impossible for her to contain it all, leaving my creampie spilling from her pussy."
    "At the same time, all the boys came together, shooting out over her body."
    "The covered her hair, her armpits, her belly and her hips."
    "Everywhere you could see, her body was covered in cum."
    "It was enough for the smell of it to fill the whole room."
    rina "Ah! Cum! There's so much! I love it!"
    "Rina's mind was addled all over again. And it seems she wasn't ready to stop here."
    rina "More~ I want more!"
    "With just a glance around the room, I could see that all the boys were staring straight at her creampied pussy."
    "Clearly, the boys weren't about to stop here either."
    shinn "Heheh..."
    shinn "I see you boys still want more."
    rina "But master, I want more too~"
    shinn "Of course you do. But let me think how the boys should give it to you."
    "It took just a moment to come up with an idea I was sure Rina would love."
    shinn "Alright guys."
    shinn "Why don't you each take turns cumming in her mouth?"
    shinn "She'll drink it all down."
    rina "Ah! Master! I get to drink all the boys' cum?"
    shinn "Yeah, they'll be your own personal cum buffet. You like that idea, don't you?"
    rina "Yes master! I love it!"
    "Rina widened her mouth, licking her lips in anticipation."
    rina "Come on, boys, what are you waiting for? Who's first?"
    male_1 "Me! I'll go first!"
    male_2 "Me next!"
    "With Rina's erotic face spurring them on, the boys quickly lined themselves up."
    "The first boy wasted no time inserting himself into her mouth."
    male_1 "Oh my god, her mouth is heaven!"
    rina "Mmm~ Tastes so good!"
    "The in line stood transfixed, watching what was unfolding in front of them."
    "They watched the boy in front with envy and anticipation, jerking themselves off while waiting their turns."
    "Meanwhile, Rina was deepthroating the boy hard, doing her best to suck out the contents of his balls."
    "She wrapped her tongue around his dick, giving off a slurping sound that was audible throughout the room."
    "Though I couldn't see it from my place on the floor, her face must have been quite a sight to see."
    "As the sucking became more and more intense, the boy was reaching his limit."
    male_1 "Agh, I can't take any more. I'm gonna cum!"
    "The realization that the boy was about to cum in her mouth got Rina even more excited."
    "And that excitement made her go even faster."
    "With the boy at the very edge, she pulled away for just a moment to speak."
    rina "It's okay. You can cum inside me. I'll drink it all!"
    male_1 "Argh! Here it comes!"
    "The cum shot out of his dick directly into Rina's throat as she took it all down."
    rina "Hmm~ Cum!"
    "The mere taste of cum got her so excited that she couldn't think about anything else."
    "The boy pulled back as soon as she'd taken everythinghe had."
    "Her eyes were rolled back and her tongue lolled out of her mouth while she panted like a dog."
    rina "Ah~ cum! More! More!"
    shinn "Alright, who's next?"
    male_2 "Me!"
    shinn "Alright. Go on then!"
    "The cycle repeated again and again. As time went by, I lost count of the number of boys who used her mouth."
    "She took in so much cum that her stomach was left swollen."
    rina "Ah... So much..."
    shinn "Look at you, you look like you're pregnant."
    rina "..."
    "She's unable to respond, so full she can barely make herself speak."
    shinn "I think could go without any more food for a few days now."
    shinn "Hahaha..."
    male_1 "We want to taste the real stuff, Shinn!"
    male_2 "Yeah! Give us the real stuff!"
    "The boys were staring at Rina. Even after several ejaculations, they still hadn't calmed down."
    "It seems the bunch of them won't be satisfied without a taste of Rina's pussy."
    "The pussy that's still clamped down on my dick as she sits on top of me."
    shinn "Alright, relax, guys."
    shinn "Go ahead and use her however you want. You can use her pussy, her ass, however you like it."
    male_3 "R— Really?"
    shinn "Yea? Isn't this what you guys wanted?"
    male_1 "Fuck yeah!"
    male_2 "Let's do it!"
    "As the boys got themselves ready, Rina looked thrilled."
    rina "Yes~ More~"
    shinn "It's going to be a long day for you, Rina."
    $ renpy.end_replay()
    $ persistent.rina__dog_scene_1 = True
    jump rina__unknown

label rina__unknown:
    scene black with fade
    "???"
    "Since I first started letting other students fuck Rina..."
    "It's been months, I guess. I'm not sure quite how long."
    "Rina herself has certainly lost all track of time."
    "After all, what does time matter to a meat toilet?"
    "But even if I've lost track of the days, that doesn't mean things have gotten dull."
    jump rina__thugs_scene_1

# *CG TRANSITION*

# Title: Rina Arc – Day 225 – Evening
# Location: Classroom
# Background CG: A typical classroom with a blackboard. Chairs and desks stand in single-file rows.

label rina__thugs_scene_1:
    "The room was filled with naked and hungry schoolboys."
    "In the middle of the class, strung up and suspended with ropes, is Rina."
    "I tied her up here myself, in this pose which shows off free and easy access to her pussy."
    "I've spent quite a while getting her ready for this sort of play."
    "The drugs I've been giving her should increase her libido even compared to before. And maybe also make her lactate as a side effect..."
    "This whole setup looks the scene of a BDSM porno."
    "The students here aren't just any boys. They're all thugs from the school who had serious beef with Rina from before. As a disciplinary teacher, she'd picked up quite a few of them."
    "So, I thought I'd make a pastime of inviting them to use her. These events have just gotten bigger over time as more and more of them have gotten involved."
    "Rina has completely accepted her fate. You can't even call her resigned to it, since the very start, she's been living like she was bown for this."
    "Once a strong-minded person and a respected authority figure, she's come to embrace being a public meat toilet."
    "It's quite a thing to see how just one chance encounter can turn someone's whole life around."
    "I sit at the front of the class, watching Rina while she stares back at all the boys surrounding her."
    rina "Ah... So many... I... want them all..."
    "Her eyes were hazy, surrounded by cock, she could no longer think about anything else."
    "Overcome with anticipation, her pussy was leaking while her body quivered against ropes."
    "Some guys were getting impatient..."
    thug_1 "Oi, Shinn! When can we start!?"
    shinn "Go ahead. Fuck her till you're all dry."
    thug_1 "All right!"
    thug_2 "Let's do it."
    "Everyone clustered in around Rina, fanning her lust even more."
    rina "Ah~ it's starting!"
    "Before we start the feast, I thought I'd give Rina a little surprise."
    shinn "Hang on guys. Let's loosen her up a little first."
    "One of the boys has a lit candle ready, and approaches Rina from the back."
    rina "Ah~ What's this?"
    "Rina has never experienced this type of foreplay before, but she can't help but anticipate pleasure."
    thug_3 "Take this!"
    "The student dripped the hot melted wax onto Rina's sensitive breasts."
    "The wax is hot enough to inflict pain, but in her current state, Rina immediately embraces it as pleasure."
    rina "Ah!~ It hurts~"
    "The sensation causes her pussy to twitch a little, with more of her juices trickling outf."
    thug_4 "It's not over yet!"
    "Another student uses a whip to lash at Rina's thighs. Again, Rina takes the pain as pleasure."
    rina "Ah! MORE! MORE!"
    "At this point, driven by her pleasure, a spring of milk starts to flow from her breasts."
    "The student with the whip picks up the pace, leaving marks on her legs with each lash."
    rina "GIVE IT TO ME! GIVE IT TO ME!"
    "The combined pleasure of the whip and the hot wax was enough to drive her over the edge."
    rina "Yes! I'M CUMMING. I'M CUMMING AHHHH~~"
    "The pleasure causes a gush of juice from her twitching pussy, and a sudden spurt of milk from her breasts."
    rina "Ah~"
    thug_1 "Woah! Check it out, she's squirting milk!"
    "Seems like that side effect is for real after all."
    "As the milk continues to drip from her breasts, one student decides to have a taste."
    thug_2 "Let me try it~"
    "The student bites down on Rina's nipple as he begins to suck."
    rina "Ah~ Not my breast!"
    "He takes his time sucking at her lactating breast."
    "When he finally pulls away, he licks his lips."
    thug_2 "Mmm.... So Rina's breast milk is sweet."
    "The school gang boss was getting impatient sitting back and watching one of his underlings breastfeed."
    thug_boss "Move away guys! This is a waste of time!"
    "Seems he can't wait any longer to enjoy her pussy."
    "The gang boss pushes his way through the crowd and immediately thrusts his dick straight inside her, not giving her even a moment to prepare."
    "Rina immediately went wild."
    rina "Ah!!! COCK!"
    "The boys at her side started jumping in, grabbing at her hands and urging her to jerk them off."
    thug_1 "Come on Rina! Use your hands too!"
    rina "Ah~ Okay~"
    "She eagerly goes along with it, vigorously stroking off the boys at her sides."
    "The rest of the boys stand around watching the action, jerking themselves off while waiting for their own turns with her pussy."
    thug_boss "Damn! Her pussy is still this tight even after she's been used this many times!"
    thug_1 "Eh? Are you kidding me? Her pussy is tight even after everything we've put into her!?"
    thug_2 "Hey, lemme check!"
    thug_boss "Heh, wait your turn. Everyone gets to use her eventually."
    thug_1 "Yeah. We can all use her to the fullest!"
    "Amid all this conversation, Rina desire for cocks has reached its peak. She's panting with her tongue out like a dog, demanding more."
    thug_1 "Haha! Look at her! She's like a fucking dog!"
    thug_2 "What a slut!"
    "She rocked her hips up and down with as much force as she could while jerking the boys off even faster."
    rina "More! Give it to me! Shoot it all! I want it all!"
    thug_1 "Ahaha! She's gone mad!"
    "Her hips were moving unstoppably, like a machine. With such forceful movement and her tight pussy, the boss couldn't last long inside her."
    thug_boss "Alright, since you asked for it!"
    "The boss began pounding her even harder, bouncing her up and down on top of him. Rina moaned out load, urging him on."
    rina "I LOVE IT! GIVE IT TO ME! GIVE ME MORE!!"
    thug_boss "Here you go!"
    "The boss came inside her, the pleasure for both of them reaching a peak."
    "Rina came along with him, shuddering against him, another spurt of milk splashing from her breasts."
    rina "MORE! I WANT MORE!"
    "The boys jerking off around her quickly began to empty their loads as well, splashing their cum across her body, leaving her covered."
    rina "Ugh~ So much cum! ~"
    "Her eyes rolled back with satisfaction. But, it was clear she was still ready for more."
    "Her pussy was twitching as the boss's cum started to leak out."
    shinn "Good job there."
    thug_boss "Eh, thanks. If it weren't for you, we'd never have had the chance to enjoy all this."
    shinn "No problem, man."
    "All the guys waiting around her were getting eager to jump in. They couldn't wait for their own turn at her pussy. Even after cumming once, all of them were still rock-hard."
    "Getting impatient, some of them start trying to force their way to the front."
    thug_4 "My turn!"
    thug_5 "Hey!"
    principal "Hang on."
    "A familiar voice emerge from the back."
    thinking "Wait a minute. That voice..."
    "Everyone is shocked as they realize who it is walking to the front of the classroom."
    thug_2 "No way..."
    thug_1 "It's the principal!"
    thug_boss "Shit! Are we all screwed?"
    principal "No worries, guys. I'm just here to join in the fun."
    "Of course, this is no surprise to me. I invited the Principal along myself when I found out how eager he was to have a taste of Rina."
    principal "Sorry I'm late, Shinn."
    shinn "No problem."
    principal "Looks like you guys have already gotten her basted and ready."
    shinn "Well, not a bad time for you to jump in then, is it?"
    principal "Certainly."
    "Realizing what's going on, Rina perks up in excitement, recognizing her boss."
    rina "Ah~ The Principal is here! Are you here to have fun with me?!"
    principal "Yes, of course."
    rina "Ah~ I can't wait! I'm sorry for being such a slutty teacher inside your school."
    principal "Heh. Don't apologize. I'm here to reward you for your work."
    "The principal unzips his pants and positions himself."
    principal "Time to taste this slutty bitch's pussy!"
    "The principal violently thrusts in and begins pounding away at her."
    rina "Ah! Principal! Your dick is amazing! I love it!!"
    principal "Ooh! Looks like her pussy is still tight after all this!"
    rina "Give it to me, Principal! Shoot everything inside me. I want the taste of your cum so badly! Please!"
    principal "Not yet. I want to savor this pussy for a while."
    "The principal started moving even faster, sending Rina into a frenzy."
    rina "Yes! More! More!"
    "He kept hammering away at her until he was finally ready to unload."
    principal "Alright, get ready. Make sure you enjoy every single drop of my cum!"
    rina "Yes! The Principal is cumming inside me! I love it! Do it!"
    "With a sudden gush, the Principal came inside her. Rina shuddered, dazed with pleasure."
    "The principal pulled out, letting the flood of cum drip fom her pussy."
    principal "There. All done."
    "The schoolboys looked on in awe at how much he'd cum inside her. And incredible display for a man of his age."
    "Satisfied, the Principal zips up his pants."
    shinn "That's all?"
    principal "I'll be back for more later."
    shinn "Alright then. Come back whenever you feel like it, she'll be here all day."
    "As the principal left, the clamor started up again as the boys fought for a place at the front of the line."
    "I offer some reassurance to calm them down."
    shinn "Don't worry guys, there's plenty of time today for everyone to fuck her!"
    "After a few hours, Rina was thoroughly fucked, but still far from finshed."
    "The marks left on her tights counting the rounds she'd been through today were now too numerous to track."
    "She was exhausted, but still eager, happy to be able to fuck her fill. Seems like she's been enjoying it more than the boys."
    rina "Yes... More... Give me more!"
    shinn "Heh. Good girl."
    "As the others started to filter out of the classroom, thoroughly spent, I walk up to her to look her over in her current state."
    rina "Ah~ Shinn~"
    shinn "Heh..."
    shinn "Did you enjoy yourself today?"
    rina "Yes! I love it!"
    shinn "Then let's end the day with my cock, shall we?"
    "Rina's sudden rush of enthusiasm wiped away all the signs of her exhaustion."
    rina "Yes! Nothing beats Shinn's big fat cock!"
    shinn "Good girl. Looks like you're still loyal to me after everything."
    "I strip off my pants and expose my cock in front of her. The sight of it makes Rina tremble."
    rina "Ah! Shinn!~"
    shinn "As a reward for your loyalty, I'm going to let you taste it."
    rina "Yes!"
    "Lubed up with all the cum that's been spilled inside her, I slide it in easily."
    rina "Ah! Shinn's cock! It's in!"
    "She squeezes down tight around me in her excitement. Even after all the boys who've used her, her body is still eager."
    shinn "Ugh. It really is tight. You're a one of a kind slut, aren't you?"
    "As my hips pound against her ass, I can feel my balls getting ready to release my load."
    rina "Ah! Shinn! HARDER! HARDER!"
    "I speed up, pounding even harder against her womb."

    if persistent.cum == "inside":
        rina "YES! MORE!"
        $ renpy.block_rollback()
        jump rina__thugs_scene_1_inside

    elif persistent.cum == "outside":
        rina "YES! MORE!"
        $ renpy.block_rollback()
        jump rina__thugs_scene_1_outside

    else:
        menu:
            rina "YES! MORE!"
            "CUM INSIDE":
                $ renpy.block_rollback()
                jump rina__thugs_scene_1_inside
                
            "CUM OUTSIDE":
                $ renpy.block_rollback()
                jump rina__thugs_scene_1_outside

label rina__thugs_scene_1_inside:
    "Going all out at the end, I finally reached my limit. In an instant, I let everything out!"
    shinn "Ahh!"
    "My cum poured out inside her pussy, enough that some of it splashed to the floor beneath her."
    rina "AH! SHINN! I'M SO HAPPY!"
    jump rina__thugs_scene_1_end

label rina__thugs_scene_1_outside:
    rina "Ah~ Shinn's cock is still the best!"
    "Going all out at the end, I finally reached my limit. In an instant, I pull out, spraying my cum across her body like a fountain."
    rina "Ah!! Shinn's cum! It's everywhere!"
    jump rina__thugs_scene_1_end

label rina__thugs_scene_1_end:
    "My balls were empty. She'd sucked me dry of cum, like some kind of vampire."
    "She seems broken again, completely unaware of what's going on around her."
    "Looking at her right now, I think I can say I'm properly satisfied with my job training her."
    "Looks like my job is done here. As far as what'll happen to her from now on, I can't be bothered."
    "It's not like I have any plans to take responsibility. Hell, I don't think anyone would want to take responsibility for her now."
    shinn "Good luck, Rina. Have fun with all the boys' cocks in school."
    rina "Yes~ I will!"
    $ renpy.end_replay()
    $ persistent.rina__thugs_scene_1 = True
    "END OF RINA ARC"
    $ staffroom_available = False
    jump map__school