label rina_rooftop_scene_1:
    $ rina_students = True
    scene bg rooftop with pixellate
    "It's evening, and the sun has already started to set. I’m still waiting for Rina to show up."
    thinking "Where is she?"
    "Just then, the door creaks open, and a familiar figure emerges behind it. Looks like she’s decided to show after all."
    shinn "There you are. What took you so long?"
    rina "Shut up, you piece of shit. You don’t need to know."
    "Taking a look at her, it seems like the hold-up might have something to do with how she’s dressed. She’s wearing a brown trenchcoat which hangs all the way to the floor."
    "She must have walked through the school in that to get here."
    shinn "Heh. Must be pretty embarrassing for you walking around school with nothing but that coat on, huh?"
    rina "Shut the fuck up."
    shinn "Well. I guess it doesn’t matter right now. Unbutton it, I want to see that naked body of yours."
    "Flushed with shame and seeming even shyer than before, she strips herself down in front of me once again."
    "Rather than being completely naked, she’s left her stockings on."
    shinn "Oh, looking pretty sexy there..."
    rina "..."
    shinn "Ha, I didn’t expect you’d go to the trouble of dressing yourself up for me."
    rina "..."
    shinn "I guess you’re really looking forward to what I have in store for you."
    rina "Shut up!"
    shinn "So tell me Rina, how do you feel, exposing yourself in the open like this?"
    rina "..."
    "She doesn’t reply, and tries to cover herself with her hands while refusing to meet my eye."
    shinn "Good. I like you this way."
    "I made my own preparations before I came here as well. This bag contains a supply of sex toys I can use to train her all night long."
    "Hopefully, by the end of the day, I’ll have made her putty in my hands. Just like I used to do in the old days."
    shinn "Now. Get in the doggy position."
    rina "W.. Wh—"
    shinn "You heard me. In the doggy position."
    "Rina was frozen in hesitation."
    shinn "Do you want your phone back or not?"
    "She glares at me with hatred before she complies getting down on her hands and knees."
    shinn "Good girl."
    "Once she’s assumed the postion, I walk up to her and lean over, looking her in the face."
    "From my bag, I retrieve a set of pink anal beads, and hold it up in front of her."
    shinn "We had some fun with your pussy before. So now, let’s have fun with your ass."
    rina "Wait what?"
    shinn "You heard me."
    rina "No way..."
    "Having informed her of my intentions, I move around behind her to inspect her ass more closely."
    "Taking a close look at it, it seems to be completely unused."
    shinn "Hmm... Any guys ever play with your ass before?"
    rina "What are you on about!"
    shinn "I’m saying, judging by the look of it, it seems untouched. Looks like I’m going to be the first."
    rina "Don’t you dare..."
    shinn "Hahaha! "
    "I start to stroke and touch around her back hole."
    rina "Wait, what are you doing?!"
    shinn "Wow, you seem pretty soft back here."
    shinn "Here, let me try out the inside."
    "As I insert my finger, her body immediately reacts."
    rina "No! What are you doing!? Stop!"
    shinn "Wow. Your really is soft inside."
    rina "It hurts! Please!"
    shinn "It hurts, huh? Well, let’s see if we can turn that pain to pleasure."
    "I twist my finger around and angle it inside her to target her weak spots."
    rina "Ah~ No~"
    "Rina lets out a little moan."
    shinn "Feeling it already, huh? Looks like your body is built for this."
    rina "Stop it!"
    shinn "A man never puts down what he’s doing halfway through!"
    "I increase the pressure a bit more, pushing her to climax from her ass."
    rina "Ah~ "
    shinn "What’s the matter? Just give in to the pleasure."
    "It’s clear that Rina is trying to hold back the feeling as much as she can."
    "So, I increase the intensity on my end to compensate."
    rina "Mm!"
    "At this point, I can see the juices slowly starting to leak from her pussy."
    shinn "See! You’re getting this wet already. Just let go, Rina."
    shinn "Indulge in the pleasure! Let it all out!"
    rina "..."
    "She’s still being stubborn. So, I decide to work my way further into her ass."
    rina "Ah~"
    "She felt my fingers plunging all the way in."
    rina "No~"
    "I ramp up the intensity in a bid to make her climax."
    shinn "Time to turn it up!"
    rina "Ah~"
    rina "I can’t..."
    shinn "You can’t? Then let it out. You’ll feel better that way."
    "Her legs have started to tremble, and her juices have started dripping down her thighs."
    "It’s only a matter of time now."
    rina "Ah~"
    rina "I can’t hold it!"
    "Her pussy twitches as her juices start gushing out."
    "Looks like she finally submitted to the pleasure from her ass."
    "I remove my fingers from her anus."
    "Surprise surprise, her hole is twitching like mad."
    shinn "Good girl, Rina."
    shinn "I told you you’d enjoy it."
    rina "..."
    "Her expression is vacant and hazy from her climax. All the better for me."
    shinn "Well, let’s get on to the next play, shall we?"
    "I pick up the set of anal beads I showed off to Rina before."
    shinn "Remember these? I think you’ve gotten enough of a warm-up now."
    rina "..."
    "Rina doesn’t respond, but I see a hint of curiosity on her face."
    shinn "Let’s get you lubed up first."
    "I run my fingers along her pussy, coating them in her juice, before inserting them back into her ass."
    rina "Ah~ "
    "I rub around inside her hole again for a bit to make sure she’s ready."
    "Her insides felt loose and steamy hot from her last orgasm."
    "Now that she’s ready, I position the first bead at the entrance of her anus."
    "She felt the tip of the sex toy pushing up against her."
    rina "Ah~ No."
    "I slowly push the first bead inside."
    rina "Mmm~"
    "She lets out a little moan, but I don’t give her a response this time. Her asshole seems soft and pliant, easy to tease."
    "Without further ado, I switch on the anal bead. The sudden vibration sends a shock of pleasure through her body."
    rina "AHH! "
    "She lets out a wild scream. Sounds like unrestrained pleasure to me."
    shinn "Enjoying it so far?"
    "Her face shows a look of shock. Compared to my finger before, the stimulation from the vibrating bead is far more vigorous."
    rina "No! Please take it out! It’s disgusting!"
    shinn "Pfft... Relax,Rina, we’re just getting started here."
    "Despite her protestations, I can see more juice leaking from her twitching pussy. She’s definitely feeling it."
    shinn "Why lie to yourself Rina? You’re enjoying this."
    rina "NO!"
    shinn "Come on. Be honest with yourself. You see how wet you’ve gotten? Why not come to terms with the slut you are?"
    rina "NO! Please stop!"
    shinn "Heh. Like hell I’m going to stop now."
    "I push my head in close and start to lick her clit. I can feel her body shivering in excitement against me."
    rina "Ah~ No..."
    shinn "See? You like it after all."
    "Using my index and middle finger, I begin to penetrate her pulsing wet pussy. She’s so soaking wet inside, it feels like dipping my fingers into a warm pool. She lets out a moan as she feels my fingers thrust inside her."
    rina "Ah~"
    "It was soft, but I could hear it clearly."
    shinn "I gonna make you cum, Rina"
    "I start to work my fingers around inside her, stimulating the walls of her vagina."
    rina "Ah~ No! Stop!"
    "I can tell it’s getting to her. Her pussy is streaming with her juices, and her legs have started to quiver again. It seems like she’s getting close."
    "Her reactions spur me on, and I start to move my hand even more aggressively."
    rina "NO! PLEASE STOP!"
    "Her legs buck as a sudden splash gushes from her pussy. Her eyes roll back as she shudders with more pleasure than she can take."
    "The convulsions of her orgasm force the beads out from her ass all at once.  "
    "The string of anal beads falls to the ground, still vibrating."
    rina "AAAHH!"
    "Her legs were shuddering, and her pussy pulsing wildly, clamping down on my fingers."
    "I guess that means she wants more. I unzip my pants to reveal the cock she’d sucked before."
    shinn "Look at it. You like it right?"
    rina "..."
    "Her asshole was twitching. I guess she wants it there."
    shinn "Looks like want to have some more fun with your ass."
    rina "Wait... No..."
    "Rina looked back with a worried face."
    shinn "No what?"
    rina "Please don’t stick it into my ass..."
    shinn "Heh. Why not?"
    rina "It’s dirty..."
    shinn "Dirty? Nah. It’s okay."
    shinn "I’ll clean it up for you with my dick."
    "I set the tip of my cock against her ass."
    rina "No! Please..."
    shinn "Here it comes!"
    "I slowly thrust inside her slippery asshole."
    rina "Mmm~"
    "Once again, Rina lets a little moan slip out."
    "The more we continue, the more her real self is starting to show through."
    "I continue thrusting into her as I feel the walls of her rectum squeezing against me."
    shinn "Man. I didn’t your ass would be this tight."
    shinn "It’s almost like I’m fucking a real pussy back here."
    rina "No~"
    "I can feel her clamping down on me with every thrust."
    shinn "Heh... Seems like you really want me to cum."
    rina "No~ That’s not true. Please take it out!"
    rina "Its disgusting! "
    shinn "Ah! Disgusting?!"
    shinn "Why are you so concerned with what’s disgusting?"
    shinn "Look at yourself! Look at how dirty you are! "
    shinn "Out here getting fucked in the ass on the roof of the school."
    shinn "What does that make you? You’re nothing but a pig whore!"
    rina "..."
    "The more I mock and shame her, the harder I can feel her clamping down on my dick."
    rina "You’re... too... rough..."
    shinn "Too rough?"
    shinn "I don’t think so..."
    "I start to rail her ass even harder. She’s feeling the pleasure and pain blending together."
    rina "Ahh~"
    shinn "That’s right. A whore like you loves it like this."
    "With every insult and bit of dirty talk, I can feel her squeezing down more against me."
    shinn "You really do want me to cum, huh?"
    rina "No..."
    shinn "Stop lying to yourself."
    "I slam my dick into her even harder..."
    rina "..."
    "Rina is left speechless for a moment by the intensity of the feeling."
    "I was getting close to cumming. But, not without letting the little slut know first."
    shinn "Time for an anal creampie!"
    rina "Mmm~"
    "I shot my cum out into her ass."
    rina "Ahh~! Cum! "
    rina "Its flowing into my stomach! I can feel it!"
    "Her entire body was trembling again. I get the impression this is going to be a routine thing for her."
    "In fact, I’m going to make sure of that myself..."
    shinn "That’s right. Feel that hot cum inside your stomach."
    shinn "You dirty whore."
    "I took out my dick, letting the jizz I’d shot inside her flow free."
    shinn "Wow. That’s a lot."
    shinn "Heheh... I wasn’t expecting your ass to squeeze out so much."
    rina "..."
    "I took a look at her eyes. She looks drunk with lust."
    thinking "Seems like she’s already half broken..."
    thinking "Time for the final step."
    shinn "Done already? I’m not done yet."
    "My cock was still rock hard."
    shinn "See what I’ve got ready for you, Rina?"
    rina "..."
    "She looks at my cock with a dreamy expression."
    shinn "If you want my cock, go ahead and beg for it."
    rina "..."
    "For a moment, a look of shock penetrates her haze of lust."
    shinn "Don’t play dumb with me. I know you want my cock now. If you want it, show me and beg for it."
    rina "..."
    "I can tell she wants it, but she still resists saying it."
    "I keep pushing her for an answer, trying to force her the rest of the way."
    shinn "Don’t want it? Fine. We can end this right now and I can give you your phone back. But, you’ll never see my cock again."
    rina "..."
    shinn "So? What’s it going to be?"
    rina "Shinn... cock..."
    "She was whispering. I could just make her voice out, but I want to hear her loud and clear."
    shinn "What? You’ve gotta say it louder, I couldn’t hear you."
    "I apply a little more pressure, placing the tip of my cock at the entrance of her pussy."
    thinking "I can tell she’s about to give in."
    shinn "Come on... Say the magic words."
    "Feeling the sensation of my cock against her pussy, her control was starting to give way."
    "The more I rub up against her, the more impossible it becomes for her to restrain herself."
    "Her desire for my cock is overriding everything else in her mind."
    thinking "Anytime now..."
    "Just as I predicted, she hold herself back any longer."
    rina "I WANT SHINN’S BIG FAT COCK IN MY SLUTTY PUSSY!"
    "Just what I was waiting for."
    shinn "That’s what I wanted to hear."
    "I push inside her without hesitation."
    rina "Ah! Shinn! "
    "The inside of her pussy was amazing. It’s so tight, I can feel it squeezing down on me, even soaked with all her orgasms so far."
    "I start to pound her hard, her body reacting to every thrust."
    rina "Yes! More! More!"
    thinking "Looks like I’ve really done a number on her. I bet she doesn’t even know who she is right now."
    rina "Harder, Shinn! HARDER!"
    shinn "You’ve got it!"
    "I thrust even harder, causing her to tighten around me."
    "I can feel her squeezing down more and more as I pound her insides."
    shinn "Fuck, Rina! Your pussy feels so good!"
    rina "Yes! Love it more, fuck me harder!"
    "It’s getting hard to hold myself back now."
    shinn "It’s too much, I’m going to cum!"
    rina "YES! SHINN, CUM INSIDE ME! FILL ME UP WITH YOUR THICK BABY MILK!"

    if persistent.cum == "inside":
        thinking "Ugh. Hearing her talk dirty like that, I can’t take any more!"
        $ renpy.block_rollback()
        jump rina_rooftop_scene_1_inside

    elif persistent.cum == "outside":
        thinking "Ugh. Hearing her talk dirty like that, I can’t take any more!"
        $ renpy.block_rollback()
        jump rina_rooftop_scene_1_outside

    else:
        menu:
            thinking "Ugh. Hearing her talk dirty like that, I can’t take any more!"
            "Cum inside":
                $ renpy.block_rollback()
                jump rina_rooftop_scene_1_inside
            "Cum outside":
                $ renpy.block_rollback()
                jump rina_rooftop_scene_1_outside

label rina_rooftop_scene_1_inside:
    "I fulfill her wish and let out everything I’ve got into her womb. "
    "It was so much that it filled all the way to the brim, trickles leaking out from around my dick. "
    rina "Ah! Shinn’s baby seeds are inside me!"
    thinking "Eh. Pretty likely she’ll get pregnant from this after all. "
    "As soon as I’m done, I pull my dick out, sending the cum gushing out from her like a waterfall. "
    "She could no longer hold herself in position, and collapsed to the ground, a shaking mess."
    "I take a look over her, completely broken, paralyzed with pleasure. Seems to me like this lesson was a success."
    rina "Ughh~ Se… Sex…"
    "She was mumbling something incoherent. Maybe she wants more. I stand up and plant my foot on her ass."
    shinn "You are mine now, Rina. Understand? I want you to call me master from now on. "
    rina "Ah~ Yes Master!"
    $ persistent.rina_rooftop_scene_1 = True
    $ renpy.end_replay()
    jump rina_dog_scene_1


label rina_rooftop_scene_1_outside:
    "I ignored her plea and pull out quickly. The cum sprays out across her butt covering her entire back. "
    rina "Ah! Shinn’s cum is everywhere!"
    "She could no longer hold herself in position, and collapsed to the ground, a shaking mess."
    "I take a look over her, completely broken, paralyzed with pleasure. Seems to me like this lesson was a success."
    rina "Ughh~ Se… Sex…"
    "She was mumbling something incoherent. Maybe she wants more. I stand up and plant my foot on her ass."
    shinn "You are mine now, Rina. Understand? I want you to call me master from now on. "
    rina "Ah~ Yes Master!"
    $ persistent.rina_rooftop_scene_1 = True
    $ renpy.end_replay()
    jump rina_dog_scene_1
