define unknown = Character("???????")
define voicemail = Character("Voicemail")
define shinn = Character("Shinn")
define female = Character("Female Student")
define female_1 = Character("Female Student #1")
define female_2 = Character("Female Student #2")
define male = Character("Male Student")
define satsuki = Character("Satsuki")
