label harem_end:
    scene bg shinn bedroom with pixellate
    "Well, this is one for the books alright."
    "Taking this job with the school really was a great choice. I've done a damned good job here, if I say so myself."
    "Managing to make all these sexy girls into my personal sex slaves was quite a result all on its own."
    "But with the law being changed to permit polygamous marriage in order to combat declining birthrates..."
    "Well, I'd like to think the deals I made with some like-minded individuals played some part in that."
    "Having made all my personal sex slaves into my wives really completes the package."
    "And so, like any other day, my wives greet me as I return home."
    show aina happy naked arms with moveinleft
    aina "Welcome back, Master!"
    "Looks like Aina's the first one to the door to welcome me."
    shinn "Where are the others, Aina?"
    aina "Ah! They're all expecting you, Master!"
    "Aina's still energetic on her feet, despite her heavily swollen belly."
    "I'm pretty sure her due date is coming up soon, just like the others."
    "But that doesn't stop her from running to the door to greet me, and it certainly hasn't held her back in the bedroom."
    shinn "How's the baby, Aina?"
    aina "Heh. She kicked a little when she felt you nearby, Master."
    aina "She really loves the father a lot."
    shinn "That's great to hear."
    aina "Oh, speaking of which, the rest are waiting for you upstairs."
    shinn "I see. Let's go then."
    "Aina accompanies me upstairs to our bedroom."
    "She opens the door for me, revealing the rest of the girls lying together on the bed, presenting their pussies, spread and ready for me."
    "Quite a greeting they've prepared for me."
    "After all the adventures I had together in school with these girls, they've all completely submitted to me in body and spirit."
    "Their huge bellies don't stop them from getting in position for me, waiting eagerly for me to give them the mating press."
    everyone "Welcome back, master!"
    "Aina takes up her place in the bed alongside Touko."
    aina "Please give us all of your cum, Master!"
    "Seeing how eager to please my slaves are, I can't help wanting to give them a proper reward."
    "I strip myself naked for them, already erect since Aina met me at the door."
    "Of course, the girls immediately go crazy."
    ritsuko "Ah~ Master's big cock! It's really coming! He's gonna give it to all of us!"
    "Well, like the saying goes, ‘ladies first.' I might as well start things off with the mature woman of the group."
    "I move over towards Rina."
    "She makes no effort to conceal her excitement as she sees me approach."
    rina "Ah! Master is giving me the first~!"
    shinn "Heh. Good girl. Are you ready for my dick?"
    rina "Yes! Please give it to me!"
    "I slowly push inside her already sopping wet pussy."
    rina "Ah~ Shinn!"
    "It's the same perfect fit as always. After all the times I've fucked her, it's only natural that her pussy would take on the shape of my dick."
    "Despite all the use, she's still as tight as ever. Her daily exercise squeezing down on my dick really seems to have paid off."
    "I slowly move inside her, savoring the warm, slick feeling of her pussy gliding over me."
    rina "Master's cock! I love it! Give me more!"
    "I oblige by picking up speed until I'm slamming her as hard as I can, her ass shuddering against me with every stroke."
    "The moment I reach full tempo, she cums, trembling and squeezing on my cock."
    rina "Ah~! C-cumming... !"
    "Her juices which gush out as she cums make my strokes glide inside her even more smoothly, hitting her deepest spots."
    "With all the pressure bearing down on her, her belly starts to move a bit."
    rina "Ah~ The baby loves it!"
    "I start to pick up even more speed, moving at a frantic pace now."
    rina "Yes, Master! Faster! Harder!"
    rina "Put it all inside me! The baby and I want your hot thick milk!"
    "I give Rina one last good slam against her baby-making hips, penetrating deep into her womb and marinating her insides with my cum."
    rina "Ah~ Master's cum!"
    "As her whole body shudders with the force of her orgasm, her breast milk starts to leak out from her nipples."
    rina "Ah...  My milk started coming out too when you put yours in me~"
    "I slowly pull out my dick, letting out the river of cum I've left inside her."
    "Needless to say, Rina is loving the attention."
    rina "So much of Master's cum! I want more~!"
    "But I ignore her request. After all, I've got all these other girls still waiting on me."
    "If there's another lady in this group, it'd be Ritsuko, so I'll follow up with her next."
    ritsuko "Ah~ Its my turn~"
    "I position myself and slowly insert myself inside her pussy as well, her juices mixing together with Rina's."
    "The moment I push inside her, she's so aroused that she starts to lactate as well."
    ritsuko "Ah~ My breast milk is flowing out~"
    "Seizing the opportunity, I lean forward and begin to suck the milk from her nipple."
    ritsuko "Shinn! That's supposed to be for the baby!"
    "I couldn't care less whose it's supposed to be. I just can't get enough of the taste of your sweet milk."
    ritsuko "Geez, Master~ You are really like a child, you know?"
    ritsuko "If you really like it that much..."
    ritsuko "Go ahead and drink as much of my milk as you like, okay?"
    "I continue to suck away at her breast, savoring her milk."
    "With my dick still inside her, I start to move my hips again."
    ritsuko "Ah~ Master's dick! I've been waiting all day for this!"
    "It's hot and wet inside her, with a particular lively feeling that really reminds you that this is a high school girl's pussy."
    "I move slowly to stat, but Ritsuko is obviously feeling it."
    ritsuko "Ah~ Master's dick is inside me! It feels so good!"
    "She keeps gushing about how amazing it is, spurring me on to pound her even harder. In no time at all, she's gushing down below as well."
    "The more I thrust into her, the tighter she squeezes me."
    "Her belly shakes constantly with the force of my movements."
    "It doesn't take long before I start to feel the urge again to release the pent up cum from my balls."
    "I keep thrusting deep into her, as far as I can into the depths of her womb."
    ritsuko "Ah~ Its so deep~!"
    ritsuko "Please cum, Master! Please give our baby your milk!"
    "I answer her pleading, releasing a load of my cum deep inside her."
    ritsuko "Ah~ Master's cum!"
    "I take a moment to savor the feeling of filling up Ritsuko's womb before I pull out."
    "Her pussy gushes with my cum the moment I pull free."
    ritsuko "Ah~ It's so much! I love it!"
    "As I leave Ritsuko drowning in the pleasure of my cum, I move on to my next wife waiting on my attention."
    "Touko has been waiting for me patiently. As the saying goes, good things come to those who wait."
    touko "Mmm~ Master, I'm ready!"
    "Her shy but eager look immediately has me at full mast again as well."
    "Seeing her huge pregnant belly under me just gets me going even more."
    "I slowly slide inside her dripping pussy."
    touko "Ahh~"
    "Touko is more demure than the last two, but despite her quiet reaction, her face clearly shows her pleasure."
    touko "Mmm~ Master's dick..."
    "Although she's still keeping her voice down, her pussy's gripping me just as hard as the others."
    "She might actually be the most ladylike of all of them, but she's just as much of a tiger in the sheets."
    "I pick up the pace, pounding her hips even faster..."
    touko "Ahh~"
    "Her pleasure is getting more intense by the moment. It seems like she's struggling to contain herself."
    touko "Mmm~ Ahh~"
    "So am I. The way she's squeezing down on my cock, I can't last much longer."
    "Rather than hold back, I power ahead, pounding her at full force until I burst inside her.."
    touko "Ahh~! Master's cum~!"
    "The instant she feels me let loose, she cums as well, her breast milk spraying out with her excitement just like the girls before her."
    touko "Ahh~!"
    "All the composure is completely blown from her face, her mind left blank by the force of her orgasm."
    touko "Amazing..."
    touko "I'm sure the baby inside me will like it too..."
    "Now that Touko's satisfied, only Aina is left."
    "The first one waiting for me at the door, and the last one still waiting for me in bed."
    aina "Master~ It's my turn!"
    "I can't resist that bright smile. Even after going through all the others, I'm as eager to fuck her as ever."
    "There's no need for me to wait to recharge. I thrust inside her without hesitation."
    aina "Ah! Master's inside me!"
    "She immediately starts moving on her own, thrusting her hips against me."
    aina "Master~! Master~!"
    "She keeps calling out for me like she's begging me for more."
    "Unlike Touko, she doesn't hold herself back at all. Whereas I've had the girls before her to take the edge off, she's only gotten more and more worked up watching."
    "Her legs shake as I slam into her, feeling her squeeze down on me as she cums over and over on my cock."
    aina "Master! Please cum inside me!"
    aina "Please give me and the baby your milk!"
    "Her pleading finally pushes me over the edge, and I unload everything still remaining in my balls inside her."
    aina "Ahh! Master's cum! It's amazing!"
    "She shudders uncontrollably as I pull my dick out, and I move back to take in the beautiful scenery."
    "All of the girls are completely overwhelmed, their pussies drenched with cum."
    "The whole room is permeated with the smell of cum and the sweet scent of their breast milk."
    "Honestly, I can't get enough of it."
    "Taking it all in, I start to feel I have a little left inside me, and start to jerk off over them."
    "The girls take in the sight in a fascinated daze."
    "With the stamina I have left, I let out a surprisingly huge load of cum over them."
    "It showers down on them, spattering across their legs."
    shinn "Beautiful."
    rina "Ahh~ More of Shinn's cum..."
    touko "Mmm~"
    ritsuko "It smells so good!"
    aina "Ahh~"
    "All of them are completely blissed out, covered in my cum."
    rina "Its not over yet, Master~"
    touko "Mmm~ We want more Master~"
    everyone "Please make more babies with us, Master!"
    "These girls..."
    "They really never get tired of this."
    "This is our daily routine now."
    "And soon, they'll give birth to my children, and we can do this again and again."
    "I'm looking forward to it."
    "We're gonna be one hell of a big happy family."
    jump end

label end:
    scene black with dissolve
    "Thank you for playing the first beta for Break: The Rematch!"
    "If you have any comments or concerns, please let use know!"
    return
